[program:spinorama-api]
command=/bin/bash -c 'cd /home/spin/run/spin-api && source ./.venv/bin/activate && ./gunicorn_start.sh'
user=spin
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/spin/log/gunicorn.log
