# -*- coding: utf-8 -*-
"""Backwards-compatibility shim. See ``spinorama.compute.scores``."""

from spinorama.compute.scores import (
    Any,
    LFQ_DEFAULT,
    LFX_DEFAULT,
    List,
    Tuple,
    aad,
    consecutive_groups,
    floating,
    lfq,
    lfx,
    linregress,
    logger,
    mad,
    nbd,
    octave,
    pref_rating,
    round_down,
    sm,
    speaker_pref_rating,
)

__all__ = [
    "Any",
    "LFQ_DEFAULT",
    "LFX_DEFAULT",
    "List",
    "Tuple",
    "aad",
    "consecutive_groups",
    "floating",
    "lfq",
    "lfx",
    "linregress",
    "logger",
    "mad",
    "nbd",
    "octave",
    "pref_rating",
    "round_down",
    "sm",
    "speaker_pref_rating",
]
