[package]
name = "compute_scores_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "compute_scores_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29", features = ["extension-module"] }
numpy = "0.29"
ndarray = { version = "0.17", features = ["rayon"] }
num-traits = "0.2"
rayon = "1.11"
rand = "0.9"
