[package]
name = "compute_scores_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "compute_scores_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.26.0", features = ["extension-module"] }
numpy = "0.26"
ndarray = { version = "0.16.1", features = ["rayon"] }
ndarray-stats = "0.6.0"
num-traits = "0.2.19"
rayon = "1.11.0"
rand = "0.9.3"
