project:
  type: website
  output-dir: ../dist/docs

website:
  title: "Spinorama"
  # favicon: "images/favicon.png"
  open-graph: true
  twitter-card: true
  site-url: https://docs.spinorama.org
  repo-url: https://github.com/pierreaubert/spinorama
  issue-url: https://github.com/pierreaubert/spinorama/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  search:
    location: navbar
    type: overlay
  page-footer:
    left: |
      Proudly GPL
    center:
      - text: "FAQ"
        href: 05_faq.qmd
    right:
      - icon: twitter
        href: https://x.com/pierreaubert
        aria-label: Spinorama Twitter
      - icon: github
        href: https://github.com/pierreaubert/spinorama
        aria-label: Spinorama GitHub
  navbar:
    background: light
    title: false
    collapse-below: lg
    left:
      - text: "Back to Spinorama.org"
        href: "https://spinorama.org"
      - text: "Website"
        href: 01_intro.qmd
      - text: "Software"
      - menu:
        - text: "How to install the software"
          href: 02_install.qmd
        - text: "How to add new speakers?"
          href: 03_metadata.qmd
        - text: "How to use the library"
          href: 04_library.qmd
        - text: "How to compute a spinorama"
          href: 08_compute_spin.qmd
      - text: "API"
        href: 09_api.qmd
      - text: "FAQ"
        href: 05_faq.qmd
    tools:
      - icon: twitter
        href: https://x.com/pierreaubert
        text: Spinorama Twitter
      - icon: github
        href: https://github.com/pierreaubert/spinorama
        text: Spinorama GitHub

  sidebar:
    - id: website
      collapse-level: 3
      contents:
        - section: "Help for Spinorama.org"
          href: 01_intro.qmd
        - section: "How to install the software?"
          href: 02_install.qmd
        - section: "How to add a speaker?"
          href: 03_metadata.qmd
        - section: "How to use the library?"
          href: 04_library.qmd
        - section: "Compute a spinorama"
          href: 08_compute_spin.qmd
        - section: "API"
          href: 09_api.qmd
        - section: "FAQ"
          href: 05_faq.qmd
        - section: "Data sources"
          href: 06_sources.qmd
        - section: "Bibliography"
          href: 07_biblio.qmd


bibliography: audio.bib

format:
  html:
    toc: true
    toc-depth: 3
    toc-title: "On this page"
    toc-location: right
    theme:
      light: [cosmo]
    code-copy: true
    code-overflow: wrap
    highlight-style: github
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
    footnotes-hover: true
    citations-hover: true
    grid:
      sidebar-width: 0px
      body-width: 900px
      margin-width: 300px

freeze: true
