# -*- coding: utf-8 -*-
# generated by generate_headphone_datas.py

from . import HeadphoneDatabase

headphones_info_k: HeadphoneDatabase = {
    'KZ CCA Trio': {
        "brand": 'KZ',
        "model": 'CCA Trio',
        "shape": 'in-ear',
        "default_measurement": 'asr',
        "price": '44.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/cca-trio-3dd-iem-review.58772/',
                'review_published': '20241125',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 71.0,
            },
        },
    },
    'KZ Castor (Harman Target/Silver)': {
        "brand": 'KZ',
        "model": 'Castor (Harman Target/Silver)',
        "shape": 'in-ear',
        "default_measurement": 'asr',
        "price": '22.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/kz-castor-harman-target-iem-review.54262/',
                'review_published': '20240507',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 101.0,
            },
        },
    },
    'KZ ZSX': {
        "brand": 'KZ',
        "model": 'ZSX',
        "shape": 'in-ear',
        "default_measurement": 'asr',
        "price": '60.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/kz-zsx-iem-review.49409/',
                'review_published': '20231109',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 27.0,
            },
        },
    },
    'Kennerton Rognir': {
        "brand": 'Kennerton',
        "model": 'Rognir',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '3770.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/kennerton-rognir-review-closed-back-headphone.27362/',
                'review_published': '20211017',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 143.0,
            },
        },
    },
    'Koss Porta Pro': {
        "brand": 'Koss',
        "model": 'Porta Pro',
        "shape": 'on-ear',
        "default_measurement": 'asr',
        "price": '50.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/koss-porta-pro-review-on-ear-headphone.29137/',
                'review_published': '20211217',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 102.0,
            },
        },
    },
}
