# -*- coding: utf-8 -*-
# generated by generate_headphone_datas.py

from . import HeadphoneDatabase

headphones_info_v: HeadphoneDatabase = {
    'Verisonix Pro DJ N1502C': {
        "brand": 'Verisonix',
        "model": 'Pro DJ N1502C',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '120.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/verisonix-pro-dj-review-hybrid-electrostatic-headphone.25050/',
                'review_published': '20210718',
                'recommendation': 'No',
                "sensitivity_mV_94dB": 66.0,
            },
        },
    },
    'Verum Audio Verum 1': {
        "brand": 'Verum Audio',
        "model": 'Verum 1',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '349.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/verum-audio-verum-1-review-headphone.31461/',
                'review_published': '20220306',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 54.0,
            },
        },
    },
    'Verum Audio Verum 2 (Pearl)': {
        "brand": 'Verum Audio',
        "model": 'Verum 2 (Pearl)',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '425.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/verum-audio-verum-2-headphone-review.68258/',
                'review_published': '20251220',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 154.0,
            },
        },
    },
}
