# -*- coding: utf-8 -*-
# generated by generate_headphone_datas.py

from . import HeadphoneDatabase

headphones_info_m: HeadphoneDatabase = {
    "MOONDROP Chu II": {
        "brand": "MOONDROP",
        "model": "Chu II",
        "shape": "in-ear",
        "default_measurement": "asr",
        "price": "19.00",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "csv_freq_spl",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/moondrop-chu-ii-iem-review.55179/",
                "review_published": "20240616",
                "recommendation": "Yes",
                "sensitivity_mV_94dB": 61.0,
            },
        },
    },
    "MOONDROP Para 2": {
        "brand": "MOONDROP",
        "model": "Para 2",
        "shape": "over-ear",
        "default_measurement": "asr",
        "price": "500.00",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "csv_freq_spl",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/moondrop-para-2-planar-headphone-review.66579/",
                "review_published": "20251010",
                "recommendation": "Yes",
                "sensitivity_mV_94dB": 228.0,
            },
        },
    },
    "Meze Audio 105 AER": {
        "brand": "Meze Audio",
        "model": "105 AER",
        "shape": "over-ear",
        "default_measurement": "asr",
        "price": "399.00",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "csv_freq_spl",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/meze-audio-105-aer-headphone-review.61717/",
                "review_published": "20250324",
                "recommendation": "Yes",
                "sensitivity_mV_94dB": 91.0,
            },
        },
    },
    "Meze Audio Liric": {
        "brand": "Meze Audio",
        "model": "Liric",
        "shape": "over-ear",
        "default_measurement": "asr",
        "price": "2000.00",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "csv_freq_spl",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/meze-liric-review-closed-back-headphone.29404/",
                "review_published": "20211228",
                "recommendation": "No",
                "sensitivity_mV_94dB": 204.0,
            },
        },
    },
    "Monoprice M1570C": {
        "brand": "Monoprice",
        "model": "M1570C",
        "shape": "over-ear",
        "default_measurement": "asr",
        "price": "600.00",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "csv_freq_spl",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/monoprice-m1570c-headphone-review.45837/",
                "review_published": "20230623",
                "recommendation": "No",
                "sensitivity_mV_94dB": 240.0,
            },
        },
    },
    "Monoprice Monolith M565": {
        "brand": "Monoprice",
        "model": "Monolith M565",
        "shape": "over-ear",
        "default_measurement": "asr",
        "price": "199.00",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "csv_freq_spl",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/monoprice-monolith-m565-headphone-review.63826/",
                "review_published": "20250627",
                "recommendation": "No",
            },
        },
    },
}
