# -*- coding: utf-8 -*-
# generated by generate_headphone_datas.py

from . import HeadphoneDatabase

headphones_info_6: HeadphoneDatabase = {
    '64 Audio tia Trió': {
        "brand": '64 Audio',
        "model": 'tia Trió',
        "shape": 'in-ear',
        "default_measurement": 'asr',
        "price": '2299.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/64-audio-tia-tri%C3%B3-iem-review.42405/',
                'review_published': '20230225',
                'recommendation': 'No',
                "sensitivity_mV_94dB": 27.0,
            },
        },
    },
}
