# -*- coding: utf-8 -*-
# generated by generate_headphone_datas.py

from . import HeadphoneDatabase

headphones_info_7: HeadphoneDatabase = {
    "7HZ Crinacle Zero: 2": {
        "brand": "7HZ",
        "model": "Crinacle Zero: 2",
        "shape": "in-ear",
        "default_measurement": "asr",
        "price": "24.99",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "csv_freq_spl",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/7hz-x-crinacle-zero-2-iem-review.50534/",
                "review_published": "20231218",
                "recommendation": "Yes",
                "sensitivity_mV_94dB": 50.0,
            },
        },
    },
    "7HZ Salnotes Zero": {
        "brand": "7HZ",
        "model": "Salnotes Zero",
        "shape": "in-ear",
        "default_measurement": "asr",
        "price": "20.00",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "csv_freq_spl",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/7hz-salnotes-zero-iem-review.50226/",
                "review_published": "20231208",
                "recommendation": "Yes",
                "sensitivity_mV_94dB": 52.0,
            },
        },
    },
    "7HZ Timeless": {
        "brand": "7HZ",
        "model": "Timeless",
        "shape": "in-ear",
        "default_measurement": "asr",
        "price": "220.00",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "csv_freq_spl",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/7hertz-timeless-iem-review.61773/",
                "review_published": "20250327",
                "recommendation": "Yes",
                "sensitivity_mV_94dB": 73.0,
            },
        },
    },
}
