# -*- coding: utf-8 -*-
# generated by generate_headphone_datas.py

from . import HeadphoneDatabase

headphones_info_t: HeadphoneDatabase = {
    'TANCHJIM Origin': {
        "brand": 'TANCHJIM',
        "model": 'Origin',
        "shape": 'in-ear',
        "default_measurement": 'asr',
        "price": '260.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/tanchjim-origin-iem-review.52707/',
                'review_published': '20240303',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 48.0,
            },
        },
    },
    'THIEAUDIO GHOST': {
        "brand": 'THIEAUDIO',
        "model": 'GHOST',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '129.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/thieaudio-ghost-headphone-review.61739/',
                'review_published': '20250326',
                'recommendation': 'No',
                "sensitivity_mV_94dB": 143.0,
            },
        },
    },
    'TRUTHEAR Crinacle Zero Blue2': {
        "brand": 'TRUTHEAR',
        "model": 'Crinacle Zero Blue2',
        "shape": 'in-ear',
        "default_measurement": 'asr',
        "price": '65.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/truthear-x-crinacle-zero-blue2-iem-review.62096/',
                'review_published': '20250410',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 71.0,
            },
        },
    },
    'TRUTHEAR Crinacle Zero:RED': {
        "brand": 'TRUTHEAR',
        "model": 'Crinacle Zero:RED',
        "shape": 'in-ear',
        "default_measurement": 'asr',
        "price": '55.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/truthear-x-crinacle-zero-red-iem-review.44865/',
                'review_published': '20230520',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 66.0,
            },
        },
    },
    'TRUTHEAR GATE': {
        "brand": 'TRUTHEAR',
        "model": 'GATE',
        "shape": 'in-ear',
        "default_measurement": 'asr',
        "price": '17.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/truthear-gate-17-iem-review.61784/',
                'review_published': '20250327',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 48.0,
            },
        },
    },
    'TRUTHEAR Zero': {
        "brand": 'TRUTHEAR',
        "model": 'Zero',
        "shape": 'in-ear',
        "default_measurement": 'asr',
        "price": '50.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/truthear-x-crinacle-zero-iem-review.37380/',
                'review_published': '20220915',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 74.0,
            },
        },
    },
    'Takstar Pro 82': {
        "brand": 'Takstar',
        "model": 'Pro 82',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '80.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/takstar-pro-82-review-headphone.24878/',
                'review_published': '20210711',
                'recommendation': 'No',
                "sensitivity_mV_94dB": 108.0,
            },
        },
    },
    'Tascam TH-07': {
        "brand": 'Tascam',
        "model": 'TH-07',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '75.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/tascam-th-07-review-headphone.23140/',
                'review_published': '20210506',
                'recommendation': 'No',
                "sensitivity_mV_94dB": 113.0,
            },
        },
    },
    'Topping Hane': {
        "brand": 'Topping',
        "model": 'Hane',
        "shape": 'in-ear',
        "default_measurement": 'asr',
        "price": '129.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/topping-hane-iem-review.59640/',
                'review_published': '20241229',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 174.0,
            },
        },
    },
}
