# -*- coding: utf-8 -*-
# generated by generate_headphone_datas.py

from . import HeadphoneDatabase

headphones_info_b: HeadphoneDatabase = {
    "Beyerdynamic Amiron": {
        "brand": "Beyerdynamic",
        "model": "Amiron",
        "shape": "over-ear",
        "default_measurement": "asr",
        "price": "400.00",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "csv_freq_spl",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/beyerdynamic-amiron-home-review-headphone.27734/",
                "review_published": "20211031",
                "recommendation": "No",
                "sensitivity_mV_94dB": 212.0,
            },
        },
    },
    "Beyerdynamic DT 880 600 Ohm": {
        "brand": "Beyerdynamic",
        "model": "DT 880 600 Ohm",
        "shape": "over-ear",
        "default_measurement": "asr",
        "price": "198.00",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "csv_freq_spl",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/beyerdynamic-dt-880-600-ohm-review-headphone.24694/",
                "review_published": "20210702",
                "recommendation": "No",
                "sensitivity_mV_94dB": 948.0,
            },
        },
    },
    "Beyerdynamic DT150": {
        "brand": "Beyerdynamic",
        "model": "DT150",
        "shape": "over-ear",
        "default_measurement": "asr",
        "price": "210.00",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "csv_freq_spl",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/beyerdynamic-dt150-review-closed-back-headphone.31257/",
                "review_published": "20220226",
                "recommendation": "No",
                "sensitivity_mV_94dB": 400.0,
            },
        },
    },
    "Beyerdynamic DT1990 Pro": {
        "brand": "Beyerdynamic",
        "model": "DT1990 Pro",
        "shape": "over-ear",
        "default_measurement": "asr",
        "price": "529.00",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "csv_freq_spl",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/beyerdynamic-dt-1990-pro-headphone-review.54872/",
                "review_published": "20240603",
                "recommendation": "No",
                "sensitivity_mV_94dB": 306.0,
            },
        },
    },
    "Beyerdynamic DT990 Pro (250 ?)": {
        "brand": "Beyerdynamic",
        "model": "DT990 Pro (250 ?)",
        "shape": "over-ear",
        "default_measurement": "asr",
        "price": "160.00",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "csv_freq_spl",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/beyerdynamic-dt990-pro-review-headphone.19975/",
                "review_published": "20210131",
                "recommendation": "No",
                "sensitivity_mV_94dB": 704.0,
            },
        },
    },
    "Beyerdynamic T1 V2": {
        "brand": "Beyerdynamic",
        "model": "T1 V2",
        "shape": "over-ear",
        "default_measurement": "asr",
        "price": "1050.00",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "csv_freq_spl",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/beyerdynamic-t1-review-v2-headphone.20192/",
                "review_published": "20210207",
                "recommendation": "No",
                "sensitivity_mV_94dB": 370.0,
            },
        },
    },
    "Bose NC700": {
        "brand": "Bose",
        "model": "NC700",
        "shape": "over-ear",
        "default_measurement": "asr",
        "price": "379.00",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "csv_freq_spl",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/bose-nc700-review-noise-cancelling-headphone.24667/",
                "review_published": "20210701",
                "recommendation": "No",
                "sensitivity_mV_94dB": 0.0,
            },
        },
    },
    "Bose QuietComfort 45": {
        "brand": "Bose",
        "model": "QuietComfort 45",
        "shape": "over-ear",
        "default_measurement": "asr",
        "price": "329.00",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "csv_freq_spl",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/bose-quietcomfort-45-headphone-review.46500/",
                "review_published": "20230718",
                "recommendation": "Yes",
                "sensitivity_mV_94dB": 0.0,
            },
        },
    },
    "Bowers & Wilkins P5 V1": {
        "brand": "Bowers & Wilkins",
        "model": "P5 V1",
        "shape": "on-ear",
        "default_measurement": "asr",
        "price": "300.00",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "csv_freq_spl",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/bowers-wilkins-p5-review-portable-headphone.20337/",
                "review_published": "20210212",
                "recommendation": "No",
                "sensitivity_mV_94dB": 69.0,
            },
        },
    },
    "Bowers & Wilkins P7": {
        "brand": "Bowers & Wilkins",
        "model": "P7",
        "shape": "over-ear",
        "default_measurement": "asr",
        "price": "400.00",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "csv_freq_spl",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/bowers-wilkins-p7.65733/",
                "review_published": "20250911",
                "recommendation": "No",
                "sensitivity_mV_94dB": 93.0,
            },
        },
    },
}
