# -*- coding: utf-8 -*-
# generated by generate_headphone_datas.py

from . import HeadphoneDatabase

from .headphone_0 import headphones_info_0
from .headphone_1 import headphones_info_1
from .headphone_2 import headphones_info_2
from .headphone_3 import headphones_info_3
from .headphone_4 import headphones_info_4
from .headphone_5 import headphones_info_5
from .headphone_6 import headphones_info_6
from .headphone_7 import headphones_info_7
from .headphone_8 import headphones_info_8
from .headphone_9 import headphones_info_9
from .headphone_a import headphones_info_a
from .headphone_b import headphones_info_b
from .headphone_c import headphones_info_c
from .headphone_d import headphones_info_d
from .headphone_e import headphones_info_e
from .headphone_f import headphones_info_f
from .headphone_g import headphones_info_g
from .headphone_h import headphones_info_h
from .headphone_i import headphones_info_i
from .headphone_j import headphones_info_j
from .headphone_k import headphones_info_k
from .headphone_l import headphones_info_l
from .headphone_m import headphones_info_m
from .headphone_n import headphones_info_n
from .headphone_o import headphones_info_o
from .headphone_p import headphones_info_p
from .headphone_q import headphones_info_q
from .headphone_r import headphones_info_r
from .headphone_s import headphones_info_s
from .headphone_t import headphones_info_t
from .headphone_u import headphones_info_u
from .headphone_v import headphones_info_v
from .headphone_w import headphones_info_w
from .headphone_x import headphones_info_x
from .headphone_y import headphones_info_y
from .headphone_z import headphones_info_z


headphones_info: HeadphoneDatabase = (
    headphones_info_0
    | headphones_info_1
    | headphones_info_2
    | headphones_info_3
    | headphones_info_4
    | headphones_info_5
    | headphones_info_6
    | headphones_info_7
    | headphones_info_8
    | headphones_info_9
    | headphones_info_a
    | headphones_info_b
    | headphones_info_c
    | headphones_info_d
    | headphones_info_e
    | headphones_info_f
    | headphones_info_g
    | headphones_info_h
    | headphones_info_i
    | headphones_info_j
    | headphones_info_k
    | headphones_info_l
    | headphones_info_m
    | headphones_info_n
    | headphones_info_o
    | headphones_info_p
    | headphones_info_q
    | headphones_info_r
    | headphones_info_s
    | headphones_info_t
    | headphones_info_u
    | headphones_info_v
    | headphones_info_w
    | headphones_info_x
    | headphones_info_y
    | headphones_info_z
)
