# -*- coding: utf-8 -*-
# generated by generate_headphone_datas.py

from . import HeadphoneDatabase

headphones_info_z: HeadphoneDatabase = {
    'ZMF Atrium Closed': {
        "brand": 'ZMF',
        "model": 'Atrium Closed',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '2500.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/zmf-atrium-closed-headphone-review.63815/',
                'review_published': '20250626',
                'recommendation': 'No',
                "sensitivity_mV_94dB": 254.0,
            },
        },
    },
    'ZMF Atticus': {
        "brand": 'ZMF',
        "model": 'Atticus',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '1099.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/zmf-atticus-review-headphone.24191/',
                'review_published': '20210613',
                'recommendation': 'No',
                "sensitivity_mV_94dB": 239.0,
            },
        },
    },
    'ZMF Bokeh': {
        "brand": 'ZMF',
        "model": 'Bokeh',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '1100.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/zmf-bokeh-headphone-review.54596/',
                'review_published': '20240521',
                'recommendation': 'No',
                "sensitivity_mV_94dB": 131.0,
            },
        },
    },
    'ZMF Caldera': {
        "brand": 'ZMF',
        "model": 'Caldera',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '3500.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/zmf-caldera-headphone-review.50016/',
                'review_published': '20231130',
                'recommendation': 'N/A',
                "sensitivity_mV_94dB": 208.0,
            },
        },
    },
}
