# -*- coding: utf-8 -*-
# generated by generate_headphone_datas.py

from . import HeadphoneDatabase

headphones_info_d: HeadphoneDatabase = {
    'DROP &amp; SENNHEISER PC38X': {
        "brand": 'DROP &amp; SENNHEISER',
        "model": 'PC38X',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '169.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/drop-sennheiser-pc38x-review-headphone.24462/',
                'review_published': '20210623',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 149.0,
            },
        },
    },
    'Dan Clark Audio (MrSpeakers) AEON 2 Noire': {
        "brand": 'Dan Clark Audio (MrSpeakers)',
        "model": 'AEON 2 Noire',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '850.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/dan-clark-audio-aeon-2-noire-review.46055/',
                'review_published': '20230701',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 353.0,
            },
        },
    },
    'Dan Clark Audio (MrSpeakers) AEON RT': {
        "brand": 'Dan Clark Audio (MrSpeakers)',
        "model": 'AEON RT',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '500.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/dan-clark-audio-aeon-rt-review-closed-headphone.19393/',
                'review_published': '20210114',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 677.0,
            },
        },
    },
    'Dan Clark Audio (MrSpeakers) Ether Flow 1.1': {
        "brand": 'Dan Clark Audio (MrSpeakers)',
        "model": 'Ether Flow 1.1',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '1799.99',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/dan-clark-audio-ether-flow-1-1-headphone-review.45821/',
                'review_published': '20230622',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 164.0,
            },
        },
    },
    'Dan Clark Audio AEON CORE': {
        "brand": 'Dan Clark Audio',
        "model": 'AEON CORE',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '899.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/dan-clark-%C3%86on-core-headphone-review.71702/',
                'review_published': '20260604',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 316.0,
            },
        },
    },
    'Dan Clark Audio E3': {
        "brand": 'Dan Clark Audio',
        "model": 'E3',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '1999.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/dan-clark-e3-headphone-review.50062/',
                'review_published': '20231202',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 512.0,
            },
        },
    },
    'Dan Clark Audio Expanse': {
        "brand": 'Dan Clark Audio',
        "model": 'Expanse',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '4000.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/dan-clark-expanse-headphone-review.37332/',
                'review_published': '20220912',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 665.0,
            },
        },
    },
    'Dan Clark Audio NOIRE X': {
        "brand": 'Dan Clark Audio',
        "model": 'NOIRE X',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '999.99',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/dan-clark-noire-x-headphone-review.58795/',
                'review_published': '20241126',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 333.0,
            },
        },
    },
    'Dan Clark Audio NOIRE XO': {
        "brand": 'Dan Clark Audio',
        "model": 'NOIRE XO',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '1299.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/dan-clark-noire-xo-headphone-review.62779/',
                'review_published': '20250509',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 370.0,
            },
        },
    },
    'Drop & Focal Elex': {
        "brand": 'Drop & Focal',
        "model": 'Elex',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '700.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/massdrop-x-focal-elex-review-headphone.22331/',
                'review_published': '20210409',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 180.0,
            },
        },
    },
    'Drop & Meze 99 Noir': {
        "brand": 'Drop & Meze',
        "model": '99 Noir',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '200.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/massdrop-x-meze-99-noir-review-headphone.23116/',
                'review_published': '20210505',
                'recommendation': 'No',
                "sensitivity_mV_94dB": 47.0,
            },
        },
    },
    'Drop & MrSpeakers Ether CX': {
        "brand": 'Drop & MrSpeakers',
        "model": 'Ether CX',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '900.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/drop-ether-cx-review-closed-planar-headphone.24681/',
                'review_published': '20210702',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 182.0,
            },
        },
    },
    'Drop & THX Panda': {
        "brand": 'Drop & THX',
        "model": 'Panda',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '399.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/drop-thx-panda-review-headphone.23277/',
                'review_published': '20210510',
                'recommendation': 'No',
                "sensitivity_mV_94dB": 68.0,
            },
        },
    },
    'Drop &amp; AKG K7XX': {
        "brand": 'Drop &amp; AKG',
        "model": 'K7XX',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '258.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/drop-akg-k7xx-review-headphone.24732/',
                'review_published': '20210705',
                'recommendation': 'No',
                "sensitivity_mV_94dB": 210.0,
            },
        },
    },
    'Drop THX Panda': {
        "brand": 'Drop',
        "model": 'THX Panda',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '399.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/drop-thx-panda-review-headphone.23277/',
                'review_published': '20210510',
                'recommendation': 'No',
                "sensitivity_mV_94dB": 68.0,
            },
        },
    },
    'Drop+Grell OAE1': {
        "brand": 'Drop+Grell',
        "model": 'OAE1',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '100.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/drop-grell-oae1-headphone-review.71097/',
                'review_published': '20260430',
                'recommendation': 'No',
                "sensitivity_mV_94dB": 348.0,
            },
        },
    },
}
