# -*- coding: utf-8 -*-
# generated by generate_headphone_datas.py

from . import HeadphoneDatabase

headphones_info_j: HeadphoneDatabase = {
    'JBL Endurance Run 2': {
        "brand": 'JBL',
        "model": 'Endurance Run 2',
        "shape": 'in-ear',
        "default_measurement": 'asr',
        "price": '9.95',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/jbl-endurance-run-2-wired-iem-review.58635/',
                'review_published': '20241119',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 56.0,
            },
        },
    },
    'JH Audio JH Audio custom made IEM': {
        "brand": 'JH Audio',
        "model": 'JH Audio custom made IEM',
        "shape": 'in-ear',
        "default_measurement": 'asr',
        "price": '2299.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/jerry-harvey-jh-custom-iem-review.56926/',
                'review_published': '20240911',
                'recommendation': 'No',
                "sensitivity_mV_94dB": 13.0,
            },
        },
    },
}
