# -*- coding: utf-8 -*-
# generated by generate_headphone_datas.py

from . import HeadphoneDatabase

headphones_info_1: HeadphoneDatabase = {
    '1More P50': {
        "brand": '1More',
        "model": 'P50',
        "shape": 'in-ear',
        "default_measurement": 'asr',
        "price": '120.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/1more-penta-driver-iem-review.55470/',
                'review_published': '20240701',
                'recommendation': 'No',
                "sensitivity_mV_94dB": 67.0,
            },
        },
    },
    '1More Sonoflow NC': {
        "brand": '1More',
        "model": 'Sonoflow NC',
        "shape": 'over-ear',
        "default_measurement": 'asr',
        "price": '99.00',
        "measurements": {
            'asr': {
                "origin": 'ASR',
                "format": 'csv_freq_spl',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/1more-sonoflow-nc-headphone-review.42849/',
                'review_published': '20230311',
                'recommendation': 'Yes',
                "sensitivity_mV_94dB": 0.0,
            },
        },
    },
}
