# -*- coding: utf-8 -*-
from . import SpeakerDatabase, gll_data_acquisition_std

speakers_info_f: SpeakerDatabase = {
    "FBT J5A": {
        "brand": "FBT",
        "model": "J5A",
        "type": "active",
        "price": "600",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-FBT",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221028",
            },
        },
    },
    "FBT J8A": {
        "brand": "FBT",
        "model": "J8A",
        "type": "active",
        "price": "800",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-FBT",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221028",
            },
        },
    },
    "FBT J12A": {
        "brand": "FBT",
        "model": "J12A",
        "type": "active",
        "price": "900",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-FBT",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221028",
            },
        },
    },
    "FBT J15A": {
        "brand": "FBT",
        "model": "J15A",
        "type": "active",
        "price": "1060",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-FBT",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221028",
            },
        },
    },
    "FBT Mitus 112A": {
        "brand": "FBT",
        "model": "Mitus 112A",
        "type": "active",
        "price": "3000",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-80x50",
        "measurements": {
            "vendor-pattern-80x50": {
                "origin": "Vendors-FBT",
                "data_acquisition": gll_data_acquisition_std,
                "format": "gll_hv_txt",
                "quality": "medium",
                "review_published": "20221028",
            },
        },
    },
    "FBT Mitus 115A": {
        "brand": "FBT",
        "model": "Mitus 115A",
        "type": "active",
        "price": "3400",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-80x50",
        "measurements": {
            "vendor-pattern-80x50": {
                "origin": "Vendors-FBT",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221028",
            },
        },
    },
    "FBT Mitus 152A": {
        "brand": "FBT",
        "model": "Mitus 152A",
        "type": "active",
        "price": "3900",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-60x40",
        "measurements": {
            "vendor-pattern-60x40": {
                "origin": "Vendors-FBT",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221028",
            },
        },
    },
    "FBT Mitus 215A": {
        "brand": "FBT",
        "model": "Mitus 215A",
        "type": "active",
        "price": "4800",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-60x40",
        "measurements": {
            "vendor-pattern-60x40": {
                "origin": "Vendors-FBT",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221028",
            },
        },
    },
    "FBT Promaxx 110A": {
        "brand": "FBT",
        "model": "Promaxx 110A",
        "type": "active",
        "price": "1200",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-FBT",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221028",
            },
        },
    },
    "FBT Promaxx 112A": {
        "brand": "FBT",
        "model": "Promaxx 112A",
        "type": "active",
        "price": "1150",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-FBT",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221028",
            },
        },
    },
    "FBT Promaxx 114A": {
        "brand": "FBT",
        "model": "Promaxx 114A",
        "type": "active",
        "price": "1950",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-FBT",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221028",
            },
        },
    },
    "FBT Vertus CS1000": {
        "brand": "FBT",
        "model": "Vertus CS1000",
        "type": "active",
        "price": "2600",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-110x30",
        "measurements": {
            "vendor-pattern-110x30": {
                "origin": "Vendors-FBT",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221028",
                "parameters": {
                    "mean_min": 50,
                    "mean_max": 500,
                },
            },
        },
    },
    "Fiio SP3": {
        "brand": "Fiio",
        "model": "SP3",
        "type": "active",
        "price": "350",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/fiio_sp3/",
                "review_published": "20231009",
            },
        },
    },
    "Fisher STE-720": {
        "brand": "Fisher",
        "model": "STE-720",
        "type": "passive",
        "price": "",
        "shape": "bookshelves",
        "default_measurement": "princeton",
        "measurements": {
            "princeton": {
                "origin": "Princeton",
                "format": "princeton",
                "symmetry": "horizontal",
                "review": "https://www.princeton.edu/3D3A/Directivity.html",
                "review_published": "20151001",
            },
        },
    },
    "Fluance Ai60": {
        "brand": "Fluance",
        "model": "Ai60",
        "type": "active",
        "price": "300",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-napilopez",
        "measurements": {
            "misc-napilopez": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/fluance-ai60-low-measurements-and-spinorama.12027/",
                },
            },
        },
    },
    "Fluance HFS Signature": {
        "brand": "Fluance",
        "model": "HFS Signature",
        "type": "passive",
        "price": "170",
        "shape": "bookshelves",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/fluance-signature-bookshelf-speaker-review.16337/",
            },
        },
    },
    "Fluance Reference XL8S": {
        "brand": "Fluance",
        "model": "Reference XL8S",
        "type": "passive",
        "price": "",
        "shape": "bookshelves",
        "default_measurement": "misc-archimago",
        "measurements": {
            "misc-archimago": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "review": "https://archimago.blogspot.com/2020/11/measurements-fluance-reference-xl8s.html",
                "quality": "low",
            },
        },
    },
    "Fluid Audio Image 2": {
        "brand": "Fluid Audio",
        "model": "Image 2",
        "type": "active",
        "price": "3800",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/fluid_image2/",
                },
                "review_published": "20231106",
                "specifications": {
                    "SPL": {
                        "max": 113,
                    },
                    "size": {
                        "height": 351,
                        "width": 241,
                        "depth": 363,
                    },
                    "weight": 12.6,
                },
            },
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/fluid-audio-image-2-review-monitor-speaker.34616/",
                "review_published": "20220604",
            },
        },
    },
    "Fluid Audio FX50": {
        "brand": "Fluid Audio",
        "model": "FX50",
        "type": "active",
        "price": "300",
        "shape": "bookshelves",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/fluid-audio-fx50-review-active-speaker.19881/",
                "review_published": "20210128",
            },
        },
    },
    "Fluid Audio FX50v2": {
        "brand": "Fluid Audio",
        "model": "FX50v2",
        "type": "active",
        "price": "300",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/fluid-audio-fx50v2-monitor-review.57541/",
                    "pre": "https://www.production-expert.com/production-expert-1/fluid-audio-fx50-1",
                },
                "review_published": "20241009",
                "specifications": {
                    "SPL": {
                        "peak": 110,
                    },
                    "size": {
                        "height": 234,
                        "width": 176,
                        "depth": 230,
                    },
                    "weight": 3.8,
                },
            },
        },
    },
    "Focal 1000 IWLCR6": {
        "brand": "Focal",
        "model": "1000 IWLCR6",
        "type": "passive",
        "price": "2700",
        "amount": "each",
        "shape": "inwall",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/focal_1000_iwlcr6/",
                "review_published": "20220514",
            },
        },
    },
    "Focal Alpha 50 Evo": {
        "brand": "Focal",
        "model": "Alpha 50 Evo",
        "type": "active",
        "price": "700",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-nuyes",
        "measurements": {
            "misc-nuyes": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "reviews": {
                    "dci": "https://gall.dcinside.com/mgallery/board/view/?id=speakers&no=195953",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/focal-alpha-evo-line-new-speakers.21773/post-902825",
                },
                "review_published": "20210906",
            },
        },
    },
    "Focal Alpha 65 Evo": {
        "brand": "Focal",
        "model": "Alpha 65 Evo",
        "type": "active",
        "price": "900",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/focal-alpha-65-evo-review-studio-monitor.28832/",
                    "sar": "https://www.soundandrecording.de/equipment/focal-alpha-65-evo-im-test/",
                },
                "review_published": "20211208",
            },
        },
    },
    "Focal Alpha Twin Evo": {
        "brand": "Focal",
        "model": "Alpha Twin Evo",
        "type": "active",
        "price": "480",
        "amount": "each",
        "shape": "bookshelves",
        "default_measurement": "misc-sr",
        "measurements": {
            "misc-sr": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://www.soundandrecording.de/equipment/focal-alpha-twin-evo-2-1-2-wege-nearfield-monitor-im-test/",
                "review_published": "20220812",
            },
        },
    },
    "Focal Aria 906": {
        "brand": "Focal",
        "model": "Aria 906",
        "type": "passive",
        "price": "450",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/focal_aria_906/",
                    "yt": "https://youtu.be/XHdutNbcXG0",
                },
                "review_published": "20230618",
            },
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/focal-aria-906-speaker-review.14085/",
                "review_published": "20200614",
            },
        },
    },
    "Focal Chora 806": {
        "brand": "Focal",
        "model": "Chora 806",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-napilopez",
        "measurements": {
            "misc-napilopez": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/new-focal-chora-806-on-and-off-axis-measurements.9613/page-2#post-360116",
                    "tnw": "https://thenextweb.com/news/review-focals-chora-806-is-a-luxury-speaker-at-a-heck-of-a-price",
                },
            },
        },
    },
    "Focal Chora 816": {
        "brand": "Focal",
        "model": "Chora 816",
        "type": "passive",
        "price": "900",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/focal-chora-816-speaker-review.42988/",
                },
                "review_published": "20230316",
            },
        },
    },
    "Focal Chorus OD 706 V": {
        "brand": "Focal",
        "model": "Chorus OD 706 V",
        "type": "passive",
        "price": "600",
        "shape": "outdoor",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/focal-chorus-od-706-v-outdoor-speaker-review.16561/",
                "review_published": "20201008",
            },
        },
    },
    "Focal Dome Flax": {
        "brand": "Focal",
        "model": "Dome Flax",
        "type": "passive",
        "price": "400",
        "shape": "bookshelves",
        "amount": "each",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/focal-dome-flax-speaker-review.47510/",
                "review_published": "20230830",
            },
        },
    },
    "Focal Twin6 Be": {
        "brand": "Focal",
        "model": "Twin6 Be",
        "type": "passive",
        "price": "1700",
        "shape": "center",
        "amount": "each",
        "default_measurement": "eac-horizontal",
        "measurements": {
            "eac-horizontal": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/focal_twin6be/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/focal-twin6-be-studio-monitor-review.22254/",
                    "sos": "https://www.soundonsound.com/reviews/focal-twin-6",
                },
                "review_published": "20210407",
            },
            "eac-vertical": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/focal_twin6be/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/focal-twin6-be-studio-monitor-review.22254/",
                    "sos": "https://www.soundonsound.com/reviews/focal-twin-6",
                },
                "review_published": "20210407",
            },
        },
    },
    "Focal Solo6 Be": {
        "brand": "Focal",
        "model": "Solo6 Be",
        "type": "active",
        "price": "1800",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/focal-solo6-be-review-studio-monitor.25407/",
                "review_published": "20210801",
            },
            "misc-napilopez": {
                "origin": "Misc",
                "format": "rew_text_dump",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/focal-solo6-be-spinorama-and-measurements.23499/#post-785638",
                "quality": "low",
                "review_published": "20210517",
            },
        },
    },
    "Focal Solo6 ST6": {
        "brand": "Focal",
        "model": "Solo6 ST6",
        "type": "active",
        "price": "2400",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/focal-solo6-st6-monitor-review.45784/",
                "review_published": "20230621",
                "specifications": {
                    "SPL": {
                        "peak": 110,
                    },
                    "size": {
                        "height": 334,
                        "width": 246,
                        "depth": 295,
                    },
                    "weight": 13.0,
                },
            },
        },
    },
    "Focal Sopra 1": {
        "brand": "Focal",
        "model": "Sopra 1",
        "type": "passive",
        "price": "10000",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "misc-audioholics",
        "measurements": {
            "misc-audioholics": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "review": "https://www.audioholics.com/bookshelf-speaker-reviews/focal-sopra-nb01/focal-sopra-nb01-conclusion",
                "quality": "low",
                "review_published": "20210609",
            },
        },
    },
    "Focal Trio6 ST6": {
        "brand": "Focal",
        "model": "Trio6 ST6",
        "type": "active",
        "price": "2900",
        "shape": "bookshelves",
        "amount": "each",
        "default_measurement": "misc-sr",
        "measurements": {
            "misc-sr": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "medium",
                "reviews": {
                    "snr": "https://www.soundandrecording.de/equipment/focal-trio6-midfield-monitor-im-test/",
                },
                "review_published": "20240612",
                "specifications": {
                    "SPL": {
                        "peak": 115,
                    },
                    "size": {
                        "height": 537,
                        "width": 292,
                        "depth": 369,
                    },
                    "weight": 25,
                },
            },
        },
    },
    "Fostex PM03": {
        "brand": "Fostex",
        "model": "PM03",
        "type": "active",
        "price": "150",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/fostex-pm-03-active-speaker-review.12517/",
                "review_published": "20200411",
            },
        },
    },
    "Fulcrum Acoustic CCX826": {
        "brand": "Fulcrum Acoustic",
        "model": "CCX826",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Fulcrum Acoustic",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20231115",
                "notes": "Relatively high smoothing; Pattern is 120x60",
            },
        },
    },
    "Fulcrum Acoustic CX826": {
        "brand": "Fulcrum Acoustic",
        "model": "CX826",
        "type": "active",
        "price": "",
        "amount": "each",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Fulcrum Acoustic",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20231116",
                "notes": "Relatively high smoothing; Pattern is 120x60",
                "specifications": {
                    "dispersion": {
                        "horizontal": 120,
                        "vertical": 60,
                    },
                    # equalized
                    "sensitivity": 102,
                    # equalized
                    "SPL": {
                        "continuous": 126,
                        "peak": 132,
                    },
                    "size": {
                        "height": 297,
                        "width": 362,
                        "depth": 298,
                    },
                    "weight": 7.7,
                },
            },
        },
    },
    "Fulcrum Acoustic CCX1500": {
        "brand": "Fulcrum Acoustic",
        "model": "CCX1500",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Fulcrum Acoustic",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20220924",
                "quality": "medium",
                "notes": "Relatively high smoothing; Pattern is 100x100",
            },
        },
    },
    "Fulcrum Acoustic CCX1526": {
        "brand": "Fulcrum Acoustic",
        "model": "CCX1526",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Fulcrum Acoustic",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20220924",
                "quality": "medium",
                "notes": "Relatively high smoothing; Pattern is 120x60",
            },
        },
    },
    "Fulcrum Acoustic CCX1565": {
        "brand": "Fulcrum Acoustic",
        "model": "CCX1565",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Fulcrum Acoustic",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20220924",
                "quality": "medium",
                "notes": "Relatively high smoothing; Pattern is 60x45",
            },
        },
    },
    "Fulcrum Acoustic CCX1577": {
        "brand": "Fulcrum Acoustic",
        "model": "CCX1577",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Fulcrum Acoustic",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20220924",
                "quality": "medium",
                "notes": "Relatively high smoothing; Pattern is 75x75",
            },
        },
    },
    "Fulcrum Acoustic CCX1595": {
        "brand": "Fulcrum Acoustic",
        "model": "CCX1595",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Fulcrum Acoustic",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20220924",
                "quality": "medium",
                "notes": "Relatively high smoothing; Pattern is 90x45",
            },
        },
    },
    "Fulcrum Acoustic DX1226": {
        "brand": "Fulcrum Acoustic",
        "model": "DX1226",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Fulcrum Acoustic",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20231117",
                "notes": "Relatively high smoothing; Pattern is 120x60",
                "specifications": {
                    "dispersion": {
                        "horizontal": 120,
                        "vertical": 60,
                    },
                    "sensitivity": 98,
                    "impedance": 8,
                    "SPL": {
                        "continuous": 126,
                        "peak": 132,
                    },
                    "size": {
                        "height": 711,
                        "width": 457,
                        "depth": 406,
                    },
                    "weight": 28.6,
                },
            },
        },
    },
    "Fulcrum Acoustic DX1526": {
        "brand": "Fulcrum Acoustic",
        "model": "DX1526",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Fulcrum Acoustic",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20220924",
                "notes": "Relatively high smoothing; Pattern is 120x60",
            },
        },
    },
    "Fulcrum Acoustic FH1565": {
        "brand": "Fulcrum Acoustic",
        "model": "FH1565",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Fulcrum Acoustic",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20220924",
                "notes": "Relatively high smoothing; Pattern is 60x45",
            },
        },
    },
    "Fulcrum Acoustic GX1200": {
        "brand": "Fulcrum Acoustic",
        "model": "GX1200",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Fulcrum Acoustic",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20220924",
                "notes": "Relatively high smoothing; Pattern is 100x100",
            },
        },
    },
    "Fulcrum Acoustic GX1526": {
        "brand": "Fulcrum Acoustic",
        "model": "GX1526",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Fulcrum Acoustic",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20220924",
                "notes": "Relatively high smoothing; Pattern is 120x60",
            },
        },
    },
    "Fulcrum Acoustic P8": {
        "brand": "Fulcrum Acoustic",
        "model": "P8",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Fulcrum Acoustic",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20231117",
                "specifications": {
                    "dispersion": {
                        "horizontal": 100,
                        "vertical": 100,
                    },
                    "sensitivity": 101,
                    "impedance": 16,
                    "SPL": {
                        "continuous": 119,
                        "peak": 125,
                    },
                    "size": {
                        "height": 313,
                        "width": 313,
                        "depth": 263,
                    },
                    "weight": 7.3,
                },
            },
        },
    },
    "Fulcrum Acoustic RX4": {
        "brand": "Fulcrum Acoustic",
        "model": "RX4",
        "type": "active",
        "price": "",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Fulcrum Acoustic",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20240825",
                "extras": {
                    "is_equed": True,
                },
                "specifications": {
                    "dispersion": {
                        "horizontal": 100,
                        "vertical": 100,
                    },
                    # equalized
                    "sensitivity": 85,
                    # equalized
                    "SPL": {
                        "continuous": 105,
                        "peak": 111,
                    },
                    "size": {
                        "height": 127,
                        "width": 135,
                        "depth": 132,
                    },
                    "weight": 1.4,
                },
            },
        },
    },
    "Fulcrum Acoustic RX5": {
        "brand": "Fulcrum Acoustic",
        "model": "RX5",
        "type": "active",
        "price": "",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Fulcrum Acoustic",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20240825",
                "extras": {
                    "is_equed": True,
                },
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 75,
                    },
                    # equalized
                    "sensitivity": 89,
                    # equalized
                    "SPL": {
                        "continuous": 111,
                        "peak": 117,
                    },
                    "size": {
                        "height": 152,
                        "width": 220,
                        "depth": 151,
                    },
                    "weight": 4.1,
                },
            },
        },
    },
    "Fulcrum Acoustic RX6": {
        "brand": "Fulcrum Acoustic",
        "model": "RX6",
        "type": "active",
        "price": "",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Fulcrum Acoustic",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20240825",
                "extras": {
                    "is_equed": True,
                },
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 75,
                    },
                    # equalized
                    "sensitivity": 90,
                    # equalized
                    "SPL": {
                        "continuous": 112,
                        "peak": 118,
                    },
                    "size": {
                        "height": 184,
                        "width": 273,
                        "depth": 154,
                    },
                    "weight": 4.9,
                },
            },
        },
    },
    "Fulcrum Acoustic RX8": {
        "brand": "Fulcrum Acoustic",
        "model": "RX8",
        "type": "active",
        "price": "",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Fulcrum Acoustic",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20240825",
                "extras": {
                    "is_equed": True,
                },
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 75,
                    },
                    # equalized
                    "sensitivity": 93,
                    # equalized
                    "SPL": {
                        "continuous": 116,
                        "peak": 122,
                    },
                    "size": {
                        "height": 229,
                        "width": 323,
                        "depth": 235,
                    },
                    "weight": 6.4,
                },
            },
        },
    },
    "Fulcrum Acoustic RX599": {
        "brand": "Fulcrum Acoustic",
        "model": "RX599",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Fulcrum Acoustic",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20230424",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 90,
                    },
                    # equalized
                    "sensitivity": 85,
                    "impedance": 16,
                    # equalized
                    "SPL": {
                        "continuous": 107,
                        "peak": 113,
                    },
                    "size": {
                        "height": 220,
                        "width": 142,
                        "depth": 152,
                    },
                    "weight": 3.9,
                },
            },
        },
    },
    "Fulcrum Acoustic RX699": {
        "brand": "Fulcrum Acoustic",
        "model": "RX699",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Fulcrum Acoustic",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20230424",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 90,
                    },
                    # equalized
                    "sensitivity": 89,
                    "impedance": 16,
                    # equalized
                    "SPL": {
                        "continuous": 112,
                        "peak": 118,
                    },
                    "size": {
                        "height": 273,
                        "width": 165,
                        "depth": 163,
                    },
                    "weight": 5.4,
                },
            },
        },
    },
}
