# -*- coding: utf-8 -*-
from . import SpeakerDatabase, gll_data_acquisition_std

note_jbl_gll = "Data provided by JBL in GLL format is highly variable, beware. It ranges from excellent to surprising"


speakers_info_j: SpeakerDatabase = {
    "Jamo C93 II": {
        "brand": "Jamo",
        "model": "C93 II",
        "type": "passive",
        "price": "300",
        "shape": "bookshelves",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jamo_c93_ii/",
                },
                "review_published": "20220809",
            },
        },
    },
    "Jamo Concert 8": {
        "brand": "Jamo",
        "model": "Concert 8",
        "type": "passive",
        "shape": "bookshelves",
        "price": "2500",
        "amount": "pair",
        "default_measurement": "misc-ageve",
        "measurements": {
            "misc-ageve": {
                "origin": "Misc",
                "format": "spl_hv_txt",
                "quality": "low",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/jamo-concert-8-d830-spinorama-measurements-cta-2034.55557/",
                },
                "review_published": "20240707",
                "specifications": {
                    "sensitivity": 91,
                    "impedance": 4,
                    "size": {
                        "height": 380,
                        "width": 245,
                        "depth": 310,
                    },
                    "weight": 13.0,
                },
            },
        },
    },
    "Jamo S7-15B": {
        "brand": "Jamo",
        "model": "S7-15B",
        "type": "passive",
        "price": "350",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jamo_s7_15b",
                    "yt": "https://youtu.be/T0sqGFqLqDk",
                },
                "review_published": "20240331",
                "specifications": {
                    "sensitivity": 86.3,
                    "impedance": 4,
                    "size": {
                        "height": 320,
                        "width": 200,
                        "depth": 340,
                    },
                    "weight": 5.93,
                },
            },
        },
    },
    "Jamo S803": {
        "brand": "Jamo",
        "model": "S803",
        "type": "passive",
        "price": "150",
        "shape": "bookshelves",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jamo_s803/",
                },
                "review_published": "20220809",
            },
        },
    },
    "Jamo S807": {
        "brand": "Jamo",
        "model": "S807",
        "type": "passive",
        "price": "650",
        "shape": "floorstanders",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "webplotdigitizer",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jamo_s807/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/jamo-s807-floorstanding-speakers-review.14314/",
                },
                "review_published": "20200622",
            },
        },
    },
    "JansZen Loudspeaker zA1.1": {
        "brand": "JansZen Loudspeaker",
        "model": "zA1.1",
        "type": "passive",
        "price": "",
        "shape": "bookshelves",
        "default_measurement": "princeton",
        "measurements": {
            "princeton": {
                "origin": "Princeton",
                "format": "princeton",
                "symmetry": "horizontal",
                "review": "https://www.princeton.edu/3D3A/Directivity.html",
                "review_published": "20151001",
            },
        },
    },
    "JansZen Loudspeaker zA2.1": {
        "brand": "JansZen Loudspeaker",
        "model": "zA2.1",
        "type": "passive",
        "price": "",
        "shape": "floorstanders",
        "default_measurement": "princeton",
        "measurements": {
            "princeton": {
                "origin": "Princeton",
                "format": "princeton",
                "symmetry": "horizontal",
                "review": "https://www.princeton.edu/3D3A/Directivity.html",
                "review_published": "20151001",
            },
        },
    },
    "Jeff Bagby Mandolin DIY": {
        "brand": "Jeff Bagby",
        "model": "Mandolin DIY",
        "type": "passive",
        "price": "300",
        "shape": "bookshelves",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/bagby-mandolin-diy-speaker-review.22981/",
            },
        },
    },
    "JBL 3733": {
        "brand": "JBL",
        "model": "3733",
        "type": "passive",
        "price": "10000",
        "amount": "pair",
        "shape": "cinema",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20220915",
                "quality": "low",
                "notes": "{}".format(note_jbl_gll),
            },
        },
    },
    "JBL 9310": {
        "brand": "JBL",
        "model": "9310",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "cinema",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20220915",
                "quality": "low",
                "notes": "{}".format(note_jbl_gll),
            },
        },
    },
    "JBL COL600": {
        "brand": "JBL",
        "model": "COL600",
        "type": "passive",
        "price": "300",
        "amount": "each",
        "shape": "columns",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "low",
                "review_published": "20231020",
                "specifications": {
                    "dispersion": {
                        "horizontal": 160,
                        "vertical": 70,
                    },
                    "SPL": {
                        "max": 105,
                        "peak": 111,
                    },
                    "sensitivity": 86,
                    "impedance": 8,
                    "size": {
                        "height": 598,
                        "width": 102,
                        "depth": 93,
                    },
                    "weight": 3.7,
                },
            },
        },
    },
    "JBL COL800": {
        "brand": "JBL",
        "model": "COL800",
        "type": "passive",
        "price": "500",
        "amount": "each",
        "shape": "columns",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "low",
                "review_published": "20231020",
                "specifications": {
                    "dispersion": {
                        "horizontal": 160,
                        "vertical": 60,
                    },
                    "SPL": {
                        "max": 110,
                        "peak": 116,
                    },
                    "sensitivity": 88,
                    "impedance": 8,
                    "size": {
                        "height": 800,
                        "width": 102,
                        "depth": 93,
                    },
                    "weight": 5.2,
                },
            },
        },
    },
    "JBL CFR2": {
        "brand": "JBL",
        "model": "CFR2",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "cinema",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20220915",
                "quality": "low",
                "notes": "{}".format(note_jbl_gll),
            },
        },
    },
    "JBL Control 24CT": {
        "brand": "JBL",
        "model": "Control 24CT",
        "type": "passive",
        "price": "150",
        "amount": "each",
        "shape": "inwall",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20220915",
                "quality": "low",
                "notes": "{}".format(note_jbl_gll),
                "reviews": {
                    "jbl": "https://jblpro.com/products/control-24ct",
                },
            },
        },
    },
    "JBL Control 25T": {
        "brand": "JBL",
        "model": "Control 25T",
        "type": "passive",
        "price": "350",
        "amount": "pair",
        "shape": "outdoor",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20220915",
                "quality": "low",
                "notes": "{}".format(note_jbl_gll),
            },
        },
    },
    "JBL Control HST V2": {
        "skip": True,  # quality is very low
        "brand": "JBL",
        "model": "Control HST V2",
        "type": "passive",
        "price": "400",
        "amount": "each",
        "shape": "bookshelves",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20220915",
                "quality": "low",
                "notes": "{}".format(note_jbl_gll),
            },
        },
    },
    "JBL CV3015": {
        "brand": "JBL",
        "model": "CV3015",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-90x90",
        "measurements": {
            "vendor-pattern-90x90": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20241105",
                "quality": "medium",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 90,
                    },
                    "sensitivity": 99,
                    "impedance": 8,
                    "SPL": {
                        "max": 125,
                        "peak": 131,
                    },
                    "size": {
                        "height": 680,
                        "width": 414,
                        "depth": 445,
                    },
                    "weight": 23.15,
                },
            },
        },
    },
    "JBL CV5012": {
        "brand": "JBL",
        "model": "CV5012",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-60x40",
        "measurements": {
            "vendor-pattern-60x40": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20230223",
                "quality": "medium",
                "notes": "This is an installation speaker that you can use indoor or outdoor.",
                "specifications": {
                    "dispersion": {
                        "horizontal": 60,
                        "vertical": 40,
                    },
                    "sensitivity": 98,
                    "impedance": 8,
                    "SPL": {
                        "peak": 132,
                    },
                    "size": {
                        "height": 630,
                        "width": 394,
                        "depth": 429,
                    },
                    "weight": 25.0,
                },
            },
        },
    },
    "JBL CV5015": {
        "brand": "JBL",
        "model": "CV5015",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20230223",
                "quality": "medium",
                "notes": "This is an installation speaker that you can use indoor or outdoor.",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 60,
                    },
                    "sensitivity": 100,
                    "impedance": 8,
                    "SPL": {
                        "peak": 135,
                    },
                    "size": {
                        "height": 700,
                        "width": 431,
                        "depth": 520,
                    },
                    "weight": 33.0,
                },
            },
            "vendor-pattern-60x40": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20230223",
                "quality": "medium",
                "notes": "This is an installation speaker that you can use indoor or outdoor.",
                "specifications": {
                    "dispersion": {
                        "horizontal": 60,
                        "vertical": 40,
                    },
                    "sensitivity": 100,
                    "impedance": 8,
                    "SPL": {
                        "peak": 135,
                    },
                    "size": {
                        "height": 700,
                        "width": 431,
                        "depth": 520,
                    },
                    "weight": 33.0,
                },
            },
        },
    },
    "JBL AC25": {
        "brand": "JBL",
        "model": "AC25",
        "type": "passive",
        "price": "1000",
        "amount": "each",
        "shape": "bookshelves",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-ac25-speaker-review.43520/",
                "review_published": "20230403",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 90,
                    },
                    "sensitivity": 91,
                    "impedance": 16,
                    "SPL": {
                        "peak": 115,
                    },
                    "size": {
                        "height": 377,
                        "width": 150,
                        "depth": 178,
                    },
                    "weight": 7.5,
                },
            },
        },
    },
    "JBL Arena 120": {
        "brand": "JBL",
        "model": "Arena 120",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-speakerdata2034",
        "measurements": {
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://speakerdata2034.blogspot.com/2019/06/harman-consumer-brands-spinorama-data.html",
            },
        },
    },
    "JBL L52 Classic": {
        "brand": "JBL",
        "model": "L52 Classic",
        "type": "passive",
        "price": "1000",
        "amount": "each",
        "shape": "bookshelves",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jbl_l52_classic/",
                    "yt": "https://youtu.be/wG9iIMId0ew",
                },
                "review_published": "20240312",
                "specifications": {
                    "sensitivity": 85,
                    "impedance": 4,
                    "size": {
                        "height": 330,
                        "width": 197,
                        "depth": 216,
                    },
                    "weight": 5,
                },
            },
        },
    },
    "JBL LSR308": {
        "brand": "JBL",
        "model": "LSR308",
        "type": "active",
        "price": "",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://speakerdata2034.blogspot.com/2019/03/spinorama-data-jbl-pro-studio.html",
            },
        },
    },
    "JBL LSR305": {
        "brand": "JBL",
        "model": "LSR305",
        "type": "active",
        "price": "",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-dominikz",
        "measurements": {
            "misc-dominikz": {
                "origin": "Misc",
                "format": "rew_text_dump",
                "quality": "low",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-lsr305-1st-gen-quasi-anechoic-measurements.24545/#post-828147",
                "review_published": "20210626",
            },
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://speakerdata2034.blogspot.com/2019/03/spinorama-data-jbl-pro-studio.html",
            },
        },
    },
    "JBL LSR6328P": {
        "brand": "JBL",
        "model": "LSR6328P",
        "type": "active",
        "price": "",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-speakerdata2034",
        "measurements": {
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://speakerdata2034.blogspot.com/2019/03/spinorama-data-jbl-pro-studio.html",
            },
        },
    },
    "JBL SLP12": {
        "brand": "JBL",
        "model": "SLP12",
        "type": "passive",
        "price": "200",
        "amount": "each",
        "shape": "surround",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20230223",
                "quality": "low",
                "notes": "This is a speaker designed to be mounted on a wall.",
                "specifications": {
                    "sensitivity": 84,
                    "impedance": 8,
                    "SPL": {
                        "continuous": 100,
                        "peak": 106,
                    },
                    "size": {
                        "height": 248,
                        "width": 230,
                        "depth": 100,
                    },
                    "weight": 1.9,
                },
            },
        },
    },
    "JBL SLP14": {
        "brand": "JBL",
        "model": "SLP14",
        "type": "passive",
        "price": "280",
        "amount": "each",
        "shape": "surround",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20230223",
                "quality": "low",
                "notes": "This is a speaker designed to be mounted on a wall.",
                "specifications": {
                    "dispersion": {
                        "horizontal": 140,
                        "vertical": 120,
                    },
                    "sensitivity": 85,
                    "impedance": 8,
                    "SPL": {
                        "continuous": 102,
                        "peak": 108,
                    },
                    "size": {
                        "height": 286,
                        "width": 263,
                        "depth": 100,
                    },
                    "weight": 2.8,
                },
            },
        },
    },
    "JBL SRX835P": {
        "brand": "JBL",
        "model": "SRX835P",
        "type": "active",
        "price": "3400",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-srx835p-reviewed-powered-monitor.25300/",
                "review_published": "20210727",
            },
        },
    },
    "JBL Synthesis Array 800": {
        "brand": "JBL",
        "model": "Synthesis Array 800",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "cinema",
        "default_measurement": "misc-speakerdata2034",
        "measurements": {
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://speakerdata2034.blogspot.com/2021/01/jbl-synthesis-spinorama-data.html",
                "review_published": "20050429",
            },
        },
    },
    "JBL Synthesis Array 880": {
        "brand": "JBL",
        "model": "Synthesis Array 880",
        "type": "passive",
        "price": "1600",
        "amount": "each",
        "shape": "center",
        "default_measurement": "asr-vertical",
        "measurements": {
            "asr-vertical": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-array-880-review-center-speaker.27911/",
                "review_published": "20211107",
            },
            "asr-horizontal": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-array-880-review-center-speaker.27911/",
                "review_published": "20211107",
            },
        },
    },
    "JBL Synthesis Array 1400": {
        "brand": "JBL",
        "model": "Synthesis Array 1400",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "cinema",
        "default_measurement": "misc-speakerdata2034",
        "measurements": {
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "reviews": {
                    "audioheritage": "http://www.audioheritage.org/vbulletin/showthread.php?10643-1400-Array&s=a38c6357aa9b2c8497c31c062c59c858&p=121867&viewfull=1#post121867",
                    "stereophile": "https://www.stereophile.com/floorloudspeakers/jbl_synthesis_1400_array_bg_loudspeaker/index.html",
                },
                "review_published": "20060826",
            },
        },
    },
    "JBL Synthesis SCL-1": {
        "brand": "JBL",
        "model": "Synthesis SCL-1",
        "type": "passive",
        "price": "15000",
        "amount": "each",
        "shape": "inwall",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "webplotdigitizer",
                "reviews": {
                    "avs": "https://www.avsforum.com/threads/official-jbl-synthesis-pro-revel-home-theater-thread.2515137/",
                },
                "review_published": "20221218",
                "specifications": {
                    "dispersion": {
                        "horizontal": 120,
                        "vertical": 100,
                    },
                    "sensitivity": 94,
                    "impedance": 4,
                    "SPL": {
                        "peak": 133,
                    },
                    "size": {
                        "height": 1218,
                        "width": 482,
                        "depth": 368,
                    },
                    "weight": 80.5,
                },
            },
        },
    },
    "JBL Synthesis SCL-3": {
        "brand": "JBL",
        "model": "Synthesis SCL-3",
        "type": "passive",
        "price": "3300",
        "amount": "each",
        "shape": "inwall",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "webplotdigitizer",
                "reviews": {
                    "avs": "https://www.avsforum.com/threads/official-jbl-synthesis-pro-revel-home-theater-thread.2515137/",
                },
                "review_published": "20221218",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 60,
                    },
                    "sensitivity": 91,
                    "impedance": 6,
                    "size": {
                        "height": 418,
                        "width": 418,
                        "depth": 153,
                    },
                    "weight": 11.2,
                },
            },
        },
    },
    "JBL Synthesis SCL-4": {
        "brand": "JBL",
        "model": "Synthesis SCL-4",
        "type": "passive",
        "price": "3990",
        "amount": "each",
        "shape": "inwall",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "webplotdigitizer",
                "reviews": {
                    "avs": "https://www.avsforum.com/threads/official-jbl-synthesis-pro-revel-home-theater-thread.2515137/",
                },
                "review_published": "20221218",
                "specifications": {
                    "dispersion": {
                        "horizontal": 100,
                        "vertical": 100,
                    },
                    "sensitivity": 91,
                    "impedance": 6,
                    "size": {
                        "height": 636,
                        "width": 409,
                        "depth": 93,
                    },
                    "weight": 12.51,
                },
            },
        },
    },
    "JBL Synthesis SCL-5": {
        "brand": "JBL",
        "model": "Synthesis SCL-5",
        "type": "passive",
        "price": "2200",
        "amount": "each",
        "shape": "inwall",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-scl-5-in-ceiling-speaker-review.41763/",
                "review_published": "20230209",
                "specifications": {
                    "dispersion": {
                        "horizontal": 120,
                        "vertical": 60,
                    },
                    "sensitivity": 86,
                    "impedance": 6,
                    "size": {
                        "height": 318,
                        "width": 318,
                        "depth": 152,
                    },
                    "weight": 3.9,
                },
            },
        },
    },
    "JBL Synthesis SCL-6": {
        "brand": "JBL",
        "model": "Synthesis SCL-6",
        "type": "passive",
        "price": "1650",
        "amount": "each",
        "shape": "inwall",
        "default_measurement": "eac-v1-farfield-without-grille",
        "measurements": {
            "eac-v1-farfield-without-grille": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jbl_scl-6/",
                    "yt": "https://www.youtube.com/watch?v=nZAokQVOFlo",
                },
                "review_published": "20220319",
                "notes": "Measured far field without grille",
                "specifications": {
                    "dispersion": {
                        "horizontal": 80,
                        "vertical": 80,
                    },
                    "sensitivity": 91,
                    "impedance": 4,
                    "size": {
                        "height": 185,
                        "width": 796,
                        "depth": 97,
                    },
                    "weight": 11.61,
                },
            },
            "eac-v2-farfield-with-grille": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jbl_scl-6/",
                    "yt": "https://www.youtube.com/watch?v=nZAokQVOFlo",
                },
                "review_published": "20220319",
                "notes": "Measured far field with grille",
            },
            "eac-v3-nearfield-without-grille": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jbl_scl-6/",
                    "yt": "https://www.youtube.com/watch?v=nZAokQVOFlo",
                },
                "review_published": "20220319",
                "notes": "Measured near field without grille",
            },
        },
    },
    "JBL Synthesis SCL-7": {
        "brand": "JBL",
        "model": "Synthesis SCL-7",
        "type": "passive",
        "price": "1100",
        "amount": "each",
        "shape": "inwall",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-scl-7-review-in-wall-speaker.32602/",
                },
                "review_published": "20220404",
                "notes": "Measured far field without grille",
                "specifications": {
                    "dispersion": {
                        "horizontal": 60,
                        "vertical": 90,
                    },
                    "sensitivity": 88,
                    "impedance": 4,
                    "size": {
                        "height": 186,
                        "width": 486,
                        "depth": 99,
                    },
                    "weight": 6.62,
                },
            },
        },
    },
    "JBL Synthesis 4429": {
        "brand": "JBL",
        "model": "Synthesis 4429",
        "type": "passive",
        "price": "6000",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-speakerdata2034",
        "measurements": {
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://speakerdata2034.blogspot.com/2021/01/jbl-synthesis-spinorama-data.html",
            },
        },
    },
    "JBL Synthesis K2 S5800": {
        "brand": "JBL",
        "model": "Synthesis K2 S5800",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "misc-speakerdata2034",
        "measurements": {
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://speakerdata2034.blogspot.com/2021/01/jbl-synthesis-spinorama-data.html",
            },
        },
    },
    "JBL Synthesis K2 S9800": {
        "brand": "JBL",
        "model": "Synthesis K2 S9800",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "misc-speakerdata2034",
        "measurements": {
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://speakerdata2034.blogspot.com/2021/01/jbl-synthesis-spinorama-data.html",
            },
        },
    },
    "JBL Synthesis K2 S9900": {
        "brand": "JBL",
        "model": "Synthesis K2 S9900",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-speakerdata2034",
        "measurements": {
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://speakerdata2034.blogspot.com/2021/01/jbl-synthesis-spinorama-data.html",
            },
        },
    },
    "JBL Synthesis SAM1HF + SAM2LF": {
        "brand": "JBL",
        "model": "Synthesis SAM1HF + SAM2LF",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-speakerdata2034",
        "measurements": {
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://speakerdata2034.blogspot.com/2021/01/jbl-synthesis-spinorama-data.html",
            },
        },
    },
    "JBL Synthesis SAM3HA": {
        "brand": "JBL",
        "model": "Synthesis SAM3HA",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "center",
        "default_measurement": "misc-speakerdata2034",
        "measurements": {
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://speakerdata2034.blogspot.com/2021/01/jbl-synthesis-spinorama-data.html",
            },
        },
    },
    "JBL Synthesis SK2-1000": {
        "brand": "JBL",
        "model": "Synthesis SK2-1000",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-speakerdata2034",
        "measurements": {
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://speakerdata2034.blogspot.com/2021/01/jbl-synthesis-spinorama-data.html",
            },
        },
    },
    "JBL Synthesis SK2-3300": {
        "brand": "JBL",
        "model": "Synthesis SK2-3300",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-speakerdata2034",
        "measurements": {
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://speakerdata2034.blogspot.com/2021/01/jbl-synthesis-spinorama-data.html",
            },
        },
    },
    "JBL Performance PC600": {
        "brand": "JBL",
        "model": "Performance PC600",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "center",
        "default_measurement": "misc-speakerdata2034",
        "measurements": {
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://speakerdata2034.blogspot.com/2019/06/harman-consumer-brands-spinorama-data.html",
            },
        },
    },
    "JBL C211": {
        "brand": "JBL",
        "model": "C211",
        "type": "passive",
        "price": "",
        "shape": "cinema",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20220918",
                "quality": "low",
                "notes": "{}".format(note_jbl_gll),
            },
        },
    },
    "JBL C222": {
        "brand": "JBL",
        "model": "C222",
        "type": "passive",
        "price": "",
        "shape": "cinema",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20220918",
                "quality": "low",
                "notes": "{}".format(note_jbl_gll),
            },
        },
    },
    "JBL Performance PT800": {
        "brand": "JBL",
        "model": "Performance PT800",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-speakerdata2034",
        "measurements": {
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://speakerdata2034.blogspot.com/2019/06/harman-consumer-brands-spinorama-data.html",
            },
        },
    },
    "JBL CBT 70J-1": {
        "brand": "JBL",
        "model": "CBT 70J-1",
        "type": "passive",
        "price": "1000",
        "shape": "cbt",
        "amount": "each",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-cbt-70j-1-review-constant-beam-transducer.21469/",
            },
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20220918",
                "quality": "low",
                "notes": "{}".format(note_jbl_gll),
            },
        },
    },
    "JBL CBT 1000": {
        "brand": "JBL",
        "model": "CBT 1000",
        "type": "passive",
        "price": "2600",
        "shape": "cbt",
        "amount": "each",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20231025",
                "quality": "low",
                "notes": "{}".format(note_jbl_gll),
                "specifications": {
                    "dispersion": {
                        "horizontal": 160,
                        "vertical": 60,
                    },
                    "sensitivity": 95,
                    "impedance": 4,
                    "SPL": {
                        "max": 127,
                        "peak": 130,
                        "pink_noise": 124,
                    },
                    "size": {
                        "height": 1020,
                        "width": 250,
                        "depth": 345,
                    },
                    "weight": 24.5,
                },
            },
        },
    },
    "JBL CBT 1000+1000E": {
        "brand": "JBL",
        "model": "CBT 1000+1000E",
        "type": "passive",
        "price": "5000",
        "shape": "cbt",
        "amount": "each",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20231027",
                "quality": "low",
                "notes": "{}".format(note_jbl_gll),
                "specifications": {
                    "dispersion": {
                        "horizontal": 160,
                        "vertical": 60,
                    },
                    "sensitivity": 102,
                    "impedance": 4,
                    "SPL": {
                        "max": 127,
                        "peak": 130,
                        "pink_noise": 124,
                    },
                    "size": {
                        "height": 2040,
                        "width": 250,
                        "depth": 345,
                    },
                    "weight": 47.2,
                },
            },
        },
    },
    "JBL Control 1 Pro": {
        "brand": "JBL",
        "model": "Control 1 Pro",
        "type": "passive",
        "price": "164",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-305p-mkii-and-control-1-pro-monitors-review.10811/",
                "review_published": "20200110",
            },
        },
    },
    "JBL Control 29AV-1": {
        "brand": "JBL",
        "model": "Control 29AV-1",
        "type": "passive",
        "price": "820",
        "shape": "outdoor",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-control-29av-1-review-pa-outdoor-speaker.26705/",
                "review_published": "20210918",
            },
        },
    },
    "JBL Control X": {
        "brand": "JBL",
        "model": "Control X",
        "type": "active",
        "price": "205",
        "shape": "outdoor",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-control-x-review-indoor-outdoor-speaker.24852/",
                "review_published": "20210710",
            },
        },
    },
    "JBL Control X Wireless": {
        "brand": "JBL",
        "model": "Control X Wireless",
        "type": "active",
        "price": "500",
        "shape": "outdoor",
        "amount": "pair",
        "default_measurement": "misc-matthews",
        "measurements": {
            "misc-matthews": {
                "origin": "Misc",
                "format": "spl_hv_txt",
                "quality": "medium",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-control-x-wireless-measurements-review.47175/",
                "review_published": "20230817",
            },
        },
    },
    "JBL SCS 8": {
        "brand": "JBL",
        "model": "SCS 8",
        "type": "passive",
        "price": "600",
        "shape": "surround",
        "amount": "each",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jbl_scs8/",
                },
                "review_published": "20231106",
                "specifications": {
                    "dispersion": {
                        "horizontal": 120,
                        "vertical": 120,
                    },
                    "sensitivity": 94,
                    "impedance": 8,
                    "SPL": {
                        "max": 118,
                    },
                    "size": {
                        "height": 300,
                        "width": 300,
                        "depth": 305,
                    },
                    "weight": 11.4,
                },
            },
        },
    },
    "JBL Stage A120": {
        "brand": "JBL",
        "model": "Stage A120",
        "type": "passive",
        "price": "200",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jbl_stage_a120/",
                },
                "review_published": "20211025",
            },
        },
    },
    "JBL Stage A125C": {
        "brand": "JBL",
        "model": "Stage A125C",
        "type": "passive",
        "price": "120",
        "shape": "center",
        "amount": "each",
        "default_measurement": "asr-vertical",
        "measurements": {
            "asr-vertical": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-stage-125c-review-center-speaker.28613/",
                "review_published": "20211201",
            },
            "asr-horizontal": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-stage-125c-review-center-speaker.28613/",
                "review_published": "20211201",
            },
        },
    },
    "JBL Stage A130": {
        "brand": "JBL",
        "model": "Stage A130",
        "type": "passive",
        "price": "200",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/jbl_stage_a130/",
                "review_published": "20211112",
            },
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-stage-a130-review-speaker.18260/",
                "review_published": "20201210",
            },
        },
    },
    "JBL Stage A135C": {
        "brand": "JBL",
        "model": "Stage A135C",
        "type": "passive",
        "price": "300",
        "shape": "center",
        "amount": "each",
        "default_measurement": "asr-vertical",
        "measurements": {
            "asr-vertical": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-stage-135c-review-center-speaker.28536/",
                "review_published": "20211129",
            },
            "asr-horizontal": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-stage-135c-review-center-speaker.28536/",
                "review_published": "20211129",
            },
        },
    },
    "JBL Stage A180": {
        "brand": "JBL",
        "model": "Stage A180",
        "type": "passive",
        "price": "400",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-a180-tower-speaker-review.34846/",
                "review_published": "20220610",
            },
        },
    },
    "JBL Stage 250B": {
        "brand": "JBL",
        "model": "Stage 250B",
        "type": "passive",
        "price": "400",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jbl_250b/",
                    "yt": "https://youtu.be/YcAgRBndf3c",
                },
                "review_published": "20240916",
                "specifications": {
                    "sensitivity": 86,
                    "impedance": 6,
                    "size": {
                        "height": 321,
                        "width": 200,
                        "depth": 241,
                    },
                    "weight": 5.6,
                },
            },
        },
    },
    "JBL Stage 280F": {
        "brand": "JBL",
        "model": "Stage 280F",
        "type": "passive",
        "price": "1200",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jbl_280f/",
                    "yt": "https://youtu.be/YcAgRBndf3c",
                },
                "review_published": "20240916",
                "specifications": {
                    "sensitivity": 91,
                    "impedance": 6,
                    "size": {
                        "height": 1113,
                        "width": 357,
                        "depth": 420,
                    },
                    "weight": 25.1,
                },
            },
        },
    },
    "JBL L100 Classic": {
        "brand": "JBL",
        "model": "L100 Classic",
        "type": "passive",
        "price": "",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "misc-audioholics",
        "measurements": {
            "misc-audioholics": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "review": "https://www.audioholics.com/bookshelf-speaker-reviews/jbl-l100/conclusion",
                "quality": "low",
            },
        },
    },
    "JBL L100 Classic MKII": {
        "brand": "JBL",
        "model": "L100 Classic MKII",
        "type": "passive",
        "price": "2799",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "yt": "https://youtu.be/ZBBqxHku5sA",
                },
                "review_published": "20250404",
                "specifications": {
                    "sensitivity": 90,
                    "impedance": 4,
                    "size": {
                        "height": 636,
                        "width": 399,
                        "depth": 371,
                    },
                    "weight": 26.7,
                },
            },
            "eac-maxed-out": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "yt": "https://youtu.be/ZBBqxHku5sA",
                },
                "review_published": "20250404",
            },
        },
    },
    "JBL 104": {
        "brand": "JBL",
        "model": "104",
        "type": "active",
        "price": "130",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-one-series-104-powered-monitor-review.11076/",
            },
            "misc-napilopez": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://thenextweb.com/news/these-3-studio-monitors-are-great-speakers-for-a-small-desk",
            },
        },
    },
    "JBL 705i": {
        "skip": True,
        "brand": "JBL",
        "model": "705i",
        "type": "passive",
        "price": "1500",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "webplotdigitizer",
                "review": "",
                "specifications": {
                    "SPL": {
                        "max": 101,
                        "peak": 107,
                    },
                    "size": {
                        "height": 267,
                        "width": 149,
                        "depth": 206,
                    },
                    "weight": 4.08,
                },
            },
        },
    },
    "JBL 705P": {
        "brand": "JBL",
        "model": "705P",
        "type": "active",
        "price": "2000",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-705p-studio-monitor-review.11944/",
                "review_published": "20200309",
                "specifications": {
                    "SPL": {
                        "max": 101,
                        "peak": 107,
                    },
                    "size": {
                        "height": 268,
                        "width": 151,
                        "depth": 274,
                    },
                    "weight": 5.68,
                },
            },
        },
    },
    "JBL 708i active": {
        "brand": "JBL",
        "model": "708i active",
        "type": "active",
        "price": "5400",  # with Crown DCI 4|300
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-708i-monitor-review-dsp-part-2.40650/",
                "review_published": "20230104",
                "specifications": {
                    "SPL": {
                        "max": 108,
                        "peak": 114,
                    },
                    "size": {
                        "height": 438,
                        "width": 248,
                        "depth": 292,
                    },
                    "weight": 11.5,
                },
                "notes": "IMPORTANT this is in active mode driven by a Crown DCI 4|300n and JBL's configuration!",
            },
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "webplotdigitizer",
                "quality": "high",
                "review": "https://speakerdata2034.blogspot.com/2019/03/spinorama-data-jbl-pro-studio.html",
            },
        },
    },
    "JBL 708i passive": {
        "brand": "JBL",
        "model": "708i passive",
        "type": "passive",
        "price": "3800",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-708i-monitor-review-passive-part-1.40530/",
                "review_published": "20221231",
                "specifications": {
                    "SPL": {
                        "max": 108,
                        "peak": 114,
                    },
                    "size": {
                        "height": 438,
                        "width": 248,
                        "depth": 292,
                    },
                    "weight": 11.5,
                },
                "notes": "IMPORTANT this is in passive mode and the speaker is not designed for this use case. Look at the same measurements which EQ please!",
            },
        },
    },
    "JBL 708P": {
        "brand": "JBL",
        "model": "708P",
        "type": "active",
        "price": "3600",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-708p-review-professional-monitor.20006/",
                "review_published": "20210201",
                "specifications": {
                    "SPL": {
                        "max": 108,
                        "peak": 114,
                    },
                    "size": {
                        "height": 441,
                        "width": 250,
                        "depth": 419,
                    },
                    "weight": 18.1,
                },
            },
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jbl_708p/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-professional-708p-bi-amplified-8-inch-master-reference-monitor.23655/",
                },
                "review_published": "20210523",
                "specifications": {
                    "SPL": {
                        "max": 108,
                        "peak": 114,
                    },
                    "size": {
                        "height": 441,
                        "width": 250,
                        "depth": 419,
                    },
                    "weight": 18.1,
                },
            },
        },
    },
    "JBL 305P Mark ii": {
        "brand": "JBL",
        "model": "305P Mark ii",
        "type": "active",
        "price": "300",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jbl_305pmk2/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-305p-mkii-review-erin.22999/",
                },
                "review_published": "20201001",
                "specifications": {
                    "dispersion": {
                        "horizontal": 120,
                        "vertical": 90,
                    },
                    "sensitivity": 92,
                    "SPL": {
                        "max": 94,
                        "peak": 108,
                    },
                    "size": {
                        "height": 298,
                        "width": 185,
                        "depth": 231,
                    },
                    "weight": 4.73,
                },
            },
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-305p-mkii-and-control-1-pro-monitors-review.10811/",
            },
        },
    },
    "JBL 306P Mark ii": {
        "brand": "JBL",
        "model": "306P Mark ii",
        "type": "active",
        "price": "150",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-306p-mk-ii-review-studio-monitor.18505/",
                "review_published": "20201217",
                "specifications": {
                    "dispersion": {
                        "horizontal": 120,
                        "vertical": 90,
                    },
                    "sensitivity": 92,
                    "SPL": {
                        "max": 92,
                        "peak": 110,
                    },
                    "size": {
                        "height": 361,
                        "width": 224,
                        "depth": 282,
                    },
                    "weight": 6.1,
                },
            },
        },
    },
    "JBL 308P Mark ii": {
        "brand": "JBL",
        "model": "308P Mark ii",
        "type": "active",
        "price": "500",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-308p-mkii-studio-monitor-review.17338/",
                "review_published": "20201106",
                "specifications": {
                    "dispersion": {
                        "horizontal": 120,
                        "vertical": 90,
                    },
                    "sensitivity": 92,
                    "SPL": {
                        "max": 102,
                        "peak": 112,
                    },
                    "size": {
                        "height": 419,
                        "width": 254,
                        "depth": 308,
                    },
                    "weight": 8.1,
                },
            },
        },
    },
    "JBL 4305P": {
        "brand": "JBL",
        "model": "4305P",
        "type": "active",
        "price": "2200",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jbl_4305p/",
                },
                "review_published": "20220506",
            },
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "webplotdigitizer",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-4305p.29623/",
                },
                "review_published": "20220104",
            },
        },
    },
    "JBL 4309": {
        "brand": "JBL",
        "model": "4309",
        "type": "passive",
        "price": "2000",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-4309-review-speaker.27255/",
                "review_published": "20211012",
            },
            "misc-napilopez": {
                "origin": "Misc",
                "format": "rew_text_dump",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-4309-spinorama-and-measurements.23465/#post-784844",
                "quality": "low",
                "review_published": "20210517",
            },
        },
    },
    "JBL 4312MII": {
        "brand": "JBL",
        "model": "4312MII",
        "type": "passive",
        "price": "1000",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-4312m-ii-3-way-studio-monitor-review.51226/",
                "review_published": "20240110",
                "specifications": {
                    "sensitivity": 92,
                    "impedance": 6,
                    "size": {
                        "height": 300,
                        "width": 180,
                        "depth": 180,
                    },
                    "weight": 4.0,
                },
            },
        },
    },
    "JBL 4312SE": {
        "brand": "JBL",
        "model": "4312SE",
        "type": "passive",
        "price": "3000",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "webplotdigitizer",
            },
        },
    },
    "JBL 4319": {
        "brand": "JBL",
        "model": "4319",
        "type": "passive",
        "price": "2500",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-4319-studio-monitor-review.12986/",
            },
        },
    },
    "JBL 4329P": {
        "brand": "JBL",
        "model": "4329P",
        "type": "active",
        "price": "4500",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jbl_4329p/",
                    "yt": "https://youtu.be/XhOz8WsKb8U",
                },
                "review_published": "20231124",
            },
        },
    },
    "JBL 4349": {
        "brand": "JBL",
        "model": "4349",
        "type": "passive",
        "price": "7500",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-4349-review-studio-monitor-speaker.22686/",
                "review_published": "20210420",
            },
        },
    },
    "JBL 4367": {
        "brand": "JBL",
        "model": "4367",
        "type": "passive",
        "price": "8500",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jbl_4367/",
                    "yt": "https://www.youtube.com/watch?v=eJnOrG3BHaw",
                },
                "review_published": "20220403",
            },
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "webplotdigitizer",
            },
        },
    },
    "JBL 4429": {
        "brand": "JBL",
        "model": "4429",
        "type": "passive",
        "price": "6000",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "webplotdigitizer",
                "review_published": "20140101",
            },
        },
    },
    "JBL HDI-1600": {
        "brand": "JBL",
        "model": "HDI-1600",
        "type": "passive",
        "price": "1800",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-hdi-1600-speaker-review.12477/",
            },
            "misc-napilopez": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "reviews": {
                    "asr": "https://thenextweb.com/news/these-3-studio-monitors-are-great-speakers-for-a-small-desk",
                    "tnw": "https://thenextweb.com/news/jbl-hdi-1600-review",
                },
            },
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "webplotdigitizer",
                "review": "https://speakerdata2034.blogspot.com/2021/01/jbl-synthesis-spinorama-data.html",
                "quality": "medium",
            },
        },
    },
    "JBL HDI-3600": {
        "brand": "JBL",
        "model": "HDI-3600",
        "type": "passive",
        "price": "3800",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-hdi-3600-speaker-review.13027/",
            },
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "webplotdigitizer",
                "review": "https://speakerdata2034.blogspot.com/2021/01/jbl-synthesis-spinorama-data.html",
                "quality": "medium",
            },
        },
    },
    "JBL HDI-3800": {
        "brand": "JBL",
        "model": "HDI-3800",
        "type": "passive",
        "price": "5800",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "eac-v2-20210416",
        "measurements": {
            "eac-v2-20210416": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jbl_hdi-3800/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-hdi-3800-floorstanding-speaker-review.21738/page-8",
                },
                "review_published": "20210416",
                "notes": "Second measurement with bass corrections",
            },
            "eac-v1-20210323": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/jbl_hdi-3800/",
                "review_published": "20210323",
            },
        },
    },
    "JBL HDI-4500": {
        "brand": "JBL",
        "model": "HDI-4500",
        "type": "passive",
        "price": "1750",
        "shape": "center",
        "amount": "each",
        "default_measurement": "eac-vertical",
        "measurements": {
            "eac-vertical": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jbl_hdi-4500/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-hdi-4500-center-channel-speaker-review.22025/",
                },
                "review_published": "20210401",
            },
            "eac-horizontal": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jbl_hdi-4500/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-hdi-4500-center-channel-speaker-review.22025/",
                },
                "review_published": "20210401",
            },
        },
    },
    "JBL L82 Classic": {
        "brand": "JBL",
        "model": "L82 Classic",
        "type": "passive",
        "price": "1250",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "misc-napilopez",
        "measurements": {
            "misc-napilopez": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "reviews": {
                    "tnw": "https://thenextweb.com/news/jbl-l82-classic-review-these-retro-speakers-offer-modern-acoustics",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-l82-classic-spinorama-and-measurements.15466/",
                },
                "quality": "low",
            },
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "webplotdigitizer",
            },
        },
    },
    "JBL LS 80": {
        "brand": "JBL",
        "model": "LS 80",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "misc-speakerdata2034",
        "measurements": {
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://speakerdata2034.blogspot.com/2019/06/harman-consumer-brands-spinorama-data.html",
            },
        },
    },
    "JBL LSR6332": {
        "brand": "JBL",
        "model": "LSR6332",
        "type": "passive",
        "price": "3200",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "webplotdigitizer",
            },
        },
    },
    "JBL M2": {
        "brand": "JBL",
        "model": "M2",
        "type": "active",
        "price": "12000",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jbl_m2/",
                    "yt": "",
                },
                "review_published": "20210821",
                "specifications": {
                    "dispersion": {
                        "horizontal": 120,
                        "vertical": 100,
                    },
                    "sensitivity": 92,
                    "SPL": {
                        "max": 117,
                        "peak": 123,
                    },
                    "size": {
                        "height": 1256,
                        "width": 508,
                        "depth": 355,
                    },
                    "weight": 58.5,
                },
            },
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "webplotdigitizer",
            },
        },
    },
    "JBL Northridge Series N28": {
        "brand": "JBL",
        "model": "Northridge Series N28",
        "type": "passive",
        "price": "",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "rew_text_dump",
            },
        },
    },
    "JBL PRX635": {
        "brand": "JBL",
        "model": "PRX635",
        "type": "passive",
        "price": "2540",
        "shape": "liveportable",
        "amount": "pair",
        "default_measurement": "princeton",
        "measurements": {
            "princeton": {
                "origin": "Princeton",
                "format": "princeton",
                "review": "https://www.princeton.edu/3D3A/Directivity.html",
                "review_published": "20151001",
            },
        },
    },
    "JBL PRX908": {
        "brand": "JBL",
        "model": "PRX908",
        "type": "active",
        "price": "850",
        "shape": "liveportable",
        "amount": "each",
        "default_measurement": "vendor-pattern-105x60",
        "measurements": {
            "vendor-pattern-105x60": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/spinorama-for-the-brand-new-jbl-prx900-serie.38843/",
                "review_published": "20221103",
                "specifications": {
                    "dispersion": {
                        "horizontal": 105,
                        "vertical": 60,
                    },
                    "SPL": {
                        "max": 126,
                    },
                    "size": {
                        "height": 479,
                        "width": 312,
                        "depth": 285,
                    },
                    "weight": 13.7,
                },
            },
        },
    },
    "JBL PRX912": {
        "brand": "JBL",
        "model": "PRX912",
        "type": "active",
        "price": "1000",
        "shape": "liveportable",
        "amount": "each",
        "default_measurement": "vendor-pattern-90x50",
        "measurements": {
            "vendor-pattern-90x50": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review": "",
                "review_published": "20221103",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 50,
                    },
                    "SPL": {
                        "max": 132,
                    },
                    "size": {
                        "height": 636,
                        "width": 394,
                        "depth": 332,
                    },
                    "weight": 19.5,
                },
            },
        },
    },
    "JBL PRX915": {
        "brand": "JBL",
        "model": "PRX915",
        "type": "active",
        "price": "1100",
        "shape": "liveportable",
        "amount": "each",
        "default_measurement": "vendor-pattern-90x50",
        "measurements": {
            "vendor-pattern-90x50": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review": "",
                "review_published": "20221103",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 50,
                    },
                    "SPL": {
                        "max": 133,
                    },
                    "size": {
                        "height": 717,
                        "width": 465,
                        "depth": 383,
                    },
                    "weight": 24.1,
                },
            },
        },
    },
    "JBL Studio 520C": {
        "brand": "JBL",
        "model": "Studio 520C",
        "type": "passive",
        "price": "",
        "shape": "center",
        "amount": "each",
        "default_measurement": "eac-vertical",
        "measurements": {
            "eac-vertical": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/jbl_520c_center/",
                "review_published": "20220111",
            },
            "eac-horizontal": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/jbl_520c_center/",
                "review_published": "20220111",
            },
        },
    },
    "JBL Studio 530": {
        "brand": "JBL",
        "model": "Studio 530",
        "type": "passive",
        "price": "600",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-studio-530-speaker-review.12298/",
            },
        },
    },
    "JBL Studio 590": {
        "brand": "JBL",
        "model": "Studio 590",
        "type": "passive",
        "price": "1000",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-studio-590-speaker-review.47269/",
                "review_published": "20230819",
            },
        },
    },
    "JBL Studio 630": {
        "brand": "JBL",
        "model": "Studio 630",
        "type": "passive",
        "price": "700",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jbl_studio_630/",
                    "yt": "https://youtu.be/PznnGL-hoSc",
                },
                "review_published": "20240112",
                "specifications": {
                    "sensitivity": 85,
                    "impedance": 6,
                    "size": {
                        "height": 372,
                        "width": 230,
                        "depth": 280,
                    },
                    "weight": 9.02,
                },
            },
        },
    },
    "JBL Studio 698": {
        "brand": "JBL",
        "model": "Studio 698",
        "type": "passive",
        "price": "1700",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jbl_studio_698/",
                    "yt": "https://youtu.be/DpwL5rXUMvg",
                },
                "review_published": "20240112",
                "specifications": {
                    "sensitivity": 90,
                    "impedance": 6,
                    "size": {
                        "height": 1058,
                        "width": 300,
                        "depth": 400,
                    },
                    "weight": 35.8,
                },
            },
        },
    },
    "JBL Studio Series S26": {
        "brand": "JBL",
        "model": "Studio Series S26",
        "type": "passive",
        "price": "",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-JBL",
                "format": "rew_text_dump",
            },
        },
    },
    "JBL VTX F35": {
        "brand": "JBL",
        "model": "VTX F35",
        "type": "active",
        "price": "5000",
        "shape": "toursound",
        "amount": "each",
        "default_measurement": "vendor-pattern-90x50",
        "measurements": {
            "vendor-pattern-90x50": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221107",
                "quality": "low",
                "notes": "data is highly smoothed. You can remove at least .6 to 1 to score computations",
            },
            "vendor-pattern-60x40": {
                "origin": "Vendors-JBL",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221107",
                "quality": "low",
                "notes": "data is highly smoothed. You can remove at least .6 to 1 to score computations",
            },
        },
    },
    "JBL XPL90": {
        "brand": "JBL",
        "model": "XPL90",
        "type": "passive",
        "price": "700",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/jbl-xpl90-speaker-review.13449/",
            },
        },
    },
    "JTR Noesis 210ht": {
        "brand": "JTR",
        "model": "Noesis 210ht",
        "type": "passive",
        "price": "4000",
        "shape": "cinema",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/jtr_2022_noesis_210ht/",
                    "yt": "https://youtu.be/pjMjcWramAw",
                },
                "review_published": "20220221",
            },
        },
    },
    "JTR Noesis 212rt": {
        "brand": "JTR",
        "model": "Noesis 212rt",
        "type": "passive",
        "price": "10400",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "misc-avnirvana",
        "measurements": {
            "misc-avnirvana": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "reviews": {
                    "avnirvana": "https://www.avnirvana.com/threads/jtr-noesis-212rt-review-and-measurements.6779/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/jtr-noesis-212rt-measurements.12688/",
                },
            },
        },
    },
}
