# -*- coding: utf-8 -*-
from . import SpeakerDatabase, gll_data_acquisition_std

speakers_info_d: SpeakerDatabase = {
    "Dali Oberon Vokal": {
        "brand": "Dali",
        "model": "Oberon Vokal",
        "type": "passive",
        "price": "359",
        "amount": "each",
        "shape": "center",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/dali-oberon-vokal-center-speaker-review.50624/",
                },
                "review_published": "20231221",
                "specifications": {
                    "sensitivity": 89.5,
                    "SPL": {
                        "peak": 109,
                    },
                    "size": {
                        "height": 161,
                        "width": 441,
                        "depth": 295,
                    },
                    "weight": 7.45,
                },
            },
        },
    },
    "Dali Spektor 1": {
        "brand": "Dali",
        "model": "Spektor 1",
        "type": "passive",
        "price": "250",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/dali-spektor-1-review-bookshelf-speaker.25063/",
                "review_published": "20210719",
            },
        },
    },
    "Dali Zensor 1": {
        "brand": "Dali",
        "model": "Zensor 1",
        "type": "passive",
        "shape": "bookshelves",
        "price": "100",
        "amount": "pair",
        "default_measurement": "misc-ageve",
        "measurements": {
            "misc-ageve": {
                "origin": "Misc",
                "format": "spl_hv_txt",
                "quality": "low",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/dali-zensor-1-spinorama-measurements-passive-version.55016/",
                },
                "review_published": "20240618",
                "specifications": {
                    "sensitivity": 86,
                    "impedance": 6,
                    "SPL": {
                        "peak": 106,
                    },
                    "size": {
                        "height": 274,
                        "width": 162,
                        "depth": 220,
                    },
                    "weight": 4.2,
                },
            },
        },
    },
    "Danley Cube": {
        "brand": "Danley",
        "model": "Cube",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "vendor-pattern-100x100",
        "measurements": {
            "vendor-pattern-100x100": {
                "origin": "Vendors-Danley",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221116",
                "quality": "medium",
            },
        },
    },
    "Danley J1-94": {
        "brand": "Danley",
        "model": "J1-94",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "vendor-pattern-90x40",
        "measurements": {
            "vendor-pattern-90x40": {
                "origin": "Vendors-Danley",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221116",
                "quality": "medium",
            },
        },
    },
    "Danley J2-96": {
        "brand": "Danley",
        "model": "J2-96",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-Danley",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221116",
                "quality": "medium",
            },
        },
    },
    "Danley J3-64": {
        "brand": "Danley",
        "model": "J3-64",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "vendor-pattern-60x40",
        "measurements": {
            "vendor-pattern-60x40": {
                "origin": "Vendors-Danley",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221116",
                "quality": "medium",
            },
        },
    },
    "Danley J4-31": {
        # graphs doesn't work, data is valid in a limited range.
        "skip": True,
        "brand": "Danley",
        "model": "J4-31",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Danley",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221116",
                "quality": "medium",
            },
        },
    },
    "Danley J6-42": {
        "brand": "Danley",
        "model": "J6-42",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Danley",
                "data_acquisition": gll_data_acquisition_std,
                "format": "gll_hv_txt",
                "review_published": "20221116",
                "quality": "medium",
            },
        },
    },
    "Danley J7-95": {
        # quality is  really low and also computation of LFX doesn't work, same case as DD
        "skip": True,
        "brand": "Danley",
        "model": "J7-95",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "vendor-pattern-90x50",
        "measurements": {
            "vendor-pattern-90x50": {
                "origin": "Vendors-Danley",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221116",
                "quality": "low",
            },
        },
    },
    "Danley SH-50": {
        "brand": "Danley",
        "model": "SH-50",
        "type": "passive",
        "price": "8000",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/danley_sh50/",
                    "yt": "",
                },
                "specifications": {
                    "sensitivity": 100,
                    "impedance": 4,
                    "SPL": {
                        "continuous": 127,
                        "peak": 133,
                    },
                    "size": {
                        "height": 711,
                        "width": 711,
                        "depth": 647,
                    },
                    "weight": 60.3,
                },
                "review_published": "20210815",
            },
            "vendor-pattern-50x50": {
                "origin": "Vendors-Danley",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/danley_sh50/",
                },
                "review_published": "20221116",
                "quality": "medium",
            },
        },
    },
    "Danley SH-60": {
        "brand": "Danley",
        "model": "SH-60",
        "type": "passive",
        "price": "8000",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "vendor-pattern-60x60",
        "measurements": {
            "vendor-pattern-60x60": {
                "origin": "Vendors-Danley",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221116",
                "quality": "medium",
            },
        },
    },
    "Danley SH-96-HO": {
        "brand": "Danley",
        "model": "SH-96-HO",
        "type": "passive",
        "price": "8000",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-Danley",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221116",
                "quality": "medium",
            },
        },
    },
    "Danley SH-Mini": {
        "skip": True,
        "brand": "Danley",
        "model": "SH-Mini",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "vendor-pattern-100x100",
        "measurements": {
            "vendor-pattern-100x100": {
                "origin": "Vendors-Danley",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20230112",
                "quality": "low",
                "specifications": {
                    "dispersion": {
                        "horizontal": 100,
                        "vertical": 100,
                    },
                    "sensitivity": 88,
                    "impedance": 8,
                    "SPL": {
                        "continuous": 111,
                        "peak": 117,
                    },
                    "size": {
                        "height": 254,
                        "width": 254,
                        "depth": 267,
                    },
                    "weight": 12,
                },
            },
        },
    },
    "Danley SH-Mini-180": {
        "brand": "Danley",
        "model": "SH-Mini-180",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "vendor-pattern-180x90",
        "measurements": {
            "vendor-pattern-180x90": {
                "origin": "Vendors-Danley",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221116",
                "quality": "low",
            },
        },
    },
    "Danley SM-60F": {
        "brand": "Danley",
        "model": "SM-60F",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Danley",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221117",
                "quality": "medium",
            },
        },
    },
    "Danley SM-60M": {
        "brand": "Danley",
        "model": "SM-60M",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Danley",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221117",
                "quality": "medium",
            },
        },
    },
    "Danley SM-80": {
        "brand": "Danley",
        "model": "SM-80",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Danley",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221117",
                "quality": "medium",
            },
        },
    },
    "Danley SM-80F": {
        # data is too low quality
        "skip": True,
        "brand": "Danley",
        "model": "SM-80F",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Danley",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221116",
                "quality": "medium",
            },
        },
    },
    "Danley SM-100": {
        "brand": "Danley",
        "model": "SM-100",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Danley",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221116",
                "quality": "medium",
            },
        },
    },
    "DAS Audio ARTEC 506A": {
        "brand": "DAS Audio",
        "model": "ARTEC 506A",
        "type": "active",
        "price": "900",
        "shape": "liveportable",
        "amount": "pair",
        "default_measurement": "vendor-pattern-80x80",
        "measurements": {
            "vendor-pattern-80x80": {
                "origin": "Vendors-DAS Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221024",
            },
        },
    },
    "DAS Audio ARTEC 508A": {
        "brand": "DAS Audio",
        "model": "ARTEC 508A",
        "type": "active",
        "price": "1000",
        "shape": "liveportable",
        "amount": "pair",
        "default_measurement": "vendor-pattern-80x80",
        "measurements": {
            "vendor-pattern-80x80": {
                "origin": "Vendors-DAS Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221024",
            },
        },
    },
    "DAS Audio ARTEC 526A": {
        "brand": "DAS Audio",
        "model": "ARTEC 526A",
        "type": "active",
        "price": "1100",
        "shape": "liveportable",
        "amount": "pair",
        "default_measurement": "vendor-pattern-80x80",
        "measurements": {
            "vendor-pattern-80x80": {
                "origin": "Vendors-DAS Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221024",
            },
        },
    },
    "DAS Audio ARTEC 510A": {
        "brand": "DAS Audio",
        "model": "ARTEC 510A",
        "type": "active",
        "price": "1800",
        "shape": "liveportable",
        "amount": "pair",
        "default_measurement": "vendor-pattern-110x50",
        "measurements": {
            "vendor-pattern-110x50": {
                "origin": "Vendors-DAS Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221024",
            },
        },
    },
    "DAS Audio Vantec 12A": {
        "brand": "DAS Audio",
        "model": "Vantec 12A",
        "type": "active",
        "price": "2500",
        "shape": "liveportable",
        "amount": "pair",
        "default_measurement": "vendor-pattern-90x50",
        "measurements": {
            "vendor-pattern-90x50": {
                "origin": "Vendors-DAS Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221027",
            },
        },
    },
    "DAS Audio Vantec 15A": {
        "brand": "DAS Audio",
        "model": "Vantec 15A",
        "type": "active",
        "price": "2800",
        "shape": "liveportable",
        "amount": "pair",
        "default_measurement": "vendor-pattern-90x50",
        "measurements": {
            "vendor-pattern-90x50": {
                "origin": "Vendors-DAS Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221027",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 50,
                    },
                    "SPL": {
                        "peak": 135,
                    },
                    "size": {
                        "height": 720,
                        "width": 445,
                        "depth": 380,
                    },
                    "weight": 25.5,
                },
            },
        },
    },
    "DAS Audio Vantec 20A": {
        "skip": True,
        "brand": "DAS Audio",
        "model": "Vantec 20A",
        "type": "active",
        "price": "2300",
        "shape": "liveportable",
        "amount": "pair",
        "default_measurement": "vendor-pattern-90x15",
        "measurements": {
            "vendor-pattern-90x15": {
                "origin": "Vendors-DAS Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20230111",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 15,
                    },
                    "SPL": {
                        "peak": 135,
                    },
                    "size": {
                        "height": 335,
                        "width": 625,
                        "depth": 440,
                    },
                    "weight": 28.5,
                },
            },
        },
    },
    "Dayton Audio B452-AIR": {
        "brand": "Dayton Audio",
        "model": "B452-AIR",
        "type": "passive",
        "price": "40",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-audioholics",
        "measurements": {
            "misc-audioholics": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://www.audioholics.com/bookshelf-speaker-reviews/b452-air-speaker/conclusion",
            },
        },
    },
    "Dayton Audio B652-AIR": {
        "brand": "Dayton Audio",
        "model": "B652-AIR",
        "type": "passive",
        "price": "70",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/dayton-audio-b652-air-speaker-review.11410/",
            },
        },
    },
    "Dayton Audio C452-AIR": {
        "brand": "Dayton Audio",
        "model": "C452-AIR",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "center",
        "default_measurement": "misc-audioholics",
        "measurements": {
            "misc-audioholics": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://www.audioholics.com/bookshelf-speaker-reviews/b452-air-speaker/conclusion",
            },
        },
    },
    "Dayton Audio MK402": {
        "brand": "Dayton Audio",
        "model": "MK402",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-audioholics",
        "measurements": {
            "misc-audioholics": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://www.audioholics.com/bookshelf-speaker-reviews/mk402-and-mk442-review/page-2",
            },
        },
    },
    "Dayton Audio MK402X": {
        "brand": "Dayton Audio",
        "model": "MK402X",
        "type": "passive",
        "price": "70",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/dayton-mk402x-review-bookshelf-speaker.23249/",
                "review_published": "20210510",
            },
        },
    },
    "Dayton Audio MK442": {
        "brand": "Dayton Audio",
        "model": "MK442",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "center",
        "default_measurement": "misc-audioholics",
        "measurements": {
            "misc-audioholics": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://www.audioholics.com/bookshelf-speaker-reviews/mk402-and-mk442-review/page-2",
            },
        },
    },
    "Dayton Audio MK602X": {
        "brand": "Dayton Audio",
        "model": "MK602X",
        "type": "passive",
        "price": "150",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/dayton_mk602x/",
                    "yt": "https://www.youtube.com/watch?v=-4QcUhlIuIM",
                },
                "review_published": "20211117",
            },
        },
    },
    "Dayton Audio OPAL1": {
        "skip": True,
        "brand": "Dayton Audio",
        "model": "OPAL1",
        "type": "passive",
        "price": "800",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/dayton_opal1/",
                    "yt": "https://youtu.be/BDv222LHNM0",
                },
                "review_published": "202404xx",
                "specifications": {
                    "sensitivity": 78.5,
                    "impedance": 4.3,
                    "SPL": {
                        "peak": 102,
                    },
                    "size": {
                        "height": 356,
                        "width": 178,
                        "depth": 241,
                    },
                    "weight": 9.4,
                },
            },
        },
    },
    "DB Audiotechnik 8S": {
        "brand": "DB Audiotechnik",
        "model": "8S",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-100x100",
        "measurements": {
            "vendor-pattern-100x100": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221126",
            },
        },
    },
    "DB Audiotechnik 10S": {
        "brand": "DB Audiotechnik",
        "model": "10S",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-110x45",
        "measurements": {
            "vendor-pattern-110x45": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221126",
            },
            "vendor-pattern-75x50": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221126",
            },
        },
    },
    "DB Audiotechnik 12S": {
        "brand": "DB Audiotechnik",
        "model": "12S",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-110x45",
        "measurements": {
            "vendor-pattern-110x45": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221126",
            },
            "vendor-pattern-75x50": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221126",
            },
        },
    },
    "DB Audiotechnik 24S": {
        "brand": "DB Audiotechnik",
        "model": "24S",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-110x45",
        "measurements": {
            "vendor-pattern-110x45": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221126",
                "specifications": {
                    "dispersion": {
                        "horizontal": 75,
                        "vertical": 45,
                    },
                    "SPL": {
                        "peak": 138,
                    },
                    "size": {
                        "height": 800,
                        "width": 410,
                        "depth": 420,
                    },
                    "weight": 33.0,
                },
            },
            "vendor-pattern-75x45": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221126",
                "specifications": {
                    "dispersion": {
                        "horizontal": 75,
                        "vertical": 45,
                    },
                    "SPL": {
                        "peak": 138,
                    },
                    "size": {
                        "height": 800,
                        "width": 410,
                        "depth": 420,
                    },
                    "weight": 33.0,
                },
            },
        },
    },
    "DB Audiotechnik 44S": {
        "brand": "DB Audiotechnik",
        "model": "44S",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-90x30",
        "measurements": {
            "vendor-pattern-90x30": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221126",
                "notes": "data computed at 2 meters.",
            },
        },
    },
    "DB Audiotechnik AL60": {
        "brand": "DB Audiotechnik",
        "model": "AL60",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "vendor-pattern-60x30-v3x+2sub",
        "measurements": {
            "vendor-pattern-60x30-v1x": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221203",
                "reviews": {
                    "pp": "https://www.production-partner.de/test/die-a-serie-von-db-im-test/",
                },
                "notes": "data computed at 2 meters.",
            },
            "vendor-pattern-60x30-v3x": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221203",
                "reviews": {
                    "pp": "https://www.production-partner.de/test/die-a-serie-von-db-im-test/",
                },
                "notes": "data computed at 2 meters.",
            },
            "vendor-pattern-60x30-v3x+2sub": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221203",
                "reviews": {
                    "pp": "https://www.production-partner.de/test/die-a-serie-von-db-im-test/",
                },
                "notes": "data computed at 2 meters. 3 AL60 with 2 ",
            },
        },
    },
    "DB Audiotechnik AL90": {
        "brand": "DB Audiotechnik",
        "model": "AL90",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "vendor-pattern-90x30-v1x",
        "measurements": {
            "vendor-pattern-90x30-v1x": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "reviews": {
                    "pp": "https://www.production-partner.de/test/die-a-serie-von-db-im-test/",
                },
                "review_published": "20221203",
                "notes": "data computed at 2 meters.",
            },
            "vendor-pattern-90x30-v3x": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "reviews": {
                    "pp": "https://www.production-partner.de/test/die-a-serie-von-db-im-test/",
                },
                "review_published": "20221203",
                "notes": "data computed at 2 meters.",
            },
        },
    },
    "DB Audiotechnik MAX2": {
        "brand": "DB Audiotechnik",
        "model": "MAX2",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20240717",
                "specifications": {
                    "impedance": 8,
                    "dispersion": {
                        "horizontal": 75,
                        "vertical": 75,
                    },
                    "SPL": {
                        "peak": 135,
                    },
                    "size": {
                        "height": 354,
                        "width": 580,
                        "depth": 496,
                    },
                    "weight": 23.0,
                },
            },
        },
    },
    "DB Audiotechnik M4": {
        "brand": "DB Audiotechnik",
        "model": "M4",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20240717",
                "specifications": {
                    "impedance": 8,
                    "dispersion": {
                        "horizontal": 50,
                        "vertical": 70,
                    },
                    "SPL": {
                        "peak": 140,
                    },
                    "size": {
                        "height": 363,
                        "width": 580,
                        "depth": 505,
                    },
                    "weight": 20.0,
                },
            },
        },
    },
    "DB Audiotechnik M6": {
        "brand": "DB Audiotechnik",
        "model": "M6",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20240717",
                "specifications": {
                    "impedance": 8,
                    "dispersion": {
                        "horizontal": 50,
                        "vertical": 80,
                    },
                    "SPL": {
                        "peak": 138,
                    },
                    "size": {
                        "height": 332,
                        "width": 486,
                        "depth": 455,
                    },
                    "weight": 16.0,
                },
            },
        },
    },
    "DB Audiotechnik Q7": {
        "brand": "DB Audiotechnik",
        "model": "Q7",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221217",
                "notes": "data computed at 2 meters.",
                "specifications": {
                    "dispersion": {
                        "horizontal": 75,
                        "vertical": 40,
                    },
                    "SPL": {
                        "peak": 134,
                    },
                    "size": {
                        "height": 580,
                        "width": 308,
                        "depth": 410,
                    },
                    "weight": 22.0,
                },
            },
        },
    },
    "DB Audiotechnik Q10": {
        "brand": "DB Audiotechnik",
        "model": "Q10",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221217",
                "notes": "data computed at 2 meters.",
                "specifications": {
                    "dispersion": {
                        "horizontal": 110,
                        "vertical": 40,
                    },
                    "SPL": {
                        "peak": 137,
                    },
                    "size": {
                        "height": 580,
                        "width": 308,
                        "depth": 410,
                    },
                    "weight": 22.0,
                },
            },
        },
    },
    "DB Audiotechnik V7P": {
        "brand": "DB Audiotechnik",
        "model": "V7P",
        "type": "passive",
        "price": "5600",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-75x40",
        "measurements": {
            "vendor-pattern-75x40": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "reviews": {
                    "pp": "https://www.production-partner.de/test/db-audiotechnik-v7p-v10p-v-gsub-test/",
                },
                "review_published": "20221126",
                "notes": "data computed at 2 meters.",
            },
        },
    },
    "DB Audiotechnik V10P": {
        "brand": "DB Audiotechnik",
        "model": "V10P",
        "type": "passive",
        "price": "5600",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-110x45",
        "measurements": {
            "vendor-pattern-110x45": {
                "origin": "Vendors-DB Audiotechnik",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "reviews": {
                    "pp": "https://www.production-partner.de/test/db-audiotechnik-v7p-v10p-v-gsub-test/",
                },
                "review_published": "20221126",
                "notes": "data computed at 2 meters.",
            },
        },
    },
    "dBTechnologies Opera Reevo 210": {
        "brand": "dBTechnologies",
        "model": "Opera Reevo 210",
        "type": "active",
        "price": "1200",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "misc-pp",
        "measurements": {
            "misc-pp": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "medium",
                "reviews": {
                    "pp": "https://www.production-partner.de/test/opera-reevo-210-von-dbtechnologies-im-test/",
                },
                "review_published": "20240914",
                "specifications": {
                    "dispersion": {
                        "horizontal": 100,
                        "vertical": 90,
                    },
                    "SPL": {
                        "peak": 132,
                    },
                    "size": {
                        "height": 604,
                        "width": 300,
                        "depth": 324,
                    },
                    "weight": 17.2,
                },
            },
        },
    },
    "Definitive Technology BP9020": {
        "brand": "Definitive Technology",
        "model": "BP9020",
        "type": "passive",
        "price": "500",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/deftech_bp9020/",
                    "dt": "https://www.definitivetechnology.com/en/product/legacy-products/bp9020",
                },
                "review_published": "20240331",
                "specifications": {
                    "sensitivity": 92,
                    "impedance": 8,
                    "size": {
                        "height": 902,
                        "width": 330,
                        "depth": 279,
                    },
                    "weight": 13.61,
                },
            },
        },
    },
    "Definitive Technology D9": {
        "brand": "Definitive Technology",
        "model": "D9",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-napilopez",
        "measurements": {
            "misc-napilopez": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/definitive-technology-d9-low-spinorama-and-measurements.13159/",
                },
            },
        },
    },
    "Definitive Technology Demand D11": {
        "brand": "Definitive Technology",
        "model": "Demand D11",
        "type": "passive",
        "price": "1200",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/definitive-demand-d11-speaker-review.15581/",
            },
        },
    },
    "Dennis Murphy Affordable Accuracy Monitor": {
        "brand": "Dennis Murphy",
        "model": "Affordable Accuracy Monitor",
        "type": "passive",
        "price": "",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/affordable-accuracy-monitor-review.13624/",
            },
        },
    },
    "Diapason Emera": {
        "brand": "Diapason",
        "model": "Emera",
        "type": "passive",
        "price": "1000",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/diapason-emera-italian-speaker-review.16193/",
            },
        },
    },
    "DIYSG Elusive 1099": {
        "brand": "DIYSG",
        "model": "Elusive 1099",
        "type": "passive",
        "price": "820",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/diysg_1099/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/diysg-1099-speaker-review-monday-jun-7-2021.24038/",
                    "avs": "https://www.avsforum.com/threads/a-3-way-99db-multi-configurable-seos-design.1479331/",
                },
                "review_published": "20210607",
            },
        },
    },
    "DIYSG HT-8": {
        "brand": "DIYSG",
        "model": "HT-8",
        "type": "passive",
        "price": "164",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "misc-mtg90",
        "measurements": {
            "misc-mtg90": {
                "origin": "Misc",
                "format": "spl_hv_txt",
                "quality": "low",
                "reviews": {
                    "diysg": "https://www.diysoundgroup.com/home-theater-speaker-kits/home-theater-series/home-theater/ht-8-kit.html",
                    "diy": "http://www.hificircuit.com/community/threads/htm-speaker-kits.609/",
                },
                "review_published": "20211205",
            },
        },
    },
    "DIYSG HT-10": {
        "brand": "DIYSG",
        "model": "HT-10",
        "type": "passive",
        "price": "216",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "misc-mtg90",
        "measurements": {
            "misc-mtg90": {
                "origin": "Misc",
                "format": "spl_hv_txt",
                "quality": "low",
                "reviews": {
                    "diysg": "https://www.diysoundgroup.com/home-theater-speaker-kits/home-theater-series/home-theater/ht-8-kit.html",
                    "diy": "http://www.hificircuit.com/community/threads/htm-speaker-kits.609/",
                },
                "review_published": "20211205",
            },
        },
    },
    "DIYSG HT-12": {
        "brand": "DIYSG",
        "model": "HT-12",
        "type": "passive",
        "price": "330",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "misc-mtg90",
        "measurements": {
            "misc-mtg90": {
                "origin": "Misc",
                "format": "spl_hv_txt",
                "quality": "low",
                "reviews": {
                    "diysg": "https://www.diysoundgroup.com/home-theater-speaker-kits/home-theater-series/home-theater/ht-8-kit.html",
                    "diy": "http://www.hificircuit.com/community/threads/htm-speaker-kits.609/",
                },
                "review_published": "20211205",
            },
        },
    },
    "DIYSG HT-12+": {
        "brand": "DIYSG",
        "model": "HT-12+",
        "type": "passive",
        "price": "330",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "misc-mtg90",
        "measurements": {
            "misc-mtg90": {
                "origin": "Misc",
                "format": "spl_hv_txt",
                "quality": "low",
                "reviews": {
                    "diysg": "https://www.diysoundgroup.com/home-theater-speaker-kits/home-theater-series/home-theater/ht-8-kit.html",
                    "diy": "http://www.hificircuit.com/community/threads/ht-12-upgrade-crossover.5891/",
                },
                "review_published": "20211205",
            },
        },
    },
    "DIYSG HTM-12v1": {
        "brand": "DIYSG",
        "model": "HTM-12v1",
        "type": "passive",
        "price": "600",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/diysg_htm12v1/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/diysg-htm-12v1-speaker-review.23654/",
                    "diysg": "https://www.diysoundgroup.com/htm-12-kit.html",
                    "diy": "https://www.diyaudio.com/forums/multi-way/354523-build-diysg-htm-12-2020-build-log.html",
                    "avf": "https://www.avforums.com/threads/htm-12-build-the-first-of-many.2211551/",
                },
                "review_published": "20210523",
            },
        },
    },
    "DIYSG HTM-12v2": {
        "brand": "DIYSG",
        "model": "HTM-12v2",
        "type": "passive",
        "price": "600",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/diysg_htm12v2/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/diysg-htm-12v2-review.24215/",
                },
                "review_published": "20210612",
            },
        },
    },
    "DIYSG Volt-6": {
        "brand": "DIYSG",
        "model": "Volt-6",
        "type": "passive",
        "price": "300",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/diysg_volt6/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/diy-sound-group-volt-6.23881/",
                },
                "review_published": "20210602",
                "notes": "sloped baffle measurement (see review)",
            },
        },
    },
    "DIYSG Volt-8 v2": {
        "brand": "DIYSG",
        "model": "Volt-8 v2",
        "type": "passive",
        "price": "300",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/diysg_volt8/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/diysg-volt-8-speaker-review.23907/#post-804491",
                },
                "review_published": "20210603",
            },
        },
    },
    "Dolby CS 133": {
        "brand": "Dolby",
        "model": "CS 133",
        "type": "passive",
        "price": "",
        "shape": "cinema",
        "amount": "each",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Dolby",
                "format": "spl_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20230602",
                "notes": "data computed from the 2 GLL files, one for the LF speaker and one for the MH speaker. The crossover used is a LR of order 8 and frequency of 365Hz.",
            },
        },
    },
    "Dolby CS 126": {
        "brand": "Dolby",
        "model": "CS 126",
        "type": "passive",
        "price": "",
        "shape": "cinema",
        "amount": "each",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Dolby",
                "format": "spl_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20230603",
            },
        },
    },
    "Dolby CS 126MH": {
        "skip": True,  # only here to provide data for the MH freq speaker
        "brand": "Dolby",
        "model": "CS 126MH",
        "type": "passive",
        "price": "",
        "shape": "cinema",
        "amount": "each",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Dolby",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20230603",
            },
        },
    },
    "Dolby CS 128": {
        "brand": "Dolby",
        "model": "CS 128",
        "type": "passive",
        "price": "",
        "shape": "cinema",
        "amount": "each",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Dolby",
                "format": "spl_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20230603",
            },
        },
    },
    "Dolby CS 128MH": {
        "skip": True,  # only here to provide data for the MH freq speaker
        "brand": "Dolby",
        "model": "CS 128MH",
        "type": "passive",
        "price": "",
        "shape": "cinema",
        "amount": "each",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Dolby",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20230603",
            },
        },
    },
    "Dolby CS 128LF": {
        "skip": True,  # only here to provide data for the MH freq speaker
        "brand": "Dolby",
        "model": "CS 128LF",
        "type": "passive",
        "price": "",
        "shape": "cinema",
        "amount": "each",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Dolby",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20230603",
            },
        },
    },
    "Dolby CS 136LF": {
        "skip": True,  # only here to provide data for the MH freq speaker
        "brand": "Dolby",
        "model": "CS 136LF",
        "type": "passive",
        "price": "",
        "shape": "cinema",
        "amount": "each",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Dolby",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20230601",
            },
        },
    },
    "Dolby CS 136MH": {
        "skip": True,  # only here to provide data for the MH freq speaker
        "brand": "Dolby",
        "model": "CS 136MH",
        "type": "passive",
        "price": "",
        "shape": "cinema",
        "amount": "each",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Dolby",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20230601",
            },
        },
    },
    "Donner Dyna 3": {
        "brand": "Donner",
        "model": "Dyna 3",
        "type": "active",
        "price": "90",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/donner_dyna3/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/donner-dyna-3-powered-bookshelf-speaker-89-monitors.23653/",
                },
                "review_published": "20210523",
            },
        },
    },
    "Donner Dyna 4": {
        "brand": "Donner",
        "model": "Dyna 4",
        "type": "active",
        "price": "90",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/donner-dyna-4-monitor-review.46474/",
                },
                "review_published": "20230717",
            },
        },
    },
    "Definitive Technology ProMonitor 1000": {
        "brand": "Definitive Technology",
        "model": "ProMonitor 1000",
        "type": "passive",
        "price": "400",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/definitive-technology-promonitor-1000-speaker-review.14220/",
            },
        },
    },
    "Devialet Phantom Reactor 900": {
        "brand": "Devialet",
        "model": "Phantom Reactor 900",
        "type": "active",
        "price": "1200",
        "amount": "each",
        "shape": "bookshelves",
        "default_measurement": "misc-napilopez",
        "measurements": {
            "misc-napilopez": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/devialet-phantom-reactor-900-measurements-now-with-spinorama.9963/page-2#post-305596",
                    "tnw": "https://thenextweb.com/news/review-devialets-phantom-reactor-is-the-david-to-your-subwoofers-goliath",
                },
            },
        },
    },
    "Devialet Phantom I": {
        "brand": "Devialet",
        "model": "Phantom I",
        "type": "active",
        "price": "2400",
        "amount": "each",
        "shape": "bookshelves",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Devialet",
                "format": "gll_hv_txt",
                "quality": "medium",
                "review_published": "20230910",
                "data_acquisition": gll_data_acquisition_std,
                "specifications": {
                    "SPL": {
                        "peak": 103,
                    },
                    "size": {
                        "height": 255,
                        "width": 252,
                        "depth": 342,
                    },
                    "weight": 11.4,
                },
            },
            "vendor-vGecko": {
                "origin": "Vendors-Devialet",
                "format": "gll_hv_txt",
                "quality": "medium",
                "review_published": "20230910",
                "data_acquisition": gll_data_acquisition_std,
                "specifications": {
                    "SPL": {
                        "peak": 103,
                    },
                    "size": {
                        "height": 255,
                        "width": 252,
                        "depth": 342,
                    },
                    "weight": 11.4,
                },
            },
            "vendor-vTree": {
                "origin": "Vendors-Devialet",
                "format": "gll_hv_txt",
                "quality": "medium",
                "review_published": "20230910",
                "data_acquisition": gll_data_acquisition_std,
                "specifications": {
                    "SPL": {
                        "peak": 103,
                    },
                    "size": {
                        "height": 255,
                        "width": 252,
                        "depth": 342,
                    },
                    "weight": 11.4,
                },
            },
        },
    },
    "Devialet Phantom II": {
        "brand": "Devialet",
        "model": "Phantom II",
        "type": "active",
        "price": "1200",
        "amount": "each",
        "shape": "bookshelves",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Devialet",
                "format": "gll_hv_txt",
                "quality": "medium",
                "review_published": "20230910",
                "data_acquisition": gll_data_acquisition_std,
                "specifications": {
                    "SPL": {
                        "peak": 95,
                    },
                    "size": {
                        "height": 168,
                        "width": 157,
                        "depth": 219,
                    },
                    "weight": 4.3,
                },
            },
        },
    },
    "Dutch Dutch 8C": {
        "brand": "Dutch Dutch",
        "model": "8C",
        "type": "active",
        "price": "10000",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/dutch_dutch_8c/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/dutch-dutch-8c-review.21016/",
                },
            },
            "misc-napilopez": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/dutch-dutch-8c-low-spinorama-and-measurements.12111/",
                    "tnw": "https://thenextweb.com/news/dutch-dutch-8c-review-super-high-end-speakers-with-the-best-bass-ive-ever-heard",
                },
            },
        },
    },
    "Dynaudio Core 47": {
        "brand": "Dynaudio",
        "model": "Core 47",
        "type": "active",
        "price": "2500",
        "shape": "bookshelves",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/dynaudio-core-47-review-professional-monitor.25113/",
                "review_published": "20210721",
            },
        },
    },
    "Dynaudio Emit M10": {
        "brand": "Dynaudio",
        "model": "Emit M10",
        "type": "passive",
        "price": "800",
        "shape": "bookshelves",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/dynaudio-emit-m10-review-bookshelf-speaker.20908/",
            },
        },
    },
    "Dynaudio Emit 20": {
        "brand": "Dynaudio",
        "model": "Emit 20",
        "type": "passive",
        "price": "800",
        "shape": "bookshelves",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://dynaudio.com/home-audio/emit/emit-20",
                    "yt": "https://youtu.be/Z7R9YApGY6w?si=BVOiNDokYFoPpWTE",
                },
                "review_published": "20231122",
                "specifications": {
                    "sensitivity": 86,
                    "impedance": 6,
                    "size": {
                        "height": 370,
                        "width": 205,
                        "depth": 211,
                    },
                    "weight": 10.32,
                },
            },
        },
    },
    "Dynaudio Excite X14": {
        "brand": "Dynaudio",
        "model": "Excite X14",
        "type": "passive",
        "price": "1500",
        "shape": "bookshelves",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/dynaudio-x14-speaker-review.17569/",
            },
        },
    },
    "Dynaudio LYD 5": {
        "brand": "Dynaudio",
        "model": "LYD 5",
        "type": "active",
        "price": "900",
        "shape": "bookshelves",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/dynaudio-lyd-5-studio-monitor-review.15963/",
            },
        },
    },
    "Dynaudio Heritage Special": {
        "brand": "Dynaudio",
        "model": "Heritage Special",
        "type": "passive",
        "price": "7000",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/dynaudio_heritage_special",
                    "yt": "https://youtu.be/vKwWokI3K08",
                },
                "review_published": "20231124",
                "specifications": {
                    "sensitivity": 85,
                    "impedance": 4,
                    "size": {
                        "height": 385,
                        "width": 208,
                        "depth": 320,
                    },
                    "weight": 11.0,
                },
            },
        },
    },
    "Dynaudio Special Forty": {
        "brand": "Dynaudio",
        "model": "Special Forty",
        "type": "passive",
        "price": "3000",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/dynaudio_special_forty/",
                    "yt": "https://youtu.be/jDTOAw4gLNM",
                },
                "review_published": "20231124",
                "specifications": {
                    "sensitivity": 86,
                    "impedance": 6,
                    "size": {
                        "height": 360,
                        "width": 198,
                        "depth": 307,
                    },
                    "weight": 8.1,
                },
            },
        },
    },
    "Dynaudio Xeo 3": {
        "brand": "Dynaudio",
        "model": "Xeo 3",
        "type": "passive",
        "price": "",
        "shape": "bookshelves",
        "default_measurement": "princeton",
        "measurements": {
            "princeton": {
                "origin": "Princeton",
                "format": "princeton",
                "review": "https://www.princeton.edu/3D3A/Directivity.html",
                "review_published": "20151001",
            },
        },
    },
}
