# -*- coding: utf-8 -*-
from . import SpeakerDatabase, gll_data_acquisition_std

speakers_info_y: SpeakerDatabase = {
    "Yamaha DBR10": {
        "brand": "Yamaha",
        "model": "DBR10",
        "type": "active",
        "price": "740",
        "shape": "liveportable",
        "amount": "pair",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-Yamaha",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221022",
            },
        },
    },
    "Yamaha DBR12": {
        "brand": "Yamaha",
        "model": "DBR12",
        "type": "active",
        "price": "920",
        "shape": "liveportable",
        "amount": "pair",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-Yamaha",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221022",
            },
        },
    },
    "Yamaha DBR15": {
        "brand": "Yamaha",
        "model": "DBR15",
        "type": "active",
        "price": "940",
        "shape": "liveportable",
        "amount": "pair",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-Yamaha",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221025",
            },
        },
    },
    "Yamaha DXR8mkII": {
        "brand": "Yamaha",
        "model": "DXR8mkII",
        "type": "active",
        "price": "1300",
        "shape": "liveportable",
        "amount": "pair",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-Yamaha",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221025",
            },
        },
    },
    "Yamaha DXR10mkII": {
        "brand": "Yamaha",
        "model": "DXR10mkII",
        "type": "active",
        "price": "1400",
        "shape": "liveportable",
        "amount": "pair",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-Yamaha",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221025",
            },
        },
    },
    "Yamaha DXR12mkII": {
        "brand": "Yamaha",
        "model": "DXR12mkII",
        "type": "active",
        "price": "1500",
        "shape": "liveportable",
        "amount": "pair",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-Yamaha",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221025",
            },
        },
    },
    "Yamaha DXR15mkII": {
        "brand": "Yamaha",
        "model": "DXR15mkII",
        "type": "active",
        "price": "1700",
        "shape": "liveportable",
        "amount": "pair",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-Yamaha",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221025",
            },
        },
    },
    "Yamaha DZR10": {
        "brand": "Yamaha",
        "model": "DZR10",
        "type": "active",
        "price": "2400",
        "shape": "liveportable",
        "amount": "pair",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-Yamaha",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221022",
            },
        },
    },
    "Yamaha DZR12": {
        "brand": "Yamaha",
        "model": "DZR12",
        "type": "active",
        "price": "2600",
        "shape": "liveportable",
        "amount": "pair",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-Yamaha",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221022",
            },
        },
    },
    "Yamaha DZR15": {
        "brand": "Yamaha",
        "model": "DZR15",
        "type": "active",
        "price": "2400",
        "shape": "liveportable",
        "amount": "pair",
        "default_measurement": "vendor-pattern-90x50",
        "measurements": {
            "vendor-pattern-90x50": {
                "origin": "Vendors-Yamaha",
                "data_acquisition": gll_data_acquisition_std,
                "format": "gll_hv_txt",
                "quality": "medium",
                "review_published": "20221025",
            },
        },
    },
    "Yamaha DZR315": {
        "brand": "Yamaha",
        "model": "DZR315",
        "type": "active",
        "price": "3400",
        "shape": "liveportable",
        "amount": "pair",
        "default_measurement": "vendor-pattern-75x50",
        "measurements": {
            "vendor-pattern-75x50": {
                "origin": "Vendors-Yamaha",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221022",
            },
        },
    },
    "Yamaha HS5": {
        "brand": "Yamaha",
        "model": "HS5",
        "type": "active",
        "price": "399",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/yamaha-hs5-powered-monitor-review.10967/",
                "review_published": "20200119",
            },
        },
    },
    "Yamaha HS7": {
        "brand": "Yamaha",
        "model": "HS7",
        "type": "active",
        "price": "640",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/yamaha-hs7-review-studio-monitor.19761/",
                "review_published": "20201026",
            },
        },
    },
    "Yamaha NS-18": {
        "brand": "Yamaha",
        "model": "NS-18",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-mab",
        "measurements": {
            "misc-mab": {
                "origin": "Misc",
                "format": "spl_hv_txt",
                "quality": "low",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/vintage-yamaha-ns-18-speaker-measurements.58087/",
                },
                "review_published": "20241105",
                "specifications": {
                    "impedance": 8,
                    "size": {
                        "height": 720,
                        "width": 540,
                        "depth": 250,
                    },
                    "weight": 18.0,
                },
            },
        },
    },
    "Yamaha NS-A638": {
        "brand": "Yamaha",
        "model": "NS-A638",
        "type": "passive",
        "price": "",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Yamaha",
                "format": "rew_text_dump",
                "review": "",
            },
        },
    },
    "Yamaha NS-6490": {
        "brand": "Yamaha",
        "model": "NS-6490",
        "type": "passive",
        "price": "130",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/yamaha-ns-6490-3-way-budget-speaker-review.17042/",
                "review_published": "20201026",
            },
        },
    },
    "Yamaha VXL1-8": {
        "brand": "Yamaha",
        "model": "VXL1-8",
        "type": "passive",
        "price": "500",
        "shape": "columns",
        "amount": "each",
        "default_measurement": "vendor-pattern-170x40",
        "measurements": {
            "vendor-pattern-170x40": {
                "origin": "Vendors-Yamaha",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20231020",
                "specifications": {
                    "dispersion": {
                        "horizontal": 170,
                        "vertical": 40,
                    },
                    "sensitivity": 89,
                    "impedance": 8,
                    "SPL": {
                        "peak": 111,
                    },
                    "size": {
                        "height": 480,
                        "width": 54,
                        "depth": 104,
                    },
                    "weight": 2.1,
                },
            },
        },
    },
    "Yamaha VXL1-24": {
        "brand": "Yamaha",
        "model": "VXL1-24",
        "type": "passive",
        "price": "1340",
        "shape": "columns",
        "amount": "each",
        "default_measurement": "vendor-pattern-180x25",
        "measurements": {
            "vendor-pattern-180x25": {
                "origin": "Vendors-Yamaha",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221025",
                "specifications": {
                    "dispersion": {
                        "horizontal": 180,
                        "vertical": 25,
                    },
                    "sensitivity": 91,
                    "impedance": 8,
                    "SPL": {
                        "peak": 117,
                    },
                    "size": {
                        "height": 1212,
                        "width": 54,
                        "depth": 104,
                    },
                    "weight": 5.5,
                },
            },
        },
    },
    "Yamaha VXS3F": {
        "brand": "Yamaha",
        "model": "VXS3F",
        "type": "passive",
        "price": "284",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Yamaha",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20231019",
                "specifications": {
                    "dispersion": {
                        "horizontal": 75,
                        "vertical": 80,
                    },
                    "sensitivity": 86,
                    "impedance": 8,
                    "SPL": {
                        "peak": 105,
                    },
                    "size": {
                        "height": 130,
                        "width": 184,
                        "depth": 94,
                    },
                    "weight": 1.0,
                },
            },
        },
    },
    "Yamaha VXS5": {
        "brand": "Yamaha",
        "model": "VXS5",
        "type": "passive",
        "price": "585",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Yamaha",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20231019",
                "specifications": {
                    "dispersion": {
                        "horizontal": 60,
                        "vertical": 60,
                    },
                    "sensitivity": 89,
                    "impedance": 8,
                    "SPL": {
                        "peak": 114,
                    },
                    "size": {
                        "height": 280,
                        "width": 176,
                        "depth": 163,
                    },
                    "weight": 3.6,
                },
            },
        },
    },
}
