# -*- coding: utf-8 -*-
from . import SpeakerDatabase, gll_data_acquisition_std

speakers_info_a: SpeakerDatabase = {
    "Acoustic Energy AE100 Mk2": {
        "brand": "Acoustic Energy",
        "model": "AE100 Mk2",
        "type": "passive",
        "price": "500",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/acoustic_energy_ae100_mk2/",
                    "yt": "https://youtu.be/-q4VkErtoAQ",
                },
                "review_published": "20231129",
                "specifications": {
                    "sensitivity": 87,
                    "impedance": 6,
                    "SPL": {
                        "peak": 112,
                    },
                    "size": {
                        "height": 290,
                        "width": 165,
                        "depth": 250,
                    },
                    "weight": 4.6,
                },
            },
        },
    },
    "Adam A4V": {
        "brand": "Adam",
        "model": "A4V",
        "type": "active",
        "price": "422",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/adam-a4v-monitor-review.36704/",
                "review_published": "20220822",
            },
        },
    },
    "Adam A5X": {
        "brand": "Adam",
        "model": "A5X",
        "type": "active",
        "price": "500",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/adam-a5x-review-powered-studio-monitor.22860/",
                "review_published": "20210427",
            },
        },
    },
    "Adam A7V": {
        "brand": "Adam",
        "model": "A7V",
        "type": "active",
        "price": "579",
        "shape": "bookshelves",
        "amount": "each",
        "default_measurement": "misc-sr",
        "measurements": {
            "misc-sr": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "medium",
                "reviews": {
                    "snr": "https://www.soundandrecording.de/equipment/studiomonitor-adam-audio-a7v-im-test/",
                },
                "review_published": "20240914",
                "specifications": {
                    "size": {
                        "height": 337,
                        "width": 200,
                        "depth": 280,
                    },
                    "weight": 8.7,
                },
            },
        },
    },
    "Adam S2V": {
        "brand": "Adam",
        "model": "S2V",
        "type": "active",
        "price": "3500",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/adam-s2v-studio-monitor-review.11455",
                "review_published": "20200213",
            },
        },
    },
    "Adam T5V": {
        "brand": "Adam",
        "model": "T5V",
        "type": "active",
        "price": "169",
        "shape": "bookshelves",
        "amount": "each",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/adam-t5v-review-studio-monitor.18122/",
                "review_published": "20201204",
            },
        },
    },
    "Adam T7V": {
        "brand": "Adam",
        "model": "T7V",
        "type": "active",
        "price": "190",
        "amount": "each",
        "shape": "bookshelves",
        "default_measurement": "misc-audioholics",
        "measurements": {
            "misc-audioholics": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://www.audioholics.com/bookshelf-speaker-reviews/adam-audio-t7v/conclusion",
                "notes": "done by James Larson in free air",
            },
        },
    },
    "Adam T8V": {
        "brand": "Adam",
        "model": "T8V",
        "type": "active",
        "price": "480",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/adam-t8v-studio-monitor-review.17118/",
                "review_published": "20201028",
            },
        },
    },
    "Advent The New Advent Loudspeaker": {
        "brand": "Advent",
        "model": "The New Advent Loudspeaker",
        "type": "passive",
        "price": "",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/the-new-advent-loudspeaker-review-vintage-speaker.24993/",
                "review_published": "20210715",
            },
        },
    },
    "AIA Cinema CCRM10-P": {
        "brand": "AIA Cinema",
        "model": "CCRM10-P",
        "type": "passive",
        "price": "2500",
        "amount": "pair",
        "shape": "cinema",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-AIA Cinema",
                "format": "webplotdigitizer",
                "quality": "medium",
                "reviews": {
                    "vendor": "https://www.aia-cinema.com/passive-speakers/ccrm10-p.html",
                },
                "review_published": "20220501",
            },
        },
    },
    "Alcons Audio LR7+LRB": {
        "brand": "Alcons Audio",
        "model": "LR7+LRB",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Alcons Audio",
                "format": "gll_hv_txt",
                "quality": "high",
                "review_published": "20221020",
                "notes": "Configuration with 2 LR7 and 1 LRB",
                "data_acquisition": gll_data_acquisition_std,
            },
        },
    },
    "Alcons Audio QRP20 90x15": {
        "brand": "Alcons Audio",
        "model": "QRP20 90x15",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "columns",
        "default_measurement": "vendor-v2-20230112",
        "measurements": {
            "vendor-v2-20230112": {
                "origin": "Vendors-Alcons Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "reviews": {
                    "psw": "https://www.prosoundweb.com/alcons-introduces-qrp20-pro-ribbon-point-source-column/",
                    "axp": "https://audioxpress.com/news/alcons-audio-introduces-qrp20-pro-ribbon-column-array",
                },
                "review_published": "20230112",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 15,
                    },
                    "sensitivity": 99,
                    "impedance": 4,
                    "SPL": {
                        "peak": 133,
                    },
                    "size": {
                        "height": 742,
                        "width": 150,
                        "depth": 150,
                    },
                    "weight": 12,
                },
            },
            "vendor-v1-20221020": {
                "origin": "Vendors-Alcons Audio",
                "format": "spl_hv_txt",
                "quality": "high",
                "reviews": {
                    "psw": "https://www.prosoundweb.com/alcons-introduces-qrp20-pro-ribbon-point-source-column/",
                    "axp": "https://audioxpress.com/news/alcons-audio-introduces-qrp20-pro-ribbon-column-array",
                },
                "review_published": "20221020",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 15,
                    },
                    "sensitivity": 99,
                    "impedance": 4,
                    "SPL": {
                        "peak": 133,
                    },
                    "size": {
                        "height": 742,
                        "width": 150,
                        "depth": 150,
                    },
                    "weight": 12,
                },
                "data_acquisition": {
                    "via": "gll",
                    "distance": 2.0,
                    "signal": "aes 20Hz-20kHz",
                    "air_absorbtion": True,
                    "resolution": 10.0,
                },
            },
        },
    },
    "Alcons Audio QRP20 120x15": {
        "brand": "Alcons Audio",
        "model": "QRP20 120x15",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "columns",
        "default_measurement": "vendor-v2-20230112",
        "measurements": {
            "vendor-v2-20230112": {
                "origin": "Vendors-Alcons Audio",
                "format": "gll_hv_txt",
                "quality": "high",
                "reviews": {
                    "psw": "https://www.prosoundweb.com/alcons-introduces-qrp20-pro-ribbon-point-source-column/",
                    "axp": "https://audioxpress.com/news/alcons-audio-introduces-qrp20-pro-ribbon-column-array",
                },
                "review_published": "20230112",
                "specifications": {
                    "dispersion": {
                        "horizontal": 120,
                        "vertical": 15,
                    },
                    "sensitivity": 97,
                    "impedance": 4,
                    "SPL": {
                        "peak": 131,
                    },
                    "size": {
                        "height": 742,
                        "width": 150,
                        "depth": 150,
                    },
                    "weight": 12,
                },
                "data_acquisition": gll_data_acquisition_std,
            },
            "vendor-v1-20221020": {
                "origin": "Vendors-Alcons Audio",
                "format": "spl_hv_txt",
                "quality": "high",
                "reviews": {
                    "psw": "https://www.prosoundweb.com/alcons-introduces-qrp20-pro-ribbon-point-source-column/",
                    "axp": "https://audioxpress.com/news/alcons-audio-introduces-qrp20-pro-ribbon-column-array",
                },
                "review_published": "20221020",
                "specifications": {
                    "dispersion": {
                        "horizontal": 120,
                        "vertical": 15,
                    },
                    "sensitivity": 97,
                    "impedance": 4,
                    "SPL": {
                        "peak": 131,
                    },
                    "size": {
                        "height": 742,
                        "width": 150,
                        "depth": 150,
                    },
                    "weight": 12,
                },
                "data_acquisition": {
                    "via": "gll",
                    "distance": 2.0,
                    "signal": "aes 20Hz-20kHz",
                    "air_absorbtion": True,
                    "resolution": 10.0,
                },
            },
        },
    },
    "Alcons Audio QRP40": {
        "brand": "Alcons Audio",
        "model": "QRP40",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "columns",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Alcons Audio",
                "format": "gll_hv_txt",
                "quality": "high",
                "review_published": "20230324",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 40,
                    },
                    "sensitivity": 103,
                    "impedance": 4,
                    "SPL": {
                        "peak": 131,
                    },
                    "size": {
                        "height": 1118,
                        "width": 161,
                        "depth": 236,
                    },
                    "weight": 22,
                },
                "data_acquisition": gll_data_acquisition_std,
            },
        },
    },
    "Alcons Audio QR24": {
        "brand": "Alcons Audio",
        "model": "QR24",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "columns",
        "default_measurement": "vendor-pattern-110x4",
        "measurements": {
            "vendor-pattern-110x4": {
                "origin": "Vendors-Alcons Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20221024",
                "specifications": {
                    "dispersion": {
                        "horizontal": 110,
                        "vertical": 3.6,
                    },
                    "sensitivity": 108,
                    "impedance": 8,
                    "SPL": {
                        "peak": 140,
                    },
                    "size": {
                        "height": 658,
                        "width": 248,
                        "depth": 336,
                    },
                    "weight": 22,
                },
            },
            "vendor-pattern-80x4": {
                "origin": "Vendors-Alcons Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20221024",
                "specifications": {
                    "dispersion": {
                        "horizontal": 80,
                        "vertical": 3.6,
                    },
                    "sensitivity": 109,
                    "impedance": 8,
                    "SPL": {
                        "peak": 141,
                    },
                    "size": {
                        "height": 658,
                        "width": 248,
                        "depth": 336,
                    },
                    "weight": 22,
                },
            },
            "vendor-v2QR24+2QM24": {
                "origin": "Vendors-Alcons Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20221204",
            },
            "vendor-v3QR24+1QM24": {
                "origin": "Vendors-Alcons Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20221204",
            },
        },
    },
    "Alcons Audio RR12": {
        "brand": "Alcons Audio",
        "model": "RR12",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "toursound",
        "default_measurement": "vendor-v6x",
        "measurements": {
            "vendor-v6x": {
                "origin": "Vendors-Alcons Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20221110",
                "notes": "This is for 6 RR12 in a vertical orientation.",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/spinorama-of-alcons-audio-rr12-with-beamforming-examples.39117/",
                },
            },
            "vendor-v1x": {
                "origin": "Vendors-Alcons Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20221110",
                "notes": "This is for 1 RR12 in a vertical orientation.",
            },
            "vendor-v3x": {
                "origin": "Vendors-Alcons Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20221110",
                "notes": "This is for 3 RR12 in a vertical orientation.",
            },
        },
    },
    "Alcons Audio SR9": {
        "brand": "Alcons Audio",
        "model": "SR9",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Alcons Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20221024",
            },
        },
    },
    "Alcons Audio VR5 V1": {
        "brand": "Alcons Audio",
        "model": "VR5 V1",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Alcons Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "reviews": {
                    "axp": "https://audioxpress.com/news/alcons-introduce-vr5-mini-versatile-monitor-with-patent-pending-waveguide-technology",
                },
                "review_published": "20221020",
            },
        },
    },
    "Amate Audio X102FD": {
        "brand": "Amate Audio",
        "model": "X102FD",
        "type": "active",
        "price": "5350",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Amate Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "specifications": {
                    "dispersion": {
                        "horizontal": 80,
                        "vertical": 60,
                    },
                    "SPL": {
                        "continuous": 136,
                        "peak": 139,
                    },
                    "size": {
                        "height": 704,
                        "width": 330,
                        "depth": 460,
                    },
                    "weight": 32,
                },
                "review_published": "20230218",
            },
        },
    },
    "Amate Audio X12CLA": {
        "brand": "Amate Audio",
        "model": "X12CLA",
        "type": "active",
        "price": "4150",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Amate Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "specifications": {
                    "dispersion": {
                        "horizontal": 100,
                        "vertical": 15,
                    },
                    "SPL": {
                        "continuous": 129,
                        "peak": 132,
                    },
                    "size": {
                        "height": 352,
                        "width": 680,
                        "depth": 485,
                    },
                    "weight": 31.5,
                },
                "review_published": "20230218",
            },
        },
    },
    "Amate Audio X14FD": {
        "brand": "Amate Audio",
        "model": "X14FD",
        "type": "active",
        "price": "",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Amate Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "specifications": {
                    "dispersion": {
                        "horizontal": 80,
                        "vertical": 80,
                    },
                    "SPL": {
                        "continuous": 129,
                        "peak": 132,
                    },
                    "size": {
                        "height": 623,
                        "width": 402,
                        "depth": 430,
                    },
                    "weight": 22.6,
                },
                "review_published": "20230218",
            },
        },
    },
    "Amazon Basic R60BTUS": {
        "brand": "Amazon Basic",
        "model": "R60BTUS",
        "type": "active",
        "price": "50",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/amazon-basics-80w-review-bookshelf-speaker.29304/",
                "review_published": "20211224",
            },
        },
    },
    "Amphion Argon1": {
        "brand": "Amphion",
        "model": "Argon1",
        "type": "passive",
        "price": "2500",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-napilopez",
        "measurements": {
            "misc-napilopez": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/amphion-argon1-low-spinorama-and-measurements-updated.13025/",
                },
                "review_published": "20200303",
            },
        },
    },
    "Andersson HIS 2.1": {
        "brand": "Andersson",
        "model": "HIS 2.1",
        "type": "passive",
        "price": "20",
        "amount": "each",
        "shape": "center",
        "default_measurement": "misc-ageve",
        "measurements": {
            "misc-ageve": {
                "origin": "Misc",
                "format": "spl_hv_txt",
                "quality": "low",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/spinorama-measurements-of-a-19-center-speaker-andersson-pure-acoustics.55029/#post-2002105",
                },
                "review_published": "20240616",
                "specifications": {
                    "sensitivity": 89,
                    "impedance": 8,
                    "size": {
                        "height": 160,
                        "width": 460,
                        "depth": 190,
                    },
                    "weight": 4.0,
                },
            },
        },
    },
    "Argon Audio 6340": {
        "brand": "Argon Audio",
        "model": "6340",
        "type": "active",
        "shape": "bookshelves",
        "price": "94",
        "amount": "pair",
        "default_measurement": "misc-ageve",
        "measurements": {
            "misc-ageve": {
                "origin": "Misc",
                "format": "spl_hv_txt",
                "quality": "low",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/argon-6340-spinorama-measurements-small-bookshelf-speaker.55247/",
                },
                "review_published": "20240622",
            },
        },
    },
    "Argon Audio 6350": {
        "brand": "Argon Audio",
        "model": "6350",
        "type": "active",
        "shape": "bookshelves",
        "price": "174",
        "amount": "pair",
        "default_measurement": "misc-ageve",
        "measurements": {
            "misc-ageve": {
                "origin": "Misc",
                "format": "spl_hv_txt",
                "quality": "low",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/argon-6350-bookshelf-speaker-spinorama-measurements.55175/",
                },
                "review_published": "20240616",
            },
        },
    },
    "Apple Homepod": {
        "brand": "Apple",
        "model": "Homepod",
        "type": "active",
        "price": "500",
        "shape": "omnidirectional",
        "amount": "each",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/apple-homepod-review-smart-speaker.23882/",
                    "ssa": "https://www.sausalitoaudio.com/data/",
                },
                "review_published": "20210602",
                "notes": "...So what you see below is accurate to about 8 kHz. Above that, there is some error but on-axis response shows surprisingly good agreement so I think we are fine...",
                "quality": "medium",
            },
            "misc-sausalitoaudio": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "review": "https://www.sausalitoaudio.com/data/",
                "quality": "low",
            },
        },
    },
    "Apple Homepod Mini": {
        "brand": "Apple",
        "model": "Homepod Mini",
        "type": "active",
        "price": "100",
        "shape": "omnidirectional",
        "amount": "each",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/apple_homepod_mini/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/apple-homepod-mini-review.24588/",
                },
                "review_published": "20210627",
                "notes": "Score formula is for monopole speaker and it is unclear if it applies also to this kind of speaker. Same comment for EQ where it may or may not work.",
            },
        },
    },
    "Aperion Audio Novus N5B": {
        "brand": "Aperion Audio",
        "model": "Novus N5B",
        "type": "passive",
        "price": "300",
        "shape": "bookshelves",
        "amount": "each",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/aperion_novus_n5b/",
                },
                "review_published": "20231129",
                "specifications": {
                    "sensitivity": 85,
                    "impedance": 4,
                    "size": {
                        "height": 300,
                        "width": 180,
                        "depth": 200,
                    },
                    "weight": 4.5,
                },
            },
        },
    },
    "Aperion Audio Novus N6SR": {
        "brand": "Aperion Audio",
        "model": "Novus N6SR",
        "type": "passive",
        "price": "650",
        "shape": "surround",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/aperion_novus_n6sr/",
                },
                "review_published": "20231129",
                "specifications": {
                    "sensitivity": 86,
                    "impedance": 4,
                    "size": {
                        "height": 300,
                        "width": 200,
                        "depth": 125,
                    },
                    "weight": 4.5,
                },
            },
        },
    },
    "Aperion Audio Novus N5C": {
        "brand": "Aperion Audio",
        "model": "Novus N5C",
        "type": "passive",
        "price": "550",
        "shape": "center",
        "amount": "each",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/aperion_novus_n5c/",
                },
                "review_published": "20231129",
                "specifications": {
                    "sensitivity": 88,
                    "impedance": 4,
                    "size": {
                        "height": 186,
                        "width": 485,
                        "depth": 231,
                    },
                    "weight": 8.5,
                },
            },
        },
    },
    "Aperion Audio Novus N5T": {
        "brand": "Aperion Audio",
        "model": "Novus N5T",
        "type": "passive",
        "price": "1400",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/aperion-n5t-speaker-review.38821/",
                "review_published": "20221104",
            },
        },
    },
    "Aperion Audio Verus III Concert V8B": {
        "brand": "Aperion Audio",
        "model": "Verus III Concert V8B",
        "type": "passive",
        "price": "750",
        "shape": "bookshelves",
        "amount": "each",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/aperion_verus_8/",
                    "yt": "https://youtu.be/JzU9cxYMkKg",
                },
                "review_published": "20230619",
                "specifications": {
                    "sensitivity": 88,
                    "impedance": 6,
                    "size": {
                        "height": 433,
                        "width": 269,
                        "depth": 330,
                    },
                    "weight": 12.7,
                },
            },
        },
    },
    "Aperion Audio Verus III Concert V6C": {
        "brand": "Aperion Audio",
        "model": "Verus III Concert V6C",
        "type": "passive",
        "price": "680",
        "shape": "center",
        "amount": "each",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/aperion_verus_6_center/",
                    "yt": "https://youtu.be/JzU9cxYMkKg",
                },
                "review_published": "20230619",
                "specifications": {
                    "sensitivity": 87,
                    "impedance": 4,
                    "size": {
                        "height": 629,
                        "width": 279,
                        "depth": 235,
                    },
                    "weight": 15.0,
                },
            },
        },
    },
    "Arendal Sound 1961 Center": {
        "brand": "Arendal Sound",
        "model": "1961 Center",
        "type": "passive",
        "price": "550",
        "shape": "center",
        "amount": "each",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/arendal-1961-center-monitor-speaker-review.43190/",
                "review_published": "20230323",
            },
        },
    },
    "Arendal Sound 1961 Monitor": {
        "brand": "Arendal Sound",
        "model": "1961 Monitor",
        "type": "passive",
        "price": "1100",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/arendal-1961-center-monitor-speaker-review.43190/",
                "review_published": "20230323",
            },
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/arenda_1961_monitor/",
                },
                "review_published": "20231009",
            },
        },
    },
    "Arendal Sound 1961 Bookshelf": {
        "brand": "Arendal Sound",
        "model": "1961 Bookshelf",
        "type": "passive",
        "price": "700",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/arendal_1961_bookshelf/",
                },
                "review_published": "20220118",
            },
        },
    },
    "Arendal Sound 1961 Tower": {
        "brand": "Arendal Sound",
        "model": "1961 Tower",
        "type": "passive",
        "price": "1700",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "eac-sealed",
        "measurements": {
            "eac-sealed": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/arendal_1961_tower/",
                    "yt": "https://www.youtube.com/watch?v=Ba7aFNyNYZo",
                },
                "review_published": "20220122",
            },
        },
    },
    "Arendal Sound 1723 Bookshelf S THX": {
        "brand": "Arendal Sound",
        "model": "1723 Bookshelf S THX",
        "type": "passive",
        "price": "1500",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac-v2-20220526",
        "measurements": {
            "eac-v2-20220526": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/arendal_1723_thx_s/",
                "review_published": "20220526",
            },
            "eac-v1-20220430": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/arendal_1723_thx_s/",
                "review_published": "20220430",
                "notes": "This version had a bad tweeter.",
            },
        },
    },
    "Arendal Sound 1723 Monitor THX": {
        "brand": "Arendal Sound",
        "model": "1723 Monitor THX",
        "type": "passive",
        "price": "2400",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/arendal-1723-speaker-review.46141/",
                "review_published": "20230704",
            },
            "misc-audioholics": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://www.audioholics.com/bookshelf-speaker-reviews/arendal-1723/conclusion",
                "review_published": "20210705",
            },
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/arendal_1723_thx_monitor",
                },
                "review_published": "20231011",
            },
        },
    },
    "Arendal Sound 1723 Monitor S THX": {
        "brand": "Arendal Sound",
        "model": "1723 Monitor S THX",
        "type": "passive",
        "price": "2000",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/arendal_1723_thx_s_monitor/",
                },
                "review_published": "20231011",
                "specifications": {
                    "sensitivity": 88.7,
                    "impedance": 4,
                    "size": {
                        "height": 569,
                        "width": 245,
                        "depth": 320,
                    },
                    "weight": 18.7,
                },
            },
        },
    },
    "Attack Audio VSH206": {
        "brand": "Attack Audio",
        "model": "VSH206",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Attack Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20230424",
                "specifications": {
                    "dispersion": {
                        "horizontal": 100,
                        "vertical": 15,
                    },
                    "SPL": {
                        "peak": 128,
                    },
                    "size": {
                        "height": 620,
                        "width": 236,
                        "depth": 373,
                    },
                    "weight": 20.3,
                },
            },
        },
    },
    "Attack Audio VSL206": {
        "brand": "Attack Audio",
        "model": "VSL206",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Attack Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20230424",
                "specifications": {
                    "dispersion": {
                        "horizontal": 100,
                        "vertical": 15,
                    },
                    "SPL": {
                        "peak": 128,
                    },
                    "size": {
                        "height": 209,
                        "width": 650,
                        "depth": 367,
                    },
                    "weight": 25.6,
                },
            },
        },
    },
    "Attack Audio VSL206+sub": {
        "brand": "Attack Audio",
        "model": "VSL206+sub",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Attack Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20230424",
                "specifications": {
                    "dispersion": {
                        "horizontal": 100,
                        "vertical": 15,
                    },
                    "SPL": {
                        "peak": 128,
                    },
                    "size": {
                        "height": 209,
                        "width": 650,
                        "depth": 367,
                    },
                    "weight": 25.6,
                },
            },
        },
    },
    "Ascend Acoustics CBM-170 SE": {
        "brand": "Ascend Acoustics",
        "model": "CBM-170 SE",
        "type": "passive",
        "shape": "bookshelves",
        "price": "400",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/ascend-cbm-170-se-speaker-review.11839",
                "review_published": "20200302",
            },
            "princeton": {
                "origin": "Princeton",
                "format": "princeton",
                "symmetry": "horizontal",
                "review": "https://www.princeton.edu/3D3A/Directivity.html",
                "review_published": "20151001",
            },
        },
    },
    "Ascend Acoustics CMT-340 Center": {
        "brand": "Ascend Acoustics",
        "model": "CMT-340 Center",
        "type": "passive",
        "shape": "center",
        "price": "300",
        "amount": "each",
        "default_measurement": "asr-vertical",
        "measurements": {
            "asr-vertical": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/ascend-cmt-340-se-center-channel-speaker-review.11797/#post-340461",
                "review_published": "20200229",
            },
            "asr-horizontal": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/ascend-cmt-340-se-center-channel-speaker-review.11797/#post-340461",
                "review_published": "20200229",
            },
        },
    },
    "Ascend Acoustics CMT-340 SE2": {
        "brand": "Ascend Acoustics",
        "model": "CMT-340 SE2",
        "type": "passive",
        "shape": "bookshelves",
        "price": "350",
        "amount": "each",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Ascend Acoustics",
                "format": "spl_hv_txt",
                "quality": "high",
                "review_published": "20221108",
            },
        },
    },
    "Ascend Acoustics ELX Ribbon Horizon": {
        "brand": "Ascend Acoustics",
        "model": "ELX Ribbon Horizon",
        "type": "passive",
        "shape": "center",
        "price": "2800",
        "amount": "each",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Ascend Acoustics",
                "format": "spl_hv_txt",
                "quality": "high",
                "review_published": "20240127",
                "specifications": {
                    "impedance": 8,
                    "sensitivity": 88.0,
                    "size": {
                        "height": 279,
                        "width": 584,
                        "depth": 317,
                    },
                    "weight": 24,
                },
            },
        },
    },
    "Ascend Acoustics ELX Ribbon Tower": {
        "brand": "Ascend Acoustics",
        "model": "ELX Ribbon Tower",
        "type": "passive",
        "shape": "floorstanders",
        "price": "2649",
        "amount": "each",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Ascend Acoustics",
                "format": "spl_hv_txt",
                "quality": "high",
                "review_published": "20231118",
                "specifications": {
                    "dispersion": {
                        "horizontal": 80,
                        "vertical": 80,
                    },
                    "impedance": 8,
                    "sensitivity": 87.5,
                    "size": {
                        "height": 109.22,
                        "width": 190,
                        "depth": 267,
                    },
                    "weight": 25.4,
                },
            },
        },
    },
    "Ascend Acoustics Horizon Center": {
        "brand": "Ascend Acoustics",
        "model": "Horizon Center",
        "type": "passive",
        "shape": "center",
        "price": "1490",
        "amount": "each",
        "default_measurement": "asr-vertical",
        "measurements": {
            "asr-vertical": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/ascend-acoustics-horizon-center-speaker-review.15199/",
                "review_published": "20200808",
            },
            "asr-horizontal": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/ascend-acoustics-horizon-center-speaker-review.15199/",
                "review_published": "20200808",
            },
        },
    },
    "Ascend Acoustics Luna Mini-Monitor": {
        "brand": "Ascend Acoustics",
        "model": "Luna Mini-Monitor",
        "type": "passive",
        "shape": "bookshelves",
        "price": "1150",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/ascend-sierra-luna-mini-monitor-review.17181/#post-556036",
                "review_published": "20201031",
            },
        },
    },
    "Ascend Acoustics Luna Duo": {
        "brand": "Ascend Acoustics",
        "model": "Luna Duo",
        "type": "passive",
        "shape": "center",
        "price": "800",
        "amount": "each",
        "default_measurement": "asr-vertical",
        "measurements": {
            "asr-vertical": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/ascend-sierra-luna-duo-center-main-speaker-review.17259/",
                "review_published": "20201103",
            },
            "asr-horizontal": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/ascend-sierra-luna-duo-center-main-speaker-review.17259/",
                "review_published": "20201103",
            },
        },
    },
    "Ascend Acoustics Sierra 1 V2": {
        "brand": "Ascend Acoustics",
        "model": "Sierra 1 V2",
        "type": "passive",
        "shape": "bookshelves",
        "price": "1000",
        "amount": "pair",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Ascend Acoustics",
                "format": "spl_hv_txt",
                "quality": "high",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/ascend_sierra_1_v2/",
                    "yt": "https://youtu.be/XuLAkwYEdfY",
                    "history": "https://forum.ascendacoustics.com/showthread.php?7896-Something-old-is-young-again-introducing-the-Sierra-1-V2!!!",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/ascend-sierra-1-v2-speaker-review.53350/",
                },
                "review_published": "20231209",
                "specifications": {
                    "sensitivity": 87,
                    "impedance": 8,
                    "size": {
                        "height": 362,
                        "width": 190,
                        "depth": 267,
                    },
                    "weight": 8.4,
                },
            },
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/ascend_sierra_1_v2/",
                    "yt": "https://youtu.be/XuLAkwYEdfY",
                    "history": "https://forum.ascendacoustics.com/showthread.php?7896-Something-old-is-young-again-introducing-the-Sierra-1-V2!!!",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/ascend-sierra-1-v2-speaker-review.53350/",
                },
                "review_published": "20231124",
                "specifications": {
                    "sensitivity": 87,
                    "impedance": 8,
                    "size": {
                        "height": 362,
                        "width": 190,
                        "depth": 267,
                    },
                    "weight": 8.4,
                },
            },
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/ascend_sierra_1_v2/",
                    "yt": "https://youtu.be/XuLAkwYEdfY",
                    "history": "https://forum.ascendacoustics.com/showthread.php?7896-Something-old-is-young-again-introducing-the-Sierra-1-V2!!!",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/ascend-sierra-1-v2-speaker-review.53350/",
                },
                "review_published": "20240329",
                "specifications": {
                    "sensitivity": 87,
                    "impedance": 8,
                    "size": {
                        "height": 362,
                        "width": 190,
                        "depth": 267,
                    },
                    "weight": 8.4,
                },
            },
        },
    },
    "Ascend Acoustics Sierra 2": {
        "brand": "Ascend Acoustics",
        "model": "Sierra 2",
        "type": "passive",
        "shape": "bookshelves",
        "price": "1500",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/ascend-sierra-2-speaker-review.11813/#post-341009",
                "review_published": "20200301",
            },
        },
    },
    "Ascend Acoustics Sierra-2EX": {
        # removed since Dave (owner of Ascend Acoustics) asked for it. He will provide new more complete data.
        "skip": True,
        "brand": "Ascend Acoustics",
        "model": "Sierra-2EX",
        "type": "passive",
        "price": "3600",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Ascend Acoustics",
                "format": "webplotdigitizer",
                "quality": "low",
                "reviews": {
                    "vendor": "http://www.ascendacoustics.com/pages/products/speakers/SRM2EX/srm2exmeas.html",
                    "spd2034": "https://speakerdata2034.blogspot.com/2019/12/ascend-acoustics-spinorama-data.html",
                },
            },
        },
    },
    "Ascend Acoustics Sierra-2EX V2": {
        "brand": "Ascend Acoustics",
        "model": "Sierra-2EX V2",
        "type": "passive",
        "price": "1648",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Ascend Acoustics",
                "format": "spl_hv_txt",
                "quality": "high",
                "reviews": {
                    "vendor": "https://ascendacoustics.com/collections/sierra-series-pairs/products/sierra-2ex-v2-pair?variant=40390917750838",
                },
                "review_published": "20220928",
            },
        },
    },
    "Ascend Acoustics Sierra-LX": {
        "brand": "Ascend Acoustics",
        "model": "Sierra-LX",
        "type": "passive",
        "price": "1400",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Ascend Acoustics",
                "format": "spl_hv_txt",
                "quality": "high",
                "reviews": {
                    "vendor": "http://forum.ascendacoustics.com/showthread.php?7588-Introducing-the-Sierra-LX!!!",
                },
                "review_published": "20220324",
            },
        },
    },
    "Ascend Acoustics Sierra Titan": {
        "brand": "Ascend Acoustics",
        "model": "Sierra Titan",
        "type": "passive",
        "price": "3000",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "vendor-dome-tweeter",
        "measurements": {
            "vendor-dome-tweeter": {
                "origin": "Vendors-Ascend Acoustics",
                "format": "spl_hv_txt",
                "quality": "high",
                "reviews": {
                    "vendor": "https://ascendacoustics.com/collections/sierra-series-pairs/products/sierra-tower-v2-pair?variant=40596422754358",
                },
                "review_published": "20230118",
                "specifications": {
                    "sensitivity": 91,
                    "impedance": 8,
                    "size": {
                        "height": 1092,
                        "width": 190,
                        "depth": 267,
                    },
                    "weight": 20.4,
                },
            },
        },
    },
    "AsciLab A6B Passive": {
        "brand": "AsciLab",
        "model": "A6B Passive",
        "type": "passive",
        "price": "2900",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "vendor-v2-20240917",
        "measurements": {
            "vendor-v2-20240917": {
                "origin": "Vendors-AsciLab",
                "format": "klippel",
                "quality": "high",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/ascilab-speakers-are-about-to-launch.54794/",
                },
                "review_published": "20240923",
                "specifications": {
                    "size": {
                        "height": 400,
                        "width": 220,
                        "depth": 260,
                    },
                    "weight": 13.0,
                },
            },
            "vendor-v1-20240720": {
                "origin": "Vendors-AsciLab",
                "format": "klippel",
                "quality": "high",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/ascilab-speakers-are-about-to-launch.54794/",
                },
                "review_published": "20240720",
                "specifications": {
                    "size": {
                        "height": 400,
                        "width": 220,
                        "depth": 260,
                    },
                    "weight": 13.0,
                },
            },
        },
    },
    "AsciLab C5B": {
        "brand": "AsciLab",
        "model": "C5B",
        "type": "passive",
        "price": "1000",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "vendor-v2-20240919",
        "measurements": {
            "vendor-v2-20240919": {
                "origin": "Vendors-AsciLab",
                "format": "klippel",
                "quality": "high",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/ascilab-speakers-are-about-to-launch.54794/",
                    "abi": "https://audiolabinsight.com/t/ascilab-c5b-ver/248",
                },
                "review_published": "20240920",
                "specifications": {
                    "size": {
                        "height": 362,
                        "width": 176,
                        "depth": 230,
                    },
                    "weight": 10.4,
                },
            },
            "vendor-v1-20240814": {
                "origin": "Vendors-AsciLab",
                "format": "klippel",
                "quality": "high",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/ascilab-speakers-are-about-to-launch.54794/",
                    "abi": "https://audiolabinsight.com/t/ascilab-c5b-ver/248",
                },
                "review_published": "20240531",
                "specifications": {
                    "size": {
                        "height": 362,
                        "width": 176,
                        "depth": 230,
                    },
                    "weight": 10.4,
                },
            },
        },
    },
    "AsciLab C6B": {
        "brand": "AsciLab",
        "model": "C6B",
        "type": "passive",
        "price": "1100",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "vendor-v2-20240919",
        "measurements": {
            "vendor-v2-20240919": {
                "origin": "Vendors-AsciLab",
                "format": "klippel",
                "quality": "high",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/ascilab-speakers-are-about-to-launch.54794/",
                    "abi": "https://audiolabinsight.com/t/ascilab-c6b-ver/247",
                },
                "review_published": "20240920",
                "specifications": {
                    "size": {
                        "height": 385,
                        "width": 197,
                        "depth": 265,
                    },
                    "weight": 10.5,
                },
            },
            "vendor-v1-20240814": {
                "origin": "Vendors-AsciLab",
                "format": "klippel",
                "quality": "high",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/ascilab-speakers-are-about-to-launch.54794/",
                    "abi": "https://audiolabinsight.com/t/ascilab-c6b-ver/247",
                },
                "review_published": "20240531",
                "specifications": {
                    "size": {
                        "height": 385,
                        "width": 197,
                        "depth": 265,
                    },
                    "weight": 10.5,
                },
            },
        },
    },
    "ASR Directiva Open Source Speaker": {
        "brand": "ASR",
        "model": "Directiva Open Source Speaker",
        "type": "active",
        "price": "1400",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/asr-directiva-open-source-speaker-review.27094/",
                "review_published": "20211006",
            },
        },
    },
    "ATC SCM19 v1": {
        "brand": "ATC",
        "model": "SCM19 v1",
        "type": "passive",
        "price": "4000",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/atc-scm19-bookshelf-speaker-review.14519/",
                "review_published": "20200703",
            },
        },
    },
    "Atlantic Technology 8600eLR Tower": {
        "brand": "Atlantic Technology",
        "model": "8600eLR Tower",
        "type": "passive",
        "price": "5600",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "avs": "https://www.avsforum.com/threads/atlantic-technology-8600elr-and-8600ec-tower-and-center-channel-objective-based-review.3240929/#post-61549716",
                },
                "review_published": "20220328",
            },
        },
    },
    "Atlantic Technology 8600eC Center": {
        "brand": "Atlantic Technology",
        "model": "8600eC Center",
        "type": "passive",
        "price": "1750",
        "shape": "center",
        "amount": "each",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "avs": "https://www.avsforum.com/threads/atlantic-technology-8600elr-and-8600ec-tower-and-center-channel-objective-based-review.3240929/#post-61549716",
                },
                "review_published": "20220328",
            },
        },
    },
    "Audio Engine A2": {
        "brand": "Audio Engine",
        "model": "A2",
        "type": "active",
        "shape": "bookshelves",
        "price": "200",
        "amount": "pair",
        "default_measurement": "misc-archimago",
        "measurements": {
            "misc-archimago": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "review": "https://archimago.blogspot.com/2020/10/qspins-audioengine-a2-edifier-s2000-mk.html",
                "review_published": "20201031",
                "quality": "low",
            },
        },
    },
    "Audio Engine A2+": {
        "skip": True,
        "brand": "Audio Engine",
        "model": "A2+",
        "type": "active",
        "shape": "bookshelves",
        "price": "269",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "",
                    "yt": "https://youtu.be/mAMv_ueINlk?si=eGu5yNVAlAJ1encX",
                },
                "review_published": "2024xxxx",
                "specifications": {
                    "size": {
                        "height": 159,
                        "width": 106,
                        "depth": 167,
                    },
                    "weight": 1.6,
                },
            },
        },
    },
    "Audio Engine A5+ Powered": {
        "brand": "Audio Engine",
        "model": "A5+ Powered",
        "type": "active",
        "shape": "bookshelves",
        "price": "400",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/audioengine-a5-powered-speaker-review.13803/",
                "review_published": "20200531",
            },
        },
    },
    "Audiofocus VENU 8a": {
        "brand": "Audiofocus",
        "model": "VENU 8a",
        "type": "active",
        "price": "2100",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Audiofocus",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "low",
                "specifications": {
                    "dispersion": {
                        "horizontal": 80,
                        "vertical": 80,
                    },
                    "SPL": {
                        "peak": 134,
                    },
                    "size": {
                        "height": 430,
                        "width": 273,
                        "depth": 291,
                    },
                    "weight": 11.5,
                },
                "review_published": "20230326",
            },
        },
    },
    "Audiofocus VENU 12a": {
        "brand": "Audiofocus",
        "model": "VENU 12a",
        "type": "active",
        "price": "2890",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Audiofocus",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "low",
                "specifications": {
                    "dispersion": {
                        "horizontal": 110,
                        "vertical": 60,
                    },
                    "SPL": {
                        "peak": 135,
                    },
                    "size": {
                        "height": 566,
                        "width": 362,
                        "depth": 357,
                    },
                    "weight": 18.5,
                },
                "review_published": "20230326",
            },
        },
    },
    "Audiofocus VENU 15a": {
        "brand": "Audiofocus",
        "model": "VENU 15a",
        "type": "active",
        "price": "3220",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Audiofocus",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "low",
                "specifications": {
                    "dispersion": {
                        "horizontal": 100,
                        "vertical": 60,
                    },
                    "SPL": {
                        "peak": 136,
                    },
                    "size": {
                        "height": 638,
                        "width": 426,
                        "depth": 412,
                    },
                    "weight": 22.5,
                },
                "review_published": "20230326",
            },
        },
    },
    "Audio Pro Addon T14": {
        "brand": "Audio Pro",
        "model": "Addon T14",
        "type": "active",
        "shape": "bookshelves",
        "price": "190",
        "amount": "pair",
        "default_measurement": "misc-ageve",
        "measurements": {
            "misc-ageve": {
                "origin": "Misc",
                "format": "spl_hv_txt",
                "quality": "low",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/audio-pro-addon-t14-spinorama-measurements.55291/#post-2009936",
                },
                "review_published": "20240622",
            },
        },
    },
    "AV123 X-CS Center": {
        "brand": "AV123",
        "model": "X-CS Center",
        "type": "passive",
        "shape": "center",
        "price": "199",
        "amount": "each",
        "default_measurement": "asr-vertical",
        "measurements": {
            "asr-vertical": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/av123-x-cs-center-speaker-review.40156/",
                "review_published": "20221218",
            },
            "asr-horizontal": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/av123-x-cs-center-speaker-review.40156/",
                "review_published": "20221218",
            },
        },
    },
    "Avantgarde Acoustic Solo": {
        "brand": "Avantgarde Acoustic",
        "model": "Solo",
        "type": "passive",
        "shape": "floorstanders",
        "price": "7000",
        "amount": "pair",
        "default_measurement": "princeton",
        "measurements": {
            "princeton": {
                "origin": "Princeton",
                "format": "princeton",
                "symmetry": "coaxial",
                "review": "https://www.princeton.edu/3D3A/Directivity.html",
                "review_published": "20151001",
            },
        },
    },
    "Avantone Pro CLA-10": {
        "brand": "Avantone Pro",
        "model": "CLA-10",
        "type": "passive",
        "shape": "bookshelves",
        "price": "550",
        "amount": "each",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/avantone-cla-10-yamaha-ns-10m-clone-review.46954/",
                    "top": "https://tapeop.com/reviews/gear/133/cla-10-passive-studio-monitor-system/",
                    "brd": "https://www.barryrudolph.com/mix/avantone_cla10.html",
                    "inl": "https://www.interface.nl/nieuws/artikel/54-23228/avantone-pro-cla-10-en-cla-200-studiomonitors-en-versterker",
                },
                "review_published": "20230805",
            },
        },
    },
    "Avantone Pro MixCube": {
        "brand": "Avantone Pro",
        "model": "MixCube",
        "type": "active",
        "shape": "bookshelves",
        "price": "259",
        "amount": "each",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/avantone-pro-mixcube-monitor-review.42817/",
                "review_published": "20230311",
            },
        },
    },
    "Axiom ED60P": {
        "brand": "Axiom",
        "model": "ED60P",
        "type": "passive",
        "price": "815",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Axiom",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20221126",
                "notes": "data computed at 2 meters.",
            },
        },
    },
    "Axiom ED80P": {
        "brand": "Axiom",
        "model": "ED80P",
        "type": "passive",
        "price": "950",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Axiom",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20221126",
                "notes": "data computed at 2 meters.",
            },
        },
    },
    "Axiom ED120A": {
        "brand": "Axiom",
        "model": "ED120A",
        "type": "active",
        "price": "1790",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Axiom",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20221126",
                "notes": "data computed at 2 meters.",
            },
        },
    },
    "Axiom ED150A": {
        "brand": "Axiom",
        "model": "ED150A",
        "type": "active",
        "price": "1990",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Axiom",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20221126",
                "notes": "data computed at 2 meters.",
            },
        },
    },
}
