# -*- coding: utf-8 -*-
from . import SpeakerDatabase, gll_data_acquisition_std

speakers_info_c: SpeakerDatabase = {
    "Cambridge Soundworks Model Six": {
        "brand": "Cambridge Soundworks",
        "model": "Model Six",
        "type": "passive",
        "shape": "bookshelves",
        "price": "",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Cambridge Soundworks",
                "format": "rew_text_dump",
            },
        },
    },
    "Cambridge Audio Minx XL": {
        "brand": "Cambridge Audio",
        "model": "Minx XL",
        "type": "passive",
        "price": "300",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/cambridge-audio-minx-xl-speaker-review.60824/",
                },
                "review_published": "20250216",
                "specifications": {
                    "sensitivity": 87,
                    "impedance": 8,
                    "size": {
                        "height": 225,
                        "width": 161,
                        "depth": 240,
                    },
                    "weight": 3.0,
                },
            },
        },
    },
    "Canon S-50": {
        "brand": "Canon",
        "model": "S-50",
        "type": "passive",
        "shape": "omnidirectional",
        "price": "300",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/canon-s-50-wide-directivity-speaker-review.13982/",
            },
        },
    },
    "Canton Plus GLX.3": {
        "brand": "Canton",
        "model": "Plus GLX.3",
        "type": "passive",
        "shape": "bookshelves",
        "price": "170",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/canton-plus-glx-3-review-speaker.18203/",
            },
        },
    },
    "Canton Vento 826.2": {
        "brand": "Canton",
        "model": "Vento 826.2",
        "type": "passive",
        "shape": "bookshelves",
        "price": "780",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/canton-vento-826-2-speaker-review.40475/",
                "review_published": "20221229",
                "specifications": {
                    "sensitivity": 85,
                    "impedance": 4,
                    "size": {
                        "height": 300,
                        "width": 195,
                        "depth": 270,
                    },
                    "weight": 6,
                },
            },
        },
    },
    "Carmody S2000 DIY Speaker Kit": {
        "brand": "Carmody",
        "model": "S2000 DIY Speaker Kit",
        "type": "passive",
        "shape": "bookshelves",
        "price": "240",
        "default_measurement": "asr",
        "amount": "pair",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/carmody-s2000-diy-speaker-kit-reivew.17507/",
            },
        },
    },
    "Celuaris Purify SPK5 prototype": {
        "brand": "Celuaris",
        "model": "Purify SPK5 prototype",
        "type": "passive",
        "price": "2000",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr-v2-20210206",
        "measurements": {
            "asr-v2-20210206": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/celuaris-spk5-purifi-review-speaker.20125/",
            },
            "asr-v1-20201124": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/purifi-spk5-speaker-review-prototype.17806/",
            },
        },
    },
    "Chane A1.5": {
        "brand": "Chane",
        "model": "A1.5",
        "type": "passive",
        "price": "329",
        "shape": "bookshelves",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/chane-a1-5-review-bookshelf-speaker.26078/",
                "review_published": "20210825",
            },
        },
    },
    "Coda Audio CoRay4": {
        "brand": "Coda Audio",
        "model": "CoRay4",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "columns",
        "default_measurement": "vendor-pattern-120x12",
        "measurements": {
            "vendor-pattern-120x12": {
                "origin": "Vendors-Coda Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20221126",
                "notes": "120x12 configuration",
            },
            "vendor-pattern-60x12": {
                "origin": "Vendors-Coda Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20221126",
                "notes": "60x12 configuration.",
            },
        },
    },
    "Coda Audio G512": {
        "brand": "Coda Audio",
        "model": "G512",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-Coda Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20230308",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 60,
                    },
                    "sensitivity": 98,
                    "impedance": 8,
                    "SPL": {
                        "peak": 132,
                    },
                    "size": {
                        "height": 630,
                        "width": 348,
                        "depth": 320,
                    },
                    "weight": 16.0,
                },
            },
        },
    },
    "Coda Audio G515": {
        "brand": "Coda Audio",
        "model": "G515",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-Coda Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20230308",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 60,
                    },
                    "sensitivity": 98,
                    "impedance": 8,
                    "SPL": {
                        "peak": 132,
                    },
                    "size": {
                        "height": 700,
                        "width": 420,
                        "depth": 370,
                    },
                    "weight": 17.5,
                },
            },
        },
    },
    "Coda Audio G712": {
        "brand": "Coda Audio",
        "model": "G712",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-Coda Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20230308",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 60,
                    },
                    "sensitivity": 98,
                    "impedance": 8,
                    "SPL": {
                        "peak": 143,
                    },
                    "size": {
                        "height": 700,
                        "width": 420,
                        "depth": 370,
                    },
                    "weight": 24.5,
                },
            },
        },
    },
    "Coda Audio G715": {
        "brand": "Coda Audio",
        "model": "G715",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-Coda Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20230308",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 60,
                    },
                    "sensitivity": 98,
                    "impedance": 8,
                    "SPL": {
                        "peak": 143,
                    },
                    "size": {
                        "height": 700,
                        "width": 420,
                        "depth": 370,
                    },
                    "weight": 24.5,
                },
            },
        },
    },
    "Coda Audio HOPS5": {
        "brand": "Coda Audio",
        "model": "HOPS5",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Coda Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20221115",
            },
        },
    },
    "Coda Audio HOPS8": {
        "brand": "Coda Audio",
        "model": "HOPS8",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Coda Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20221115",
            },
        },
    },
    "Coda Audio HOPS12": {
        "brand": "Coda Audio",
        "model": "HOPS12",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-90x60",
        "measurements": {
            "vendor-pattern-90x60": {
                "origin": "Vendors-Coda Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20221115",
                "notes": "90x60 configuration",
            },
            "vendor-pattern-60x40": {
                "origin": "Vendors-Coda Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20221115",
                "notes": "60x40 configuration.",
            },
        },
    },
    "Coda Audio TiRAY": {
        "brand": "Coda Audio",
        "model": "TiRAY",
        "type": "passive",
        "price": "",
        "amount": "each",
        "shape": "toursound",
        "default_measurement": "vendor-v1x",
        "measurements": {
            "vendor-v1x": {
                "origin": "Vendors-Coda Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "high",
                "review_published": "20230308",
                "specifications": {
                    "dispersion": {
                        "horizontal": 100,
                        "vertical": 12,
                    },
                    "sensitivity": 94,
                    "impedance": 8,
                    "SPL": {
                        "peak": 124,
                    },
                    "size": {
                        "height": 155,
                        "width": 404,
                        "depth": 253,
                    },
                    "weight": 9.9,
                },
                "notes": "configuration is for 1 TiRAY and 1 TiLOW (12 inch subwoofer)",
            },
        },
    },
    "CommonSense Audio 5.6": {
        "brand": "CommonSense Audio",
        "model": "5.6",
        "type": "passive",
        "price": "",
        "shape": "floorstanders",
        "default_measurement": "princeton",
        "measurements": {
            "princeton": {
                "origin": "Princeton",
                "format": "princeton",
                "review": "https://www.princeton.edu/3D3A/Directivity.html",
                "review_published": "20151001",
            },
        },
    },
    "CSS Criton 1TD-X DIY": {
        "brand": "CSS",
        "model": "Criton 1TD-X DIY",
        "type": "passive",
        "price": "770",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/css-criton-1td-x-kit-speaker-review.41923/",
                "review_published": "20230211",
            },
        },
    },
    "CSS Criton 3TD-X DIY": {
        "brand": "CSS",
        "model": "Criton 3TD-X DIY",
        "type": "passive",
        "price": "2000",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/css-criton-3td-x-kit-speaker-review.58467/",
                "review_published": "20241113",
                "specifications": {
                    "sensitivity": 87.8,
                    "impedance": 4,
                    "size": {
                        "height": 1054,
                        "width": 216,
                        "depth": 342,
                    },
                    "weight": 31.7,
                },
            },
        },
    },
}
