from . import SpeakerDatabase, gll_data_acquisition_std

note_kef_data = "Data computed by KEF is precise above 300Hz, the on axis is corrected below that. The other curves are interpolated below 300Hz and are not very precise."


speakers_info_k: SpeakerDatabase = {
    "Kali IN-5": {
        "brand": "Kali",
        "model": "IN-5",
        "type": "active",
        "price": "700",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kali_in-5/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/kali-in-5-studio-monitor-review.22487/",
                },
                "review_published": "20210415",
            },
        },
    },
    "Kali IN-8": {
        "brand": "Kali",
        "model": "IN-8",
        "type": "active",
        "price": "760",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kali_in-8v1/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/kali-audio-in-8v1-3-way-studio-monitor-review.24241/#post-818243",
                    "yt": "https://www.youtube.com/watch?v=DNpkizYXbVM",
                },
                "review_published": "20210615",
            },
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/kali-audio-in-8-studio-monitor-review.10897/",
                "review_published": "20200114",
            },
        },
    },
    "Kali IN-8v2": {
        "brand": "Kali",
        "model": "IN-8v2",
        "type": "active",
        "price": "760",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kali_in-8v2",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/kali-audio-in-8v2-second-wave-3-way-studio-monitor-review.24586/",
                    "yt": "https://www.youtube.com/watch?v=DNpkizYXbVM",
                },
                "review_published": "20210615",
            },
        },
    },
    "Kali LP-6": {
        "brand": "Kali",
        "model": "LP-6",
        "type": "active",
        "price": "300",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/kali-lp-6-review-studio-monitor.17978/",
            },
        },
    },
    "Kali LP-6v2": {
        "brand": "Kali",
        "model": "LP-6v2",
        "type": "active",
        "price": "300",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kali_lp-6v2/",
                    "yt": "https://www.youtube.com/watch?v=Wj47W9EP4tQ&t=2s",
                },
                "review_published": "20211025",
            },
        },
    },
    "Kali LP-8": {
        "brand": "Kali",
        "model": "LP-8",
        "type": "active",
        "price": "",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-audioholics",
        "measurements": {
            "misc-audioholics": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://www.audioholics.com/bookshelf-speaker-reviews/kali-audio-lp-8/conclusion",
            },
        },
    },
    "Kali LP-8v2": {
        "brand": "Kali",
        "model": "LP-8v2",
        "type": "active",
        "price": "300",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kali_lp-8v2/",
                },
                "review_published": "20211114",
            },
        },
    },
    "Kali LP-UNF": {
        "brand": "Kali",
        "model": "LP-UNF",
        "type": "active",
        "price": "300",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kali_lp_unf/",
                    "yt": "https://youtu.be/hOkMVbW7Yts",
                },
                "review_published": "20240312",
                "specifications": {
                    "SPL": {
                        "peak": 103,
                    },
                    "size": {
                        "height": 254,
                        "width": 164,
                        "depth": 186,
                    },
                    "weight": 3.2,
                },
            },
        },
    },
    "Kanto ORA": {
        "brand": "Kanto",
        "model": "ORA",
        "type": "active",
        "price": "350",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-audioholics",
        "measurements": {
            "misc-audioholics": {
                "origin": "Misc",
                "format": "rew_text_dump",
                "quality": "low",
                "review": "https://www.audioholics.com/computer-speaker-reviews/kanto-living-ora",
                "notes": "done by James Larson in free air",
                "specifications": {
                    "size": {
                        "height": 254,
                        "width": 227,
                        "depth": 383,
                    },
                    "weight": 1.0,
                },
            },
        },
    },
    "Kanto YU": {
        "brand": "Kanto",
        "model": "YU",
        "type": "active",
        "price": "280",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/kanto-yu-review-pc-speaker.22329/",
                "review_published": "20210409",
            },
        },
    },
    "Kanto YU6": {
        "brand": "Kanto",
        "model": "YU6",
        "type": "active",
        "price": "500",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/kanto-yu6-measurements-powered-monitor.27342/",
                "review_published": "20211016",
            },
        },
    },
    "K ARRAY Dragon KX12": {
        "brand": "K ARRAY",
        "model": "Dragon KX12",
        "type": "passive",
        "price": "1900",
        "shape": "liveportable",
        "amount": "each",
        "default_measurement": "vendor-configuration-onwall",
        "measurements": {
            "vendor-configuration-onwall": {
                "origin": "Vendors-K ARRAY",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221111",
                "quality": "medium",
            },
            "vendor-configuration-krx-1x": {
                "origin": "Vendors-K ARRAY",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221111",
                "quality": "medium",
            },
            "vendor-configuration-krx-2x": {
                "origin": "Vendors-K ARRAY",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221111",
                "quality": "medium",
            },
            "vendor-configuration-krx-3x": {
                "origin": "Vendors-K ARRAY",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221111",
                "quality": "medium",
            },
        },
    },
    "KEF Blade 1 Meta": {
        "brand": "KEF",
        "model": "Blade 1 Meta",
        "type": "passive",
        "price": "35000",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "vendor-v2-20230503",
        "measurements": {
            "vendor-v2-20230503": {
                "origin": "Vendors-KEF",
                "format": "rew_text_dump",
                "review_published": "20230503",
                "notes": note_kef_data,
                "quality": "medium",
                "reviews": {
                    "white_paper": "https://assets.kef.com/documents/reference/KEF_Blade_Ref_Meta_Tech_Paper.pdf",
                },
            },
            "vendor-v1-20220217": {
                "origin": "Vendors-KEF",
                "format": "webplotdigitizer",
                "review_published": "20220217",
                "notes": note_kef_data,
                "quality": "medium",
                "reviews": {
                    "white_paper": "https://assets.kef.com/documents/reference/KEF_Blade_Ref_Meta_Tech_Paper.pdf",
                },
            },
        },
    },
    "KEF Blade 2 Meta": {
        "brand": "KEF",
        "model": "Blade 2 Meta",
        "type": "passive",
        "price": "25000",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_blade2_met#a/",
                    "yt": "https://youtu.be/lh8D7LhlVoQ",
                    "white_paper": "https://assets.kef.com/documents/reference/KEF_Blade#_Ref_Meta_Tech_Paper.pdf",
                    "str": "https://www.stereophile.com/content/kef-blade-two-meta-louds#peaker",
                    "whf": "https://www.whathifi.com/reviews/kef-blade-two-meta",
                    "ssh": "https://www.soundstagehifi.com/index.php/equipment-reviews/9#60-kef-blade-two-loudspeakers",
                },
                "review_published": "20240327",
                "specifications": {
                    "SPL": {
                        "peak": 116,
                    },
                    "sensitivity": 88,
                    "impedance": 3.2,
                    "size": {
                        "height": 1461,
                        "width": 338,
                        "depth": 475,
                    },
                    "weight": 35.3,
                },
            },
            "vendor-v2-20230503": {
                "origin": "Vendors-KEF",
                "format": "rew_text_dump",
                "review_published": "20230503",
                "notes": note_kef_data,
                "quality": "medium",
                "reviews": {
                    "white_paper": "https://assets.kef.com/documents/reference/KEF_Blade_Ref_Meta_Tech_Paper.pdf",
                },
            },
            "vendor-v1-20220217": {
                "origin": "Vendors-KEF",
                "format": "webplotdigitizer",
                "review_published": "20220217",
                "notes": note_kef_data,
                "quality": "medium",
                "reviews": {
                    "white_paper": "https://assets.kef.com/documents/reference/KEF_Blade_Ref_Meta_Tech_Paper.pdf",
                },
            },
        },
    },
    "KEF Ci3160RL-THX": {
        "brand": "KEF",
        "model": "Ci3160RL-THX",
        "type": "passive",
        "price": "1400",
        "amount": "each",
        "shape": "inwall",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/kef_ci3160rl-thx/",
                "review_published": "20220514",
            },
        },
    },
    "KEF CI250RRM-THX": {
        "brand": "KEF",
        "model": "CI250RRM-THX",
        "type": "passive",
        "price": "2500",
        "amount": "each",
        "shape": "inwall",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-KEF",
                "format": "gll_hv_txt",
                "quality": "medium",
                "review_published": "20240527",
                "reviews": {
                    "white_paper": "https://images.salsify.com/image/upload/s--NpCBx-SO--/w9cbdm861tt4vimzda3g.pdf",
                },
                "notes": "The speaker is optimised for being listen to off axis at 30 up to 60 degrees",
            },
        },
    },
    "KEF LS50": {
        "brand": "KEF",
        "model": "LS50",
        "type": "passive",
        "price": "1500",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr-vertical",
        "measurements": {
            "asr-vertical": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/kef-ls50-bookshelf-speaker-review.11144/",
            },
            "asr-horizontal": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/kef-ls50-bookshelf-speaker-review.11144/",
            },
            "princeton": {
                "origin": "Princeton",
                "format": "princeton",
                "symmetry": "horizontal",
                "review": "https://www.princeton.edu/3D3A/Directivity.html",
                "review_published": "20151001",
            },
            "misc-archimago": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "review": "https://archimago.blogspot.com/2020/10/pspinorama-measurements-kef-ls50.html",
                "quality": "low",
            },
        },
    },
    "KEF LS50 Meta": {
        "brand": "KEF",
        "model": "LS50 Meta",
        "type": "passive",
        "price": "1000",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "eac-v1",
        "measurements": {
            "eac-v1": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_ls50_meta/",
                    "yt": "https://youtu.be/RAKKVe6stCs",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/kef-ls50-meta-review-speaker.25574/",
                    "npz": "https://www.audiosciencereview.com/forum/index.php?threads/kef-ls50-meta-spinorama-and-measurements.18353/#post-59879",
                    "tnw": "https://thenextweb.com/news/review-kefs-ls50-meta-upgrades-an-audiophile-fave-to-near-perfection",
                },
                "review_published": "20231221",
                "specifications": {
                    "SPL": {
                        "peak": 106,
                    },
                    "sensitivity": 65,
                    "impedance": 3.5,
                    "size": {
                        "height": 302,
                        "width": 200,
                        "depth": 280,
                    },
                    "weight": 7.8,
                },
            },
            "eac-v1-15-degrees": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_ls50_meta/",
                    "yt": "https://youtu.be/RAKKVe6stCs",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/kef-ls50-meta-review-speaker.25574/",
                    "npz": "https://www.audiosciencereview.com/forum/index.php?threads/kef-ls50-meta-spinorama-and-measurements.18353/#post-59879",
                    "tnw": "https://thenextweb.com/news/review-kefs-ls50-meta-upgrades-an-audiophile-fave-to-near-perfection",
                },
                "review_published": "20231221",
                "specifications": {
                    "SPL": {
                        "peak": 106,
                    },
                    "sensitivity": 65,
                    "impedance": 3.5,
                    "size": {
                        "height": 302,
                        "width": 200,
                        "depth": 280,
                    },
                    "weight": 7.8,
                },
            },
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/kef-ls50-meta-review-speaker.25574/",
                "review_published": "20210807",
            },
            "misc-napilopez": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/kef-ls50-meta-spinorama-and-measurements.18353/#post-598793",
                    "tnw": "https://thenextweb.com/news/review-kefs-ls50-meta-upgrades-an-audiophile-fave-to-near-perfection",
                },
            },
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://speakerdata2034.blogspot.com/2019/03/spinorama-data-kef.html",
            },
            "misc-audioxpress": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "medium",
                "review": "https://audioxpress.com/article/fresh-from-the-bench-kef-ls50-meta-the-measurements",
                "review_published": "20210701",
            },
        },
    },
    "KEF LS50 Wireless II": {
        "brand": "KEF",
        "model": "LS50 Wireless II",
        "type": "active",
        "price": "2800",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_wireless_ii/",
                    "yt": "https://www.youtube.com/watch?v=ryxm7pPyU9c",
                },
                "review_published": "20210907",
            },
            "misc-nuyes": {
                "origin": "Misc",
                "format": "spl_hv_txt",
                "quality": "low",
                "reviews": {
                    "dci": "https://gall.dcinside.com/mgallery/board/view/?id=speakers&no=265278&s_type=search_name&s_keyword=Nuyes&page=2",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/kef-ls50w-ii-measurements.36932/",
                },
                "notes": "Data gated at 5ms so valid above 200Hz/300Hz and smoothed 1/24th of octave",
                "review_published": "20220831",
            },
        },
    },
    "KEF LS60 Wireless": {
        "brand": "KEF",
        "model": "LS60 Wireless",
        "type": "active",
        "price": "7000",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_ls60/",
                    "yt": "",
                    "whf": "https://www.whathifi.com/reviews/kef-ls60-wireless",
                    "sss": "https://www.soundstagesimplifi.com/index.php/equipment-reviews/209-kef-ls60-wireless-active-speaker-system",
                    "hfn": "https://www.hifinews.com/content/kef-ls60-wireless-loudspeaker",
                },
                "review_published": "20231218",
                "specifications": {
                    "SPL": {
                        "peak": 111,
                    },
                    "size": {
                        "height": 1090,
                        "width": 212,
                        "depth": 394,
                    },
                    "weight": 31.2,
                },
            },
            "eac-15-degrees": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_ls60/",
                    "yt": "",
                    "whf": "https://www.whathifi.com/reviews/kef-ls60-wireless",
                    "sss": "https://www.soundstagesimplifi.com/index.php/equipment-reviews/209-kef-ls60-wireless-active-speaker-system",
                    "hfn": "https://www.hifinews.com/content/kef-ls60-wireless-loudspeaker",
                },
                "review_published": "20231218",
                "specifications": {
                    "SPL": {
                        "peak": 111,
                    },
                    "size": {
                        "height": 1090,
                        "width": 212,
                        "depth": 394,
                    },
                    "weight": 31.2,
                },
            },
            "vendor": {
                "origin": "Vendors-KEF",
                "format": "webplotdigitizer",
                "quality": "medium",
                "reviews": {
                    "whf": "https://www.whathifi.com/reviews/kef-ls60-wireless",
                    "sss": "https://www.soundstagesimplifi.com/index.php/equipment-reviews/209-kef-ls60-wireless-active-speaker-system",
                    "hfn": "https://www.hifinews.com/content/kef-ls60-wireless-loudspeaker",
                },
                "review_published": "20220909",
                "specifications": {
                    "SPL": {
                        "peak": 111,
                    },
                    "size": {
                        "height": 1090,
                        "width": 212,
                        "depth": 394,
                    },
                    "weight": 31.2,
                },
            },
        },
    },
    "KEF LSX": {
        "brand": "KEF",
        "model": "LSX",
        "type": "active",
        "price": "1250",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr-vertical",
        "measurements": {
            "asr-vertical": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/kef-lsx-review-wireless-speaker.24802/",
                "review_published": "20210708",
            },
            "asr-horizontal": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/kef-lsx-review-wireless-speaker.24802/",
                "review_published": "20210708",
            },
        },
    },
    "KEF Q100": {
        "brand": "KEF",
        "model": "Q100",
        "type": "passive",
        "price": "600",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/kef-q100-speaker-review.11987/",
            },
        },
    },
    "KEF Q150": {
        "brand": "KEF",
        "model": "Q150",
        "type": "passive",
        "price": "500",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_q150/",
                    "yt": "https://www.youtube.com/watch?v=SiGslBHnK9c&t=3s",
                },
                "review_published": "20220225",
            },
        },
    },
    "KEF Q250": {
        "brand": "KEF",
        "model": "Q250",
        "type": "passive",
        "price": "600",
        "shape": "center",
        "amount": "each",
        "default_measurement": "eac-vertical",
        "measurements": {
            "eac-vertical": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_q250/",
                    "yt": "",
                },
                "review_published": "20220317",
            },
            "eac-horizontal": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_q250/",
                    "yt": "",
                },
                "review_published": "20220317",
            },
        },
    },
    "KEF Q350": {
        "brand": "KEF",
        "model": "Q350",
        "type": "passive",
        "price": "700",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr-vertical",
        "measurements": {
            "asr-vertical": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/kef-q350-speaker-review.13484/",
            },
            "asr-horizontal": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/kef-q350-speaker-review.13484/",
            },
        },
    },
    "KEF Q650C": {
        "brand": "KEF",
        "model": "Q650C",
        "type": "passive",
        "price": "750",
        "shape": "center",
        "amount": "each",
        "default_measurement": "eac-horizontal",
        "measurements": {
            "eac-vertical": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/kef_q650c_center/",
                "review_published": "20220126",
            },
            "eac-horizontal": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/kef_q650c_center/",
                "review_published": "20220126",
            },
        },
    },
    "KEF R2c": {
        "brand": "KEF",
        "model": "R2c",
        "type": "passive",
        "price": "1300",
        "amount": "each",
        "shape": "center",
        "default_measurement": "eac-horizontal",
        "measurements": {
            "eac-horizontal": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_r2c/",
                    "yt": "https://youtu.be/TZTNcEV-TV0",
                    "white_paper": "https://assets.kef.com/documents/rseries/rseries2018-white-paper.pdf",
                },
                "review_published": "20210810",
            },
            "eac-vertical": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_r2c/",
                    "yt": "https://youtu.be/TZTNcEV-TV0",
                    "white_paper": "https://assets.kef.com/documents/rseries/rseries2018-white-paper.pdf",
                },
                "review_published": "20210810",
            },
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "reviews": {
                    "spd2034": "https://speakerdata2034.blogspot.com/2019/03/spinorama-data-kef.html",
                    "white_paper": "https://assets.kef.com/documents/rseries/rseries2018-white-paper.pdf",
                },
            },
        },
    },
    "KEF R2C Meta": {
        "brand": "KEF",
        "model": "R2C Meta",
        "type": "passive",
        "price": "1400",
        "amount": "each",
        "shape": "center",
        "default_measurement": "vendor-v2",
        "measurements": {
            "vendor-v2": {
                "origin": "Vendors-KEF",
                "format": "rew_text_dump",
                "quality": "medium",
                "review_published": "20230503",
                "reviews": {
                    "white_paper": "https://www.audiosciencereview.com/forum/index.php?attachments/kef_r_series_with_mat_whitepaper_compressed-pdf.280101/",
                },
            },
        },
    },
    "KEF R3": {
        "brand": "KEF",
        "model": "R3",
        "type": "passive",
        "price": "1400",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/kef-r3-speaker-review.12021/",
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_r3/",
                    "yt": "https://www.youtube.com/watch?v=Gt96DBlQk8A",
                    "white_paper": "https://assets.kef.com/documents/rseries/rseries2018-white-paper.pdf",
                },
            },
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_r3/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/kef-r3-speaker-review.12021/",
                    "yt": "https://www.youtube.com/watch?v=Gt96DBlQk8A",
                    "white_paper": "https://assets.kef.com/documents/rseries/rseries2018-white-paper.pdf",
                },
                "review_published": "20210314",
            },
            "vendor": {
                "origin": "Vendors-KEF",
                "format": "webplotdigitizer",
                "reviews": {
                    "white_paper": "https://assets.kef.com/documents/rseries/rseries2018-white-paper.pdf",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/kef-r3-speaker-review.12021/",
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_r3/",
                    "yt": "https://www.youtube.com/watch?v=Gt96DBlQk8A",
                },
            },
        },
    },
    "KEF R3 Meta": {
        "brand": "KEF",
        "model": "R3 Meta",
        "type": "passive",
        "price": "2200",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "eac-v1-ported",
        "measurements": {
            "eac-v1-ported": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review_published": "20230705",
                "reviews": {
                    "white_paper": "https://www.audiosciencereview.com/forum/index.php?attachments/kef_r_series_with_mat_whitepaper_compressed-pdf.280101/",
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_r3_meta/",
                    "yt": "https://youtu.be/nbZGj69rI0c",
                    "whi": "https://www.whathifi.com/reviews/kef-r3-meta",
                    "hifi": "https://hifi.de/test/kef-r3-meta-test-137367",
                },
            },
            "eac-v1-sealed": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review_published": "20230705",
                "reviews": {
                    "white_paper": "https://www.audiosciencereview.com/forum/index.php?attachments/kef_r_series_with_mat_whitepaper_compressed-pdf.280101/",
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_r3_meta/",
                    "yt": "https://youtu.be/nbZGj69rI0c",
                    "whi": "https://www.whathifi.com/reviews/kef-r3-meta",
                    "hifi": "https://hifi.de/test/kef-r3-meta-test-137367",
                },
            },
            "eac-v1-ported-10-degrees": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review_published": "20230705",
                "reviews": {
                    "white_paper": "https://www.audiosciencereview.com/forum/index.php?attachments/kef_r_series_with_mat_whitepaper_compressed-pdf.280101/",
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_r3_meta/",
                    "yt": "https://youtu.be/nbZGj69rI0c",
                    "whi": "https://www.whathifi.com/reviews/kef-r3-meta",
                    "hifi": "https://hifi.de/test/kef-r3-meta-test-137367",
                },
            },
            "eac-v1-sealed-10-degrees": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review_published": "20230705",
                "reviews": {
                    "white_paper": "https://www.audiosciencereview.com/forum/index.php?attachments/kef_r_series_with_mat_whitepaper_compressed-pdf.280101/",
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_r3_meta/",
                    "yt": "https://youtu.be/nbZGj69rI0c",
                    "whi": "https://www.whathifi.com/reviews/kef-r3-meta",
                    "hifi": "https://hifi.de/test/kef-r3-meta-test-137367",
                },
            },
            "vendor-v2-20230503": {
                "origin": "Vendors-KEF",
                "format": "rew_text_dump",
                "quality": "medium",
                "review_published": "20230503",
                "reviews": {
                    "white_paper": "https://www.audiosciencereview.com/forum/index.php?attachments/kef_r_series_with_mat_whitepaper_compressed-pdf.280101/",
                },
            },
        },
    },
    "KEF R5": {
        "brand": "KEF",
        "model": "R5",
        "type": "passive",
        "price": "2600",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_r5/",
                    "yt": "https://www.youtube.com/watch?v=6oCN4iawV4g",
                    "white_paper": "https://assets.kef.com/documents/rseries/rseries2018-white-paper.pdf",
                },
                "review_published": "20210915",
            },
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_r5/",
                    "yt": "https://www.youtube.com/watch?v=6oCN4iawV4g",
                    "white_paper": "https://assets.kef.com/documents/rseries/rseries2018-white-paper.pdf",
                },
            },
        },
    },
    "KEF R5 Meta": {
        "brand": "KEF",
        "model": "R5 Meta",
        "type": "passive",
        "price": "3500",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_r5_meta/",
                    "yt": "https://youtu.be/THBJXdZl2qM",
                    "white_paper": "https://www.audiosciencereview.com/forum/index.php?attachments/kef_r_series_with_mat_whitepaper_compressed-pdf.280101/",
                },
                "review_published": "20240206",
                "specifications": {
                    "sensitivity": 87,
                    "impedance": 4,
                    "SPL": {
                        "peak": 110,
                    },
                    "size": {
                        "height": 1025,
                        "width": 175,
                        "depth": 344,
                    },
                    "weight": 24.5,
                },
            },
            "vendor-v2": {
                "origin": "Vendors-KEF",
                "format": "rew_text_dump",
                "quality": "medium",
                "review_published": "20230503",
                "reviews": {
                    "white_paper": "https://www.audiosciencereview.com/forum/index.php?attachments/kef_r_series_with_mat_whitepaper_compressed-pdf.280101/",
                },
            },
        },
    },
    "KEF R6C Meta": {
        "brand": "KEF",
        "model": "R6C Meta",
        "type": "passive",
        "price": "1800",
        "amount": "each",
        "shape": "center",
        "default_measurement": "vendor-v2",
        "measurements": {
            "vendor-v2": {
                "origin": "Vendors-KEF",
                "format": "rew_text_dump",
                "quality": "medium",
                "review_published": "20230503",
                "reviews": {
                    "white_paper": "https://www.audiosciencereview.com/forum/index.php?attachments/kef_r_series_with_mat_whitepaper_compressed-pdf.280101/",
                },
            },
        },
    },
    "KEF R7": {
        "brand": "KEF",
        "model": "R7",
        "type": "passive",
        "price": "3200",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "misc-speakerdata2034",
        "measurements": {
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "reviews": {
                    "white_paper": "https://assets.kef.com/documents/rseries/rseries2018-white-paper.pdf",
                },
            },
        },
    },
    "KEF R7 Meta": {
        "brand": "KEF",
        "model": "R7 Meta",
        "type": "passive",
        "price": "5000",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "vendor-v2",
        "measurements": {
            "vendor-v2": {
                "origin": "Vendors-KEF",
                "format": "rew_text_dump",
                "quality": "medium",
                "reviews": {
                    "white_paper": "https://www.audiosciencereview.com/forum/index.php?attachments/kef_r_series_with_mat_whitepaper_compressed-pdf.280101/",
                },
            },
        },
    },
    "KEF R8a": {
        "brand": "KEF",
        "model": "R8a",
        "type": "passive",
        "price": "1400",
        "amount": "pair",
        "shape": "surround",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_r8a/",
                    "white_paper": "https://assets.kef.com/documents/rseries/rseries2018-white-paper.pdf",
                },
                "review_published": "20210807",
            },
        },
    },
    "KEF R8 Meta": {
        "brand": "KEF",
        "model": "R8 Meta",
        "type": "passive",
        "price": "800",
        "amount": "each",
        "shape": "surround",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/kef-r8-meta-dolby-atmos-speaker-review.44520/",
                },
                "review_published": "20230509",
            },
        },
    },
    "KEF R11": {
        "brand": "KEF",
        "model": "R11",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "misc-speakerdata2034",
        "measurements": {
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "reviews": {
                    "white_paper": "https://assets.kef.com/documents/rseries/rseries2018-white-paper.pdf",
                },
            },
        },
    },
    "KEF R11 Meta": {
        "brand": "KEF",
        "model": "R11 Meta",
        "type": "passive",
        "price": "6500",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/kef-r11-meta-tower-speaker-review.53282/",
                "review_published": "20240326",
                "reviews": {
                    "white_paper": "https://assets.kef.com/pdf_doc/REF/REF-White-Paper-201219-LR.pdf",
                },
            },
            "vendor-v2": {
                "origin": "Vendors-KEF",
                "format": "rew_text_dump",
                "review_published": "20230503",
                "quality": "medium",
                "reviews": {
                    "white_paper": "https://www.audiosciencereview.com/forum/index.php?attachments/kef_r_series_with_mat_whitepaper_compressed-pdf.280101/",
                },
            },
        },
    },
    "KEF Reference 1 Meta": {
        "brand": "KEF",
        "model": "Reference 1 Meta",
        "type": "passive",
        "price": "9000",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac-short-port",
        "measurements": {
            "eac-short-port": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review_published": "20220501",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_reference_1_meta/",
                    "yt": "https://youtu.be/4hyKx9GiB8o",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/kef-reference-1-meta-bookshelf-speaker-review-by-erins-audio-corner.33666/",
                },
            },
            "eac-long-port": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review_published": "20220501",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kef_reference_1_meta/",
                    "yt": "https://youtu.be/4hyKx9GiB8o",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/kef-reference-1-meta-bookshelf-speaker-review-by-erins-audio-corner.33666/",
                },
            },
            "vendor-v2-20230503": {
                "origin": "Vendors-KEF",
                "format": "rew_text_dump",
                "review_published": "20230503",
                "notes": note_kef_data,
                "quality": "medium",
            },
            "vendor-v1-20220217": {
                "origin": "Vendors-KEF",
                "format": "webplotdigitizer",
                "review_published": "20220217",
                "quality": "medium",
            },
        },
    },
    "KEF Reference 2C Meta": {
        "brand": "KEF",
        "model": "Reference 2C Meta",
        "type": "passive",
        "price": "5500",
        "amount": "each",
        "shape": "center",
        "default_measurement": "vendor-v2-20230503",
        "measurements": {
            "vendor-v2-20230503": {
                "origin": "Vendors-KEF",
                "format": "rew_text_dump",
                "review_published": "20230503",
                "notes": note_kef_data,
                "quality": "medium",
            },
            "vendor-v1-20220217": {
                "origin": "Vendors-KEF",
                "format": "webplotdigitizer",
                "quality": "medium",
                "review_published": "20220217",
                "reviews": {
                    "kef": "https://www.shop.us.kef.com/pub/media/reference/KEF_Blade_Ref_Meta_Tech_Paper.pdf",
                },
            },
        },
    },
    "KEF Reference 3 Meta": {
        "brand": "KEF",
        "model": "Reference 3 Meta",
        "type": "passive",
        "price": "13500",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "vendor-v2-20230503",
        "measurements": {
            "vendor-v2-20230503": {
                "origin": "Vendors-KEF",
                "format": "rew_text_dump",
                "review_published": "20230503",
                "notes": note_kef_data,
                "quality": "medium",
            },
            "vendor-v1-20220217": {
                "origin": "Vendors-KEF",
                "format": "webplotdigitizer",
                "quality": "medium",
                "notes": note_kef_data,
                "review_published": "20220217",
            },
        },
    },
    "KEF Reference 4C": {
        "brand": "KEF",
        "model": "Reference 4C",
        "type": "passive",
        "price": "7500",
        "shape": "center",
        "amount": "each",
        "default_measurement": "asr-vertical",
        "measurements": {
            "asr-vertical": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/kef-reference-4c-review-center-speaker.30048/",
                "review_published": "20220118",
                "reviews": {
                    "white_paper": "https://assets.kef.com/pdf_doc/REF/REF-White-Paper-201219-LR.pdf",
                },
            },
            "asr-horizontal": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/kef-reference-4c-review-center-speaker.30048/",
                "review_published": "20220118",
                "reviews": {
                    "white_paper": "https://assets.kef.com/pdf_doc/REF/REF-White-Paper-201219-LR.pdf",
                },
            },
        },
    },
    "KEF Reference 4C Meta": {
        "brand": "KEF",
        "model": "Reference 4C Meta",
        "type": "passive",
        "price": "8000",
        "amount": "each",
        "shape": "center",
        "default_measurement": "vendor-v2-20230503",
        "measurements": {
            "vendor-v2-20230503": {
                "origin": "Vendors-KEF",
                "format": "rew_text_dump",
                "review_published": "20230503",
                "notes": note_kef_data,
                "quality": "medium",
            },
            "vendor-v1-20220217": {
                "origin": "Vendors-KEF",
                "format": "webplotdigitizer",
                "review_published": "20220217",
                "quality": "medium",
            },
        },
    },
    "KEF Reference 5": {
        "brand": "KEF",
        "model": "Reference 5",
        "type": "passive",
        "price": "16800",
        "shape": "floorstanders",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-KEF",
                "format": "webplotdigitizer",
                "quality": "medium",
                "reviews": {
                    "white_paper": "https://assets.kef.com/pdf_doc/REF/REF-White-Paper-201219-LR.pdf",
                },
            },
        },
    },
    "KEF Reference 5 Meta": {
        "brand": "KEF",
        "model": "Reference 5 Meta",
        "type": "passive",
        "price": "20000",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "vendor-v2-20230428",
        "measurements": {
            "vendor-v2-20230428": {
                "origin": "Vendors-KEF",
                "format": "rew_text_dump",
                "quality": "medium",
                "review_published": "20230428",
                "notes": note_kef_data,
            },
            "vendor-v1-20220217": {
                "origin": "Vendors-KEF",
                "format": "webplotdigitizer",
                "quality": "medium",
                "review_published": "20220217",
                "notes": note_kef_data,
            },
        },
    },
    "KEF T101": {
        "brand": "KEF",
        "model": "T101",
        "type": "passive",
        "price": "650",
        "shape": "surround",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/kef-t101-review-thin-speaker.29574/",
                "review_published": "20220103",
            },
        },
    },
    "KEF T301C": {
        "brand": "KEF",
        "model": "T301C",
        "type": "passive",
        "price": "300",
        "shape": "center",
        "amount": "each",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/kef-t301c-review-ultra-thin-speaker.28743/",
                "review_published": "20211205",
            },
        },
    },
    "King's Audio KingSound KS 3001": {
        "brand": "King's Audio",
        "model": "KingSound KS 3001",
        "type": "passive",
        "price": "",
        "shape": "bookshelves",
        "default_measurement": "princeton",
        "measurements": {
            "princeton": {
                "origin": "Princeton",
                "format": "princeton",
                "review": "https://www.princeton.edu/3D3A/Directivity.html",
                "review_published": "20151001",
            },
        },
    },
    "KLH 911B": {
        "brand": "KLH",
        "model": "911B",
        "type": "passive",
        "price": "",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-KLH",
                "format": "rew_text_dump",
            },
        },
    },
    "KLH Model Five": {
        "brand": "KLH",
        "model": "Model Five",
        "type": "passive",
        "price": "2500",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "eac-v1-grilleon",
        "measurements": {
            "eac-v1-grilleon": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "",
                },
                "review_published": "20220730",
                "notes": "Measured with MID setting and with grille on",
            },
        },
    },
    "Kii Audio Three": {
        "brand": "Kii Audio",
        "model": "Three",
        "type": "active",
        "price": "13000",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/kii_three/",
                },
                "review_published": "20211201",
            },
        },
    },
    "Klipsch Forte IV": {
        "brand": "Klipsch",
        "model": "Forte IV",
        "type": "passive",
        "price": "6780",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/klipsch_forte_iv/",
                "review_published": "20211002",
            },
        },
    },
    "Kling Freitag CA 106 Pro": {
        "brand": "Kling Freitag",
        "model": "CA 106 Pro",
        "type": "active",
        "price": "1045",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor-fullrange-pattern-90x60",
        "measurements": {
            "vendor-fullrange-pattern-90x60": {
                "origin": "Vendors-Kling Freitag",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221107",
                "quality": "high",
                "reviews": {
                    "ps": "https://www.professional-system.de/tests/klassiker-in-der-2-generation-kling-freitag-ca-106-pro/",
                },
                "notes": "generated from GLL file provided by Kling Freitag, full range mode",
            },
            "vendor-lowcut-pattern-90x60": {
                "origin": "Vendors-Kling Freitag",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221107",
                "quality": "high",
                "notes": "generated from GLL file provided by Kling Freitag, low cut mode",
            },
            "vendor-passive-pattern-90x60": {
                "origin": "Vendors-Kling Freitag",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221107",
                "quality": "high",
                "notes": "generated from GLL file provided by Kling Freitag, passive mode",
            },
        },
    },
    "Kling Freitag PIA M": {
        "brand": "Kling Freitag",
        "model": "PIA M",
        "type": "active",
        "price": "6780",
        "amount": "pair",
        "shape": "columns",
        "default_measurement": "vendor-bassreflex-wide",
        "measurements": {
            "vendor-bassreflex-narrow": {
                "origin": "Vendors-Kling Freitag",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221018",
                "quality": "high",
                "notes": "generated from GLL file provided by Kling Freitag, configuration bass reflex with narrow mode on",
            },
            "vendor-bassreflex-medium": {
                "origin": "Vendors-Kling Freitag",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221018",
                "quality": "high",
                "notes": "generated from GLL file provided by Kling Freitag, configuration bass reflex with medium mode on",
            },
            "vendor-bassreflex-wide": {
                "origin": "Vendors-Kling Freitag",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221018",
                "quality": "high",
                "notes": "generated from GLL file provided by Kling Freitag, configuration bass reflex with wide mode on",
            },
            "vendor-cardioid-wide": {
                "origin": "Vendors-Kling Freitag",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221018",
                "quality": "high",
                "notes": "generated from GLL file provided by Kling Freitag, configuration cardiod with wide mode on",
            },
            "vendor-cardioid-medium": {
                "origin": "Vendors-Kling Freitag",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221018",
                "quality": "high",
                "notes": "generated from GLL file provided by Kling Freitag, configuration cardiod with medium mode on",
            },
            "vendor-cardioid-narrow": {
                "origin": "Vendors-Kling Freitag",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221018",
                "quality": "high",
                "notes": "generated from GLL file provided by Kling Freitag, configuration cardiod with narrow mode on",
            },
        },
    },
    "Kling Freitag Spectra": {
        "brand": "Kling Freitag",
        "model": "Spectra",
        "type": "active",
        "price": "6780",
        "amount": "each",
        "shape": "toursound",
        "default_measurement": "vendor-wide",
        "measurements": {
            "vendor-wide": {
                "origin": "Vendors-Kling Freitag",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221028",
                "quality": "high",
            },
            "vendor-narrow": {
                "origin": "Vendors-Kling Freitag",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221028",
                "quality": "high",
            },
        },
    },
    "Kling Freitag Sequenza 5B+5W": {
        "brand": "Kling Freitag",
        "model": "Sequenza 5B+5W",
        "type": "active",
        "price": "5000",
        "amount": "each",
        "shape": "toursound",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Kling Freitag",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221027",
                "quality": "medium",
                "parameters": {
                    "mean_min": 50,
                    "mean_max": 500,
                },
            },
        },
    },
    "Klipsch Icon KF-26": {
        "brand": "Klipsch",
        "model": "Icon KF-26",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "misc-speakerdata2034",
        "measurements": {
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://speakerdata2034.blogspot.com/2020/04/various-brands-spinorama-data-from.html",
            },
        },
    },
    "Klipsch R41M": {
        "brand": "Klipsch",
        "model": "R41M",
        "type": "passive",
        "price": "150",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/klipsch-r-41m-bookshelf-speaker-review.11566/",
            },
        },
    },
    "Klipsch Heresy IV": {
        "brand": "Klipsch",
        "model": "Heresy IV",
        "type": "passive",
        "price": "2000",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "eac-v2-20210926",
        "measurements": {
            "eac-v2-20210926": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/klipsch_heresy_iv/",
                },
                "review_published": "20210926",
            },
            "eac-v1-20201105": {
                "origin": "ErinsAudioCorner",
                "format": "webplotdigitizer",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/klipsch_heresy_iv/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/klipsch-heresy-iv-speaker-review.17853/",
                },
                "review_published": "20201105",
            },
        },
    },
    "Klipsch RP-404C II": {
        "brand": "Klipsch",
        "model": "RP-404C II",
        "type": "passive",
        "price": "600",
        "shape": "center",
        "amount": "each",
        "default_measurement": "eac-vertical",
        "measurements": {
            "eac-vertical": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/klipsch_rp_404cii/",
                "review_published": "20220702",
            },
            "eac-horizontal": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/klipsch_rp_404cii/",
                "review_published": "20220702",
            },
        },
    },
    "Klipsch RP-500M": {
        "brand": "Klipsch",
        "model": "RP-500M",
        "type": "passive",
        "price": "400",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/klipsch_rp_500m_i/",
                "review_published": "20220610",
            },
        },
    },
    "Klipsch RP-500C II": {
        "brand": "Klipsch",
        "model": "RP-500C II",
        "type": "passive",
        "price": "500",
        "shape": "center",
        "amount": "each",
        "default_measurement": "eac-vertical",
        "measurements": {
            "eac-vertical": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/klipsch_rp_500cii/",
                "review_published": "20220702",
            },
            "eac-horizontal": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/klipsch_rp_500cii/",
                "review_published": "20220702",
            },
        },
    },
    "Klipsch RP-500M II": {
        "brand": "Klipsch",
        "model": "RP-500M II",
        "type": "passive",
        "price": "600",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/klipsch_rp_500m_ii/",
                "review_published": "20220610",
            },
        },
    },
    "Klipsch RP-504C II": {
        "brand": "Klipsch",
        "model": "RP-504C II",
        "type": "passive",
        "price": "800",
        "shape": "center",
        "amount": "each",
        "default_measurement": "eac-vertical",
        "measurements": {
            "eac-vertical": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/klipsch_rp_504cii/",
                "review_published": "20220702",
            },
            "eac-horizontal": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/klipsch_rp_504cii/",
                "review_published": "20220702",
            },
        },
    },
    "Klipsch RP-600M": {
        "brand": "Klipsch",
        "model": "RP-600M",
        "type": "passive",
        "price": "670",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/klipsch-rp-600m-speaker-review.12138/",
                "review_published": "20200519",
            },
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/klipsch_rp_600m_i/",
                "review_published": "20220522",
            },
        },
    },
    "Klipsch RP-600M II": {
        "brand": "Klipsch",
        "model": "RP-600M II",
        "type": "passive",
        "price": "670",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac-no-grille",
        "measurements": {
            "eac-no-grille": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/klipsch_rp_600m_ii/",
                "review_published": "20220522",
                "notes": "This measurement is without a grille",
            },
            "eac-grille-on": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/klipsch_rp_600m_ii/",
                "review_published": "20220522",
                "notes": "This measurement is with grille on",
            },
        },
    },
    "Klipsch RP-5000F II": {
        "brand": "Klipsch",
        "model": "RP-5000F II",
        "type": "passive",
        "price": "1200",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/klipsch_rp_5000f_ii/",
                    "yt": "https://youtu.be/vmGTy5o5Xgc",
                },
                "review_published": "20220711",
            },
        },
    },
    "Klipsch RP-6000F II": {
        "brand": "Klipsch",
        "model": "RP-6000F II",
        "type": "passive",
        "price": "1500",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/klipsch_rp_6000f_ii/",
                    "yt": "https://youtu.be/vmGTy5o5Xgc",
                },
                "review_published": "20220711",
            },
        },
    },
    "Klipsch RP-8000F II": {
        "brand": "Klipsch",
        "model": "RP-8000F II",
        "type": "passive",
        "price": "1800",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/klipsch_rp_8000f_ii/",
                    "yt": "https://youtu.be/vmGTy5o5Xgc",
                },
                "review_published": "20220711",
            },
        },
    },
    "Klipsch Synergy SB-3 Monitor": {
        "brand": "Klipsch",
        "model": "Synergy SB-3 Monitor",
        "type": "passive",
        "price": "",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Klipsch",
                "format": "rew_text_dump",
                "review": "",
            },
        },
    },
    "Klipsch The Fives": {
        "brand": "Klipsch",
        "model": "The Fives",
        "type": "active",
        "price": "800",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac-v1-20210428",
        "measurements": {
            "eac-v1-20210428": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/klipsch_the_fives/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/klipsch-the-fives-powered-bookshelf-speaker-review.22892/",
                },
                "review_published": "20210428",
                "notes": "Bass cut mode",
            },
        },
    },
    "Klipsch The Three": {
        "brand": "Klipsch",
        "model": "The Three",
        "type": "active",
        "price": "399",
        "shape": "bookshelves",
        "amount": "each",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/klipsch-the-three-review-powered-speaker.23847/",
                "review_published": "20210530",
                "notes": "...performed over 700 measurement which resulted in error rate of less than 1% below about 7 kHz. Above that the error shot way up due to me setting the reference axis to the woofer center, not the tweeter. This severely disadvantaged the NFS system in computing the sound field as the tweeter took over more of the duty. I picked the woofer because I incorrectly assumed this was a mono speaker and dual tweeters were used for some kind of spatial effect...",
                "quality": "medium",
            },
        },
    },
    "Klipsch The Nines": {
        "brand": "Klipsch",
        "model": "The Nines",
        "type": "active",
        "price": "1840",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/klipsch_the_nines/",
                    "yt": "https://youtu.be/PxiUWhIeIeY",
                },
                "review_published": "20230602",
            },
        },
    },
    "KME Sound ICS4": {
        "brand": "KME Sound",
        "model": "ICS4",
        "type": "active",
        "price": "",
        "shape": "liveportable",
        "amount": "each",
        "default_measurement": "vendor-pattern-80x40",
        "measurements": {
            "vendor-pattern-80x40": {
                "origin": "Vendors-KME Sound",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221111",
                "quality": "medium",
            },
        },
    },
    "KME Sound VL15XTL": {
        "brand": "KME Sound",
        "model": "VL15XTL",
        "type": "active",
        "price": "",
        "shape": "liveportable",
        "amount": "each",
        "default_measurement": "vendor-pattern-80x60",
        "measurements": {
            "vendor-pattern-80x60": {
                "origin": "Vendors-KME Sound",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221111",
                "quality": "medium",
            },
        },
    },
    "KRK Systems Classic 5": {
        "brand": "KRK Systems",
        "model": "Classic 5",
        "type": "active",
        "price": "150",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/krk-classic-5-review-studio-monitor.19031/",
            },
        },
    },
    "KRK Systems RoKit 5 G4": {
        "brand": "KRK Systems",
        "model": "RoKit 5 G4",
        "type": "active",
        "price": "300",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/krk-rokit-5-gen-4-review-studio-monitor.20711/",
                "review_published": "20210224",
            },
        },
    },
    "KRK Systems RoKit 6 G2": {
        "brand": "KRK Systems",
        "model": "RoKit 6 G2",
        "type": "active",
        "price": "400",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "princeton",
        "measurements": {
            "princeton": {
                "origin": "Princeton",
                "format": "princeton",
                "symmetry": "horizontal",
                "review": "https://www.princeton.edu/3D3A/Directivity.html",
                "review_published": "20151001",
            },
        },
    },
    "KV2 Audio ES1.0": {
        "brand": "KV2 Audio",
        "model": "ES1.0",
        "type": "active",
        "price": "",
        "shape": "liveportable",
        "amount": "each",
        "default_measurement": "vendor-pattern-90x40",
        "measurements": {
            "vendor-pattern-90x40": {
                "origin": "Vendors-KV2 Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221111",
                "quality": "medium",
            },
        },
    },
    "KV2 Audio ESR212": {
        "brand": "KV2 Audio",
        "model": "ESR212",
        "type": "active",
        "price": "",
        "shape": "liveportable",
        "amount": "each",
        "default_measurement": "vendor-pattern-90x40",
        "measurements": {
            "vendor-pattern-90x40": {
                "origin": "Vendors-KV2 Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221111",
                "quality": "medium",
            },
        },
    },
    "KV2 Audio EX10": {
        "brand": "KV2 Audio",
        "model": "EX10",
        "type": "active",
        "price": "2900",
        "shape": "liveportable",
        "amount": "each",
        "default_measurement": "vendor-pattern-100x80",
        "measurements": {
            "vendor-pattern-100x80": {
                "origin": "Vendors-KV2 Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221111",
                "quality": "medium",
            },
        },
    },
    "KV2 Audio EX12": {
        "brand": "KV2 Audio",
        "model": "EX12",
        "type": "active",
        "price": "3480",
        "shape": "liveportable",
        "amount": "each",
        "default_measurement": "vendor-pattern-80x40",
        "measurements": {
            "vendor-pattern-80x40": {
                "origin": "Vendors-KV2 Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221111",
                "quality": "medium",
            },
        },
    },
    "KV2 Audio EX15": {
        "brand": "KV2 Audio",
        "model": "EX15",
        "type": "active",
        "price": "6000",
        "shape": "liveportable",
        "amount": "each",
        "default_measurement": "vendor-pattern-80x60",
        "measurements": {
            "vendor-pattern-80x60": {
                "origin": "Vendors-KV2 Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "review_published": "20221111",
                "quality": "medium",
            },
        },
    },
}
