# extra speaker info
speakers_info = {
    'Adam S2V': {
        'brand': 'Adam',
        'model': 'S2V',
        'type': 'active',
        'price': '3500',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement' : 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/adam-s2v-studio-monitor-review.11455',
            },
        },
    },
    'Adam T5V': {
        'brand': 'Adam',
        'model': 'T5V',
        'type': 'active',
        'price': '400',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement' : 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/adam-t5v-review-studio-monitor.18122/'.
            },
        },
    },
        'Adam T8V': {
        'brand': 'Adam',
        'model': 'T8V',
        'type': 'active',
        'price': '600',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement' : 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/adam-t8v-studio-monitor-review.17118/',
            },
        },
    },
    'Apple Homepod': {
        'brand': 'Apple',
        'model': 'Homepod',
        'type': 'active',
        'price': '500',
        'shape': 'bookshelves',
        'amount': 'single',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-Apple',
                'format': 'webplotdigitizer',
            },
        },
    },
    'Ascend Acoustics CBM-170 SE': {
        'brand': 'Ascend Acoustics',
        'model': 'CBM-170 SE',
        'type': 'passive',
        'shape': 'bookshelves',
        'price': '400',
        'amount': 'pair',
        'default_measurement' : 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/ascend-cbm-170-se-speaker-review.11839',
            },
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
            },
        },
    },
    'Ascend Acoustics CMT-340': {
        'brand': 'Ascend Acoustics',
        'model': 'CMT-340',
        'type': 'passive',
        'shape': 'center',
        'price': '300',
        'amount': 'each',
        'default_measurement' : 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/ascend-cmt-340-se-center-channel-speaker-review.11797/#post-340461',
            },
        },
    },
    'Ascend Acoustics Horizon Center': {
        'brand': 'Ascend Acoustics',
        'model': 'Horizon Center',
        'type': 'passive',
        'shape': 'center',
        'price': '1490',
        'amount': 'each',
        'default_measurement' : 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/ascend-acoustics-horizon-center-speaker-review.15199/',
            },
        },
    },
    'Ascend Acoustics Luna Mini-Monitor': {
        'brand': 'Ascend Acoustics',
        'model': 'Luna Mini-Monitor',
        'type': 'passive',
        'shape': 'bookshelves',
        'price': '1150',
        'amount': 'pair',
        'default_measurement' : 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/ascend-sierra-luna-mini-monitor-review.17181/#post-556036',
            },
        },
    },
    'Ascend Acoustics Luna Duo': {
        'brand': 'Ascend Acoustics',
        'model': 'Luna Duo',
        'type': 'passive',
        'shape': 'center',
        'price': '800',
        'amount': 'each',
        'default_measurement' : 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/ascend-sierra-luna-duo-center-main-speaker-review.17259/',
            },
        },
    },
    'Ascend Acoustics Sierra 2': {
        'brand': 'Ascend Acoustics',
        'model': 'Sierra 2',
        'type': 'passive',
        'shape': 'bookshelves',
        'price': '1500',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/ascend-sierra-2-speaker-review.11813/#post-341009',
            },
        },
    },
    'ATC SCM19 v1': {
        'brand': 'ATC',
        'model': 'SCM19 v1',
        'type': 'passive',
        'price': '4000',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/atc-scm19-bookshelf-speaker-review.14519/',
            },
        },
    },
    'Audioengine A5+ Powered': {
        'brand': 'Audioengine',
        'model': 'A5+ Powered',
        'type': 'active',
        'shape': 'bookshelves',
        'price': '400',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/audioengine-a5-powered-speaker-review.13803/',
            },
        },
    },
    'Avantgarde Acoustic Solo': {
        'brand': 'Avantgarde Acoustic',
        'model': 'Solo',
        'type': 'passive',
        'shape': 'floorstanders',
        'price': '7000',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
            },
        },
    },
    'Behringer B2030p': {
        'brand': 'Behringer',
        'model': 'B2030p',
        'type': 'active',
        'shape': 'bookshelves',
        'price': '200',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/behringer-b2030p-studio-monitor-review.14719', 
            },
        },
    },
    'Buchardt Audio S400': {
        'brand': 'Buchardt Audio',
        'model': 'S400',
        'type': 'passive',
        'shape': 'bookshelves',
        'price': '1800',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/buchardt-s400-speaker-review.12844/',
                'format': 'klippel',
            },
            'vendor' : {
                'origin': 'Vendors-Buchardt Audio',
                'website': 'https://www.buchardtaudio.com',
                'format': 'webplotdigitizer',
            },
        },
    },
    'BIC America Venturi DV62si': {
        'brand': 'BIC America',
        'model': 'Venturi DV62si',
        'type': 'passive',
        'shape': 'bookshelves',
        'price': '',
        'default_measurement' : 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/bic-america-dv62si-bookshelf-speaker-review.14918/',
            },
            'vendor': {
                'origin': 'Vendors-BIC America',
                'website': 'https://www.bicamerica.com',
                'format': 'rewstextdump',
            },
        },
    },
    'Bose 301 Series IV': {
        'brand': 'Bose',
        'model': '301 Series IV',
        'type': 'passive',
        'shape': 'bookshelves',
        'price': '',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-Bose',
                'website': 'https://www.bose.com',
                'format': 'rewstextdump',
            },
        },
    },
    'Bose 141': {
        'brand': 'Bose',
        'model': '141',
        'type': 'passive',
        'shape': 'bookshelves',
        'price': '',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-Bose',
                'website': 'https://www.bose.com',
                'format': 'rewstextdump',
            },
        },
    },
    'Bose 901 Series V': {
        'brand': 'Bose',
        'model': '901 Series V',
        'type': 'active',
        'shape': 'bookshelves',
        'price': '',
        'default_measurement' : 'eac-noeq',
        'measurements': {
            'eac-noeq': {
                'origin': 'ErinsAudioCorner',
                'format': 'splHVtxt',
                'review': 'https://www.erinsaudiocorner.com/loudspeakers/bose_901_series_v/',
            },
            'eac-eq-neutral': {
                'origin': 'ErinsAudioCorner',
                'format': 'splHVtxt',
                'review': 'https://www.erinsaudiocorner.com/loudspeakers/bose_901_series_v/',
            },
            'eac-eq-v3': {
                'origin': 'ErinsAudioCorner',
                'format': 'splHVtxt',
                'review': 'https://www.erinsaudiocorner.com/loudspeakers/bose_901_series_v/',
            },
        },
    },
    'Boston Acoustics A 25': {
        'brand': 'Boston Acoustics',
        'model': 'A 25',
        'type': 'passive',
        'shape': 'bookshelves',
        'price': '180',
        'default_measurement' : 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/boston-acoustics-a-25-speaker-review.17625/',
            },
        },
    },
    'Bowers & Wilkins 802N': {
        'brand': 'Bowers & Wilkins',
        'model': '802N',
        'type': 'passive',
        'shape': 'floorstanders',
        'price': '',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-Bowers & Wilkins',
                'format': 'webplotdigitizer',
            },
        },
    },
    'Bowers & Wilkins 805S': {
        'brand': 'Bowers & Wilkins',
        'model': '805S',
        'type': 'passive',
        'shape': 'bookshelves',
        'price': '2500',
        'default_measurement' : 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/bowers-wilkins-805s-bookshelf-speaker-review.16523/',
            },
        },
    },
    'Cambridge Soundworks Model Six': {
        'brand': 'Cambridge Soundworks',
        'model': 'Model Six',
        'type': 'passive',
        'shape': 'bookshelves',
        'price': '',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-Cambridge Soundworks',
                'website': 'https://en.wikipedia.org/wiki/Cambridge_SoundWorks',
                'format': 'rewstextdump',
            },
        },
    },
    'Canon S-50': {
        'brand': 'Canon',
        'model': 'S-50',
        'type': 'passive',
        'shape': 'omnidirectional',
        'price': '300',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/canon-s-50-wide-directivity-speaker-review.13982/'
            },
        },
    },
    'Carmody S2000 DIY Speaker Kit': {
        'brand': 'Carmody',
        'model': 'S2000 DIY Speaker Kit',
        'type': 'passive',
        'shape': 'bookshelves',
        'price': '240',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/carmody-s2000-diy-speaker-kit-reivew.17507/',
            },
        },
    },
    'Celuaris Purify SPK5 prototype': {
        'brand': 'Celuaris',
        'model': 'Purify SPK5 prototype',
        'type': 'passive',
        'price': '2000',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/purifi-spk5-speaker-review-prototype.17806/',
            },
        },
    },
    'CommonSense Audio 5.6': {
        'brand': 'CommonSense Audio',
        'model': '5.6',
        'type': 'passive',
        'price': '',
        'shape': 'floorstanders',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
             },
        },
    },
    'Dayton Audio B652-AIR': {
        'brand': 'Dayton Audio',
        'model': 'B652-AIR',
        'type': 'passive',
        'price': '70',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/dayton-audio-b652-air-speaker-review.11410/',
            },
        },
    },
    'Definitive Technology Demand D11': {
        'brand': 'Definitive Technology',
        'model': 'Demand D11',
        'type': 'passive',
        'price': '1200',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/definitive-demand-d11-speaker-review.15581/',
            },
        },
    },
    'Dennis Murphy Affordable Accuracy Monitor': {
        'brand': 'Dennis Murphy',
        'model': 'Affordable Accuracy Monitor',
        'type': 'passive',
        'price': '',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/affordable-accuracy-monitor-review.13624/',
            },
        },
    },
    'Diapason Emera': {
        'brand': 'Diapason',
        'model': 'Emera',
        'type': 'passive',
        'price': '1000',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/diapason-emera-italian-speaker-review.16193/',
            },
        },
    },
    'Philharmonic BMR': {
        'brand': 'Philharmonic',
        'model': 'BMR',
        'type': 'passive',
        'price': '2400',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'eac',
        'measurements': {
            'eac': {
                'origin': 'ErinsAudioCorner',
                'format': 'splHVtxt',
                'review': 'https://www.erinsaudiocorner.com/loudspeakers/philharmonic_bmr/',
            },
        },
    },
    'Definitive Technology ProMonitor 1000': {
        'brand': 'Definitive Technology',
        'model': 'ProMonitor 1000',
        'type': 'passive',
        'price': '400',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/definitive-technology-promonitor-1000-speaker-review.14220/',
            },
        },
    },
    'Dynaudio LYD 5': {
        'brand': 'Dynaudio',
        'model': 'LYD 5',
        'type': 'active',
        'price': '900',
        'shape': 'bookshelves',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/dynaudio-lyd-5-studio-monitor-review.15963/',
             },
        },
    },
    'Dynaudio Excite X14': {
        'brand': 'Dynaudio',
        'model': 'Excite X14',
        'type': 'passive',
        'price': '1500',
        'shape': 'bookshelves',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/dynaudio-x14-speaker-review.17569/',
             },
        },
    },
    'Dynaudio Xeo 3': {
        'brand': 'Dynaudio',
        'model': 'Xeo 3',
        'type': 'passive',
        'price': '',
        'shape': 'bookshelves',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
             },
        },
    },
    'Edifier R1280T': {
        'brand': 'Edifier',
        'model': 'R1280T',
        'type': 'active',
        'price': '100',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/edifier-r1280t-powered-speaker-review.16112/',
            },
        },
    },
    'Elac Adante AS-61': {
        'brand': 'Elac',
        'model': 'Adante AS-61',
        'type': 'passive',
        'price': '1500',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/elac-adante-as-61-speaker-review.11507/#post-329527',
            },
        },
    },
    'Elac Debut Reference DBR-62': {
        'brand': 'Elac',
        'model': 'Debut Reference DBR-62',
        'type': 'passive',
        'price': '600',
        'shape': 'bookshelves',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/elac-debut-reference-dbr-62-speaker-review.12232/#post-357719',
            },
        },
    },
    'Elac Debut 2.0 B6.2': {
        'brand': 'Elac',
        'model': 'Debut 2.0 B6.2',
        'type': 'passive',
        'price': '245',
        'shape': 'bookshelves',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/elac-debut-2-0-b6-2-speaker-review.14272/',
            },
        },
    },
    'Elac BS U5 Slim': {
        'brand': 'Elac',
        'model': 'BS U5 Slim',
        'type': 'passive',
        'price': '',
        'shape': 'bookshelves',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/elac-bs-u5-slim-3-way-coaxial-speaker-review.13735/',
            },
        },
    },
    'Emotiva Airmotive 6s': {
        'brand': 'Emotiva',
        'model': 'Airmotive 6s',
        'type': 'passive',
        'price': '600',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/emotiva-airmotiv-6s-powered-speaker-review.11185/',
            },
        },
    },
    'Essence Electrostatic Model 1600': {
        'brand': 'Essence Electrostatic',
        'model': 'Model 1600',
        'type': 'passive',
        'price': '',
        'shape': 'floorstanders',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
                'review': '',
            },
        },
    },
    'Fisher STE-720': {
        'brand': 'Fisher',
        'model': 'STE-720',
        'type': 'passive',
        'price': '',
        'shape': 'bookshelves',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
             },
        },
    },
    'Fluance HFS Signature': {
        'brand': 'Fluance',
        'model': 'HFS Signature',
        'type': 'passive',
        'price': '170',
        'shape': 'bookshelves',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/fluance-signature-bookshelf-speaker-review.16337/',
             },
        },
    },
    'Focal Aria 906': {
        'brand': 'Focal',
        'model': 'Aria 906',
        'type': 'passive',
        'price': '450',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/focal-aria-906-speaker-review.14085/',
            },
        },
    },
    'Focal Chorus OD 706 V': {
        'brand': 'Focal',
        'model': 'Chorus OD 706 V',
        'type': 'passive',
        'price': '600',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/focal-chorus-od-706-v-outdoor-speaker-review.16561/',
            },
        },
    },
    'Fostex PM03': {
        'brand': 'Fostex',
        'model': 'PM03',

        'type': 'active',
        'price': '150',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/fostex-pm-03-active-speaker-review.12517/',
            },
        },
    },
    'Gainphile R16': {
        'brand': 'Gainphile',
        'model': 'R16',
        'type': 'passive',
        'price': '',
        'shape': 'floorstanders',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
             },
        },
    },
    'GedLee Nathan': {
        'brand': 'GedLee',
        'model': 'Nathan',
        'type': 'passive',
        'price': '',
        'shape': 'floorstanders',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
             },
        },
    },
    'Genelec 1032A': {
        'brand': 'Genelec',
        'model': '1032A',
        'type': 'active',
        'price': '',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'misc',
        'measurements': {
            'misc': {
                'origin': 'Misc',
                'format': 'rewstextdump',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/genelec-1032a-measurements-including-spinorama.17491/',
            },
        },
    },
    'Genelec 8010A': {
        'brand': 'Genelec',
        'model': '8010A',
        'type': 'active',
        'price': '600',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/genelec-8010a-powered-studio-monitor-review.16866/',
            },
        },
    },
    'Genelec 8030A': {
        'brand': 'Genelec',
        'model': '8030A',
        'type': 'active',
        'shape': 'bookshelves',
        'price': '',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
             },
        },
    },
    'Genelec 8030C': {
        'brand': 'Genelec',
        'model': '8030C',
        'type': 'active',
        'price': '1000',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/genelec-8030c-studio-monitor-review.14795/',
            },
        },
    },
    'Genelec 8351A': {
        'brand': 'Genelec',
        'model': '8351A',
        'type': 'active',
        'price': '5700',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
             },
        },
    },
    'Genelec 8341A': {
        'brand': 'Genelec',
        'model': '8341A',
        'type': 'active',
        'price': '4500',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/genelec-8341a-sam%E2%84%A2-studio-monitor-review.11652/#post-335087',
            },
        },
    },
    'Genelec G2': {
        'brand': 'Genelec',
        'model': 'G2',
        'type': 'active',
        'price': '',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'misc',
        'measurements': {
            'misc': {
                'origin': 'Misc',
                'format': 'rewstextdump',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/genelec-g2-8020-measurements.18076/#post-588571',
            },
        },
    },
    'Gradient Helsinki 1.5': {
        'brand': 'Gradient',
        'model': 'Helsinki 1.5',
        'shape': 'floorstanders',
        'type': 'passive',
        'price': '',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
             },
        },
    },
    'GGNTKT M1': {
        'brand': 'GGNTKT',
        'model': 'M1',
        'shape': 'bookshelves',
        'type': 'active',
        'price': '',
        'default_measurement': 'vendor-v2-202009-monopole',
        'measurements': {
            'vendor-v2-202009-monopole': {
                'origin': 'Vendors-GGNTKT',
                'format': 'webplotdigitizer',
                'website': 'https://ggntkt.de/en/model-m1',
             },
            'vendor-v1-202008': {
                'origin': 'Vendors-GGNTKT',
                'format': 'webplotdigitizer',
                'website': 'https://ggntkt.de/en/model-m1',
             },
        },
    },
    'GR Research X-LS Encore Kit': {
        'brand': 'GR Research',
        'model': 'X-LS Encore Kit',
        'shape': 'bookshelves',
        'type': 'passive',
        'price': '500',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/gr-research-x-ls-encore-kit-speaker-review.14957/',
             },
        },
    },
    'Harbeth Monitor 30.0': {
        'brand': 'Harbeth',
        'model': 'Monitor 30.0',
        'type': 'passive',
        'price': '3200',
        'shape': 'floorstanders',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/harbeth-monitor-30-speaker-review.11108/',
            },
        },
    },
    'Hivi 3.1A DIY': {
        'brand': 'Hivi',
        'model': '3.1A DIY',
        'type': 'passive',
        'price': '300',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/hivi-3-1a-diy-speaker-with-sehlin-mod-review.15802/',
            },
        },
    },
    'iKey-Audio M-808V2': {
        'brand': 'iKey-Audio',
        'model': 'M-808V2',
        'type': 'passive',
        'shape': 'bookshelves',
        'price': '',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
             },
        },
    },
    'Infinity R152': {
        'brand': 'Infinity',
        'model': 'R152',
        'type': 'passive',
        'price': '350',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-Infinity',
                'website': 'www.infinityspeakers.com',
                'format': 'webplotdigitizer',
            },
        },
    },
    'Infinity R253': {
        'brand': 'Infinity',
        'model': 'R253',
        'type': 'passive',
        'price': '200',
        'shape': 'bookshelves',
        'amount': 'floorstanders',
        'default_measurement' : 'asr-v2-20201202',
        'measurements': {
            'asr-v1-20201126': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/infinity-reference-253-review-speaker.17923/'
            },
            'asr-v2-202012026': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/infinity-reference-253-review-speaker.17923/'
            },
        },
    },
    'Infinity Entra One': {
        'brand': 'Infinity',
        'model': 'Entra One',
        'type': 'passive',
        'price': '',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-Infinity',
                'website': 'www.infinityspeakers.com',
                'format': 'rewstextdump',
            },
        },
    },
    'Infinity Interlude IL10': {
        'brand': 'Infinity',
        'model': 'Interlude IL10',
        'type': 'passive',
        'price': '',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/research-project-infinity-il10-speaker-review-measurements.14310/',
            },
            'vendor': {
                'origin': 'Vendors-Infinity',
                'website': 'www.infinityspeakers.com',
                'format': 'rewstextdump',
            },
        },
    },
    'Infinity R162': {
        'brand': 'Infinity',
        'model': 'R162',
        'type': 'passive',
        'price': '540',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/infinity-r162-bookshelf-speaker-review.12333/',
            },
        },
    },
    'Infinity RC263': {
        'brand': 'Infinity',
        'model': 'RC263',
        'type': 'passive',
        'amount': 'each',
        'shape': 'center',
        'price': '500',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/infinity-rc263-center-speaker-review.12442/',
            },
        },
    },
    'JansZen Loudspeaker zA1.1': {
        'brand': 'JansZen Loudspeaker',
        'model': 'zA1.1',
        'type': 'passive',
        'price': '',
        'shape': 'floorstanders',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
             },
        },
    },
    'JansZen Loudspeaker zA2.1': {
        'brand': 'JansZen Loudspeaker',
        'model': 'zA2.1',
        'type': 'passive',
        'price': '',
        'shape': 'floorstanders',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
             },
        },
    },
    'JBL Control 1 Pro': {
        'brand': 'JBL',
        'model': 'Control 1 Pro',
        'type': 'active',
        'price': '164',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/jbl-305p-mkii-and-control-1-pro-monitors-review.10811/',
            },
        },
    },
    'JBL 104': {
        'brand': 'JBL',
        'model': '104',
        'type': 'passive',
        'price': '130',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/jbl-one-series-104-powered-monitor-review.11076/',
            },
        },
    },
    'JBL 705i': {
        'brand': 'JBL',
        'model': '705i',
        'type': 'passive',
        'price': '1500',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-JBL',
                'format': 'webplotdigitizer',
                'review': '',
            },
        },
    },
    'JBL 705P': {
        'brand': 'JBL',
        'model': '705P',
        'type': 'active',
        'price': '2000',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/jbl-705p-studio-monitor-review.11944/',
            },
        },
    },
    'JBL 305P Mark ii': {
        'brand': 'JBL',
        'model': '305P Mark ii',
        'type': 'active',
        'price': '300',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/jbl-305p-mkii-and-control-1-pro-monitors-review.10811/',
            },
        },
    },
    'JBL 308P Mark ii': {
        'brand': 'JBL',
        'model': '308P Mark ii',
        'type': 'active',
        'price': '500',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/jbl-308p-mkii-studio-monitor-review.17338/',
            },
        },
    },
    'JBL 4319': {
        'brand': 'JBL',
        'model': '4319',
        'type': 'passive',
        'price': '8400',
        'shape': 'floorstanders',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/jbl-4319-studio-monitor-review.12986/',
            },
        },
    },
    'JBL 4367': {
        'brand': 'JBL',
        'model': '4367',
        'type': 'passive',
        'price': '8500',
        'shape': 'floorstanders',
        'amount': 'pair',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-JBL',
                'website': 'www.jbl.com',
                'format': 'webplotdigitizer',
            },
        },
    },
    'JBL HDI-1600': {
        'brand': 'JBL',
        'model': 'HDI-1600',
        'type': 'passive',
        'price': '1800',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/jbl-hdi-1600-speaker-review.12477/',
            },
        },
    },
    'JBL HDI-3600': {
        'brand': 'JBL',
        'model': 'HDI-3600',
        'type': 'passive',
        'price': '3800',
        'shape': 'floorstanders',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/jbl-hdi-3600-speaker-review.13027/',
            },
        },
    },
    'JBL M2': {
        'brand': 'JBL',
        'model': 'M2',
        'type': 'active',
        'price': '20000',
        'shape': 'floorstanders',
        'amount': 'pair',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-JBL',
                'website': 'www.jbl.com',
                'format': 'webplotdigitizer',
            },
        },
    },
    'JBL Northridge Series N28': {
        'brand': 'JBL',
        'model': 'Northridge Series N28',
        'type': 'passive',
        'price': '',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-JBL',
                'website': 'www.jbl.com',
                'format': 'rewstextdump',
            },
        },
    },
    'JBL PRX635': {
        'brand': 'JBL',
        'model': 'PRX635',
        'type': 'passive',
        'price': '2540',
        'shape': 'floorstanders',
        'amount': 'pair',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
             },
        },
    },
    'JBL Studio 530': {
        'brand': 'JBL',
        'model': 'Studio 530',
        'type': 'passive',
        'price': '600',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/jbl-studio-530-speaker-review.12298/',
            },
        },
    },
    'JBL Studio Series S26': {
        'brand': 'JBL',
        'model': 'Studio Series S26',
        'type': 'passive',
        'price': '',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-JBL',
                'website': 'www.jbl.com',
                'format': 'rewstextdump',
            },
        },
    },
    'JBL XPL90': {
        'brand': 'JBL',
        'model': 'XPL90',
        'type': 'passive',
        'price': '700',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/jbl-xpl90-speaker-review.13449/',
            },
        },
    },
    'JTR Noesis 212rt': {
        'brand': 'JTR',
        'model': 'Noesis 212rt',
        'type': 'passive',
        'price': '5600',
        'shape': 'floorstanders',
        'amount': 'pair',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-JTR',
                'website': 'https://www.jtrspeakers.com',
                'format': 'webplotdigitizer',
            },
        },
    },
    'Kali IN-8': {
        'brand': 'Kali',
        'model': 'IN-8',
        'type': 'active',
        'price': '760',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/kali-audio-in-8-studio-monitor-review.10897/',
            },
        },
    },
    'Kali LP-6': {
        'brand': 'Kali',
        'model': 'LP-6',
        'type': 'active',
        'price': '300',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/kali-lp-6-review-studio-monitor.17978/',
            },
        },
    },
    'KEF Q100': {
        'brand': 'KEF',
        'model': 'Q100',
        'type': 'passive',
        'price': '600',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/kef-q100-speaker-review.11987/',
            },
        },
    },
    'KEF Q350': {
        'brand': 'KEF',
        'model': 'Q350',
        'type': 'passive',
        'price': '700',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/kef-q350-speaker-review.13484/',
            },
        },
    },
    'KEF R3': {
        'brand': 'KEF',
        'model': 'R3',
        'type': 'passive',
        'price': '2000',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': '',
                },
            'vendor': {
                'origin': 'Vendors-KEF',
                'format': 'webplotdigitizer',
                'review': '',
            },
        },
    },
    'KEF LS50': {
        'brand': 'KEF',
        'model': 'LS50',
        'type': 'passive',
        'price': '1500',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/kef-ls50-bookshelf-speaker-review.11144/',
            },
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
            },
        },
    },
    'KEF Reference 5': {
        'brand': 'KEF',
        'model': 'Reference 5',
        'type': 'passive',
        'price': '16800',
        'shape': 'floorstanders',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-KEF',
                'website': 'www.kef.com',
                'format': 'webplotdigitizer',
            },
        },
    },
    'King\'s Audio KingSound KS 3001': {
        'brand': 'King\'s Audio',
        'model': 'KingSound KS 3001',
        'type': 'passive',
        'price': '',
        'shape': 'bookshelves',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
             },
        },
    },
    'KLH 911B': {
        'brand': 'KLH',
        'model': '911B',
        'type': 'passive',
        'price': '',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-KLH',
                'website': 'www.klh.com',
                'format': 'rewstextdump',
            },
        },
    },
    'Klipsch R41M': {
        'brand': 'Klipsch',
        'model': 'R41M',
        'type': 'passive',
        'price': '150',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/klipsch-r-41m-bookshelf-speaker-review.11566/',
            },
        },
    },
    'Klipsch RP-600M': {
        'brand': 'Klipsch',
        'model': 'RP-600M',
        'type': 'passive',
        'price': '670',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/klipsch-rp-600m-speaker-review.12138/',
            },
        },
    },
    'Klipsch Synergy SB-3 Monitor': {
        'brand': 'Klipsch',
        'model': 'Synergy SB-3 Monitor',
        'type': 'passive',
        'price': '',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-Klipsch',
                'format': 'rewstextdump',
                'review': '',
            },
        },
    },
    'KRK Systems RoKit 6 G2': {
        'brand': 'KRK Systems',
        'model': 'RoKit 6 G2',
        'type': 'active',
        'price': '400',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
             },
        },
    },
    'Manger Sidekick': {
        'brand': 'Manger',
        'model': 'Sidekick',
        'type': 'passive',
        'shape': 'surround',
        'price': '',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
             },
        },
    },
    'Magnepan LRS': {
        'brand': 'Magnepan',
        'model': 'LRS',
        'type': 'passive',
        'shape': 'floorstanders',
        'price': '650',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/magnepan-lrs-speaker-review.16068/',
             },
        },
    },
    'Magico A3': {
        'brand': 'Magico',
        'model': 'A3',
        'type': 'passive',
        'price': '12300',
        'shape': 'floorstanders',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-Magico',
                'format': 'webplotdigitizer',
            },
        },
    },
    'Mesanovic RTM10': {
        'brand': 'Mesanovic',
        'model': 'RTM10',
        'type': 'active',
        'price': '7500',
        'shape': 'floorstanders',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-Mesanovic',
                'format': 'rewstextdump',
            },
        },
    },
    'Micca RB42': {
        'brand': 'Micca',
        'model': 'RB42',
        'type': 'passive',
        'price': '150',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/micca-rb42-bookshelf-speaker-review.11267/',
            },
        },
    },
    'Neumann KH 80': {
        'brand': 'Neumann',
        'model': 'KH 80',
        'type': 'active',
        'price': '1000',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr-v3-20200711',
        'measurements': {
            # review is here but I do not find the data
            #'asr-v1-20200120' : {
            #    'origin': 'ASR',
            #    'format': 'klippel',
            #    'review': 'https://www.audiosciencereview.com/forum/index.php?threads/neumann-kh-80-dsp-monitor-review.11018/',
            #},
            # that's the working sample
            'asr-v2-20200208': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/neumann-kh-80-dsp-speaker-measurements-take-two.11323/',
            },
            # 3rd measurement later
            'asr-v3-20200711' : {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/neumann-kh80-dsp-monitor-measurements-3.14637/',
            },
        },
    },
    'Neumann KH 310A': {
        'brand': 'Neumann',
        'model': 'KH 310A',
        'type': 'active',
        'price': '4400',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/neumann-kh-310a-review-powered-monitor.17723/',
            },
        },
    },
    'NHT Pro M-00': {
        'brand': 'NHT',
        'model': 'Pro M-00',
        'type': 'active',
        'price': '500',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/nht-pro-m-00-powered-monitor-review.10859/',
            },
        },
    },
    'NHT SB2': {
        'brand': 'NHT',
        'model': 'SB2',
        'type': 'active',
        'price': '400',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/nht-sb2-speaker-review.13273/',
            },
        },
    },
    'Ocean Way HR5': {
        'brand': 'Ocean Way',
        'model': 'HR5',
        'type': 'active',
        'price': '2800',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/ocean-way-hr5-studio-monitor-review.13925',
            },
        },
    },
    'Paradigm Monitor SE Atom': {
        'brand': 'Paradigm',
        'model': 'Monitor SE Atom',
        'type': 'passive',
        'price': '239',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/paradigm-monitor-se-atom-speaker-review.17837/',
            },
        },
    },
    'Part Express DIY C-Note': {
        'brand': 'Part Express',
        'model': 'DIY C-Note',
        'type': 'passive',
        'price': '100',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': '',
            },
        },
    },
    'Pioneer S-DF3-K': {
        'brand': 'Pioneer',
        'model': 'S-DF3-K',
        'type': 'passive',
        'price': '',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-Pioneer',
                'format': 'rewstextdump',
                'review': '',
            },
        },
    },
    'Pioneer SP-BS22-LR': {
        'brand': 'Pioneer',
        'model': 'SP-BS22-LR',
        'type': 'passive',
        'price': '160',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/pioneer-sp-bs22-lr-bookshelf-speaker-review.11303/',
            },
        },
    },
    'Pioneer SP-EBS73-LR': {
        'brand': 'Pioneer',
        'model': 'SP-EBS73-LR',
        'type': 'passive',
        'price': '750',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/pioneer-elite-sp-ebs73-lr-atmos-speaker-review.12163/',
            },
        },
    },
    'Pioneer SP-EC73': {
        'brand': 'Pioneer',
        'model': 'SP-EC73',
        'type': 'passive',
        'price': '400',
        'shape': 'center',
        'amount': 'each',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/pioneer-elite-sp-ec73-center-speaker-review.12197/',
            },
        },
    },
    'PMC Twenty 21': {
        'brand': 'PMC',
        'model': 'Twenty 21',
        'type': 'passive',
        'price': '2000',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/pmc-twenty-21-bookshelf-speaker-review.14442/',
            },
        },
    },
    'Polk Audio RT15i': {
        'brand': 'Polk Audio',
        'model': 'RT15i',
        'type': 'passive',
        'price': '',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-Polk Audio',
                'format': 'rewstextdump',
                'review': '',
            },
        },
    },
    'Polk Audio 5JR': {
        'brand': 'Polk Audio',
        'model': '5JR',
        'type': 'passive',
        'price': '',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
                'review': '',
            },
        },
    },
    'Polk Audio Signature S15': {
        'brand': 'Polk Audio',
        'model': 'Signature S15',
        'type': 'passive',
        'price': '230',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/polk-audio-signature-s15-speaker-review.15437/',
            },
        },
    },
    'Polk Audio T15': {
        'brand': 'Polk Audio',
        'model': 'T15',
        'type': 'passive',
        'price': '100',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/polk-t15-bookshelf-speaker-review.11720/',
            },
        },
    },
    'Presonus Eris E5 XT': {
        'brand': 'Presonus',
        'model': 'Eris E5 XT',
        'type': 'active',
        'price': '260',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/presonus-e5-xt-active-speaker-review.13436/',
            },
        },
    },
    'PSB Alpha P5': {
        'brand': 'PSB',
        'model': 'Alpha P5',
        'type': 'passive',
        'price': '349',
        'shape': 'bookshelves',
        'amount': 'each',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/psb-alpha-p5-speaker-review.15161/',
            },
        },
    },
    'Q Acoustics 3020i': {
        'brand': 'Q Acoustics',
        'model': '3020i',
        'type': 'passive',
        'price': '315',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/q-acoustics-3020i-bookshelf-speaker-review.14568/',
            },
        },
    },
    'Quad Electroacoustics ESL-57': {
        'brand': 'Quad Electroacoustics',
        'model': 'ESL-57',
        'type': 'passive',
        'shape': 'floorstanders',
        'price': '',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
             },
        },
    },
    'Realistic MC-1000': {
        'brand': 'Realistic',
        'model': 'MC-1000',
        'type': 'passive',
        'price': '60',
        'shape': 'bookshelves',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/mc-1000-best-speaker-in-the-world.11283/',
            },
        },
    },
    'Revel C25': {
        'brand': 'Revel',
        'model': 'C25',
        'type': 'passive',
        'shape': 'center',
        'price': '',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-Revel',
                'website': 'www.revel.com',
                'format': 'webplotdigitizer',
            },
        },
    },
    'Revel C52': {
        'brand': 'Revel',
        'model': 'C52',
        'type': 'passive',
        'price': '2500',
        'shape': 'center',
        'amount': 'each',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/mc-1000-best-speaker-in-the-world.11283/',
            },
        },
    },
    'Revel F206': {
        'brand': 'Revel',
        'model': 'F206',
        'type': 'passive',
        'price': '',
        'shape': 'floorstanders',
        'amount': 'pair',
        'default_measurement': 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-Revel',
                'format': 'webplotdigitizer',
            },
        },
    },
    'Revel F208': {
        'brand': 'Revel',
        'model': 'F208',
        'type': 'passive',
        'price': '5000',
        'shape': 'floorstanders',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/revel-f208-tower-speaker-review.13192/',
            },
            'vendor' : {
                'origin': 'Vendors-Revel',
                'website': 'www.revel.com',
                'format': 'webplotdigitizer',
            },
        },
    },
    'Revel F226be': {
        'brand': 'Revel',
        'model': 'F226be',
        'type': 'passive',
        'price': '',
        'shape': 'floorstanders',
        'amount': 'pair',
        'default_measurement': 'eac',
        'measurements': {
            'eac': {
                'origin': 'ErinsAudioCorner',
                'format': 'splHVtxt',
                'review': 'https://www.erinsaudiocorner.com/loudspeakers/revel_f226be/',
            },
            'vendor': {
                'origin': 'Vendors-Revel',
                'format': 'webplotdigitizer',
            },
        },
    },
    'Revel F328be': {
        'brand': 'Revel',
        'model': 'F328be',
        'type': 'passive',
        'price': '16000',
        'shape': 'floorstanders',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/revel-f328be-speaker-review.17443/',
            },
            'vendor': {
                'origin': 'Vendors-Revel',
                'format': 'webplotdigitizer',
            },
        },
    },
    'Revel F35': {
        'brand': 'Revel',
        'model': 'F35',
        'type': 'passive',
        'price': '1600',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/revel-f35-speaker-review.12053/',
            },
        },
    },
    'Revel M105': {
        'brand': 'Revel',
        'model': 'M105',
        'type': 'passive',
        'price': '1500',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/revel-m105-bookshelf-speaker-review.14745/',
            },
        },
    },
    'Revel M106': {
        'brand': 'Revel',
        'model': 'M106',
        'type': 'passive',
        'price': '4000',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/revel-m106-bookshelf-speaker-review.14363/',
            },
        },
    },
    'Revel M16': {
        'brand': 'Revel',
        'model': 'M16',
        'type': 'passive',
        'price': '900',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/revel-m16-speaker-review.11884/',
            },
            'vendor': {
                'origin': 'Vendors-Revel',
                'format': 'webplotdigitizer',
                'review': '',
            },
        },
    },
    'Revel M22': {
        'brand': 'Revel',
        'model': 'M22',
        'type': 'passive',
        'price': '2000',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/revel-m22-speaker-review.12279/',
            },
        },
    },
    'Revel M55XC': {
        'brand': 'Revel',
        'model': 'M55XC',
        'type': 'passive',
        'price': '420',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/revel-m55xc-outdoor-speaker-review.14881/',
            },
        },
    },
    'Revel Ultima Salon': {
        'brand': 'Revel',
        'model': 'Ultima Salon',
        'type': 'passive',
        'price': '',
        'shape': 'floorstanders',
        'amount': 'pair',
        'default_measurement' : 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-Revel',
                'website': 'www.revel.com',
                'format': 'webplotdigitizer',
            },
        },
    },
    'Revel Ultima Salon2': {
        'brand': 'Revel',
        'model': 'Ultima Salon2',
        'type': 'passive',
        'price': '',
        'shape': 'floorstanders',
        'amount': 'pair',
        'default_measurement': 'harman-v2-2017',
        'measurements': {
            'harman-v1-2007': {
                'origin': 'Vendors-Revel',
                'website': 'www.revel.com',
                'format': 'webplotdigitizer',
            },
            'harman-v2-2017': {
                'origin': 'Vendors-Revel',
                'website': 'www.revel.com',
                'format': 'webplotdigitizer',
            },
        },
    },
    'RSL Outsider II': {
        'brand': 'RSL',
        'model': 'Outsider II',
        'type': 'passive',
        'price': '300',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/rsl-outsider-ii-outdoor-speaker-review.16659/',
            },
        },
    },
    'Salk WoW1': {
        'brand': 'Salk',
        'model': 'WoW1',
        'type': 'passive',
        'price': '1295',
        'shape': 'bookshelves',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/salk-wow1-bookshelf-speaker-review.14842/',
            },
        },
    },
    'Sanders Sound Systems Model 11': {
        'brand': 'Sanders Sound Systems',
        'model': 'Model 11',
        'type': 'passive',
        'price': '',
        'shape': 'floorstanders',
        'default_measurement': 'princeton-factory',
        'measurements': {
            'princeton-factory': {
                'origin': 'Princeton',
                'format': 'princeton',
            },
            'princeton-with-anechoic-foam': {
                'origin': 'Princeton',
                'format': 'princeton',
            },
            'princeton-with-backwave-absorber': {
                'origin': 'Princeton',
                'format': 'princeton', },
        },
    },
    'Selah Audio Integrity DIY': {
        'brand': 'Selah Audio',
        'model': 'Integrity DIY',
        'type': 'passive',
        'price': '700',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/selah-integrity-diy-speaker-kit-review.15695/',
            },
        },
    },
    'Selah Audio Purezza': {
        'brand': 'Selah Audio',
        'model': 'Purezza',
        'type': 'passive',
        'shape': 'bookshelves',
        'price': '2700',
        'default_measurement' : 'eac-original',
        'measurements': {
            'eac-original': {
                'origin': 'ErinsAudioCorner',
                'format': 'splHVtxt',
                'review': 'https://www.erinsaudiocorner.com/loudspeakers/selah_audio_purezza/',
            },
            'eac-eq': {
                'origin': 'ErinsAudioCorner',
                'format': 'splHVtxt',
                'review': 'https://www.erinsaudiocorner.com/loudspeakers/selah_audio_purezza/',
            },
        },
    },
    'Selah Audio RC3R': {
        'brand': 'Selah Audio',
        'model': 'RC3R',
        'type': 'passive',
        'price': '1300',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/selah-audio-rc3r-3-way-speaker-review.11218/',
            },
        },
    },
    'Sehlin Helium DIY': {
        'brand': 'Sehlin',
        'model': 'Helium DIY',
        'type': 'passive',
        'price': '140',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/sehlin-helium-diy-speaker-review.15518/',
            },
        },
    },
    'Sony SS-CS5': {
        'brand': 'Sony',
        'model': 'SS-CS5',
        'type': 'passive',
        'price': '150',
        'shape': 'bookshelves',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/sony-ss-cs5-3-way-speaker-review.13562/',
            },
        },
    },
    'Spendor Audio Systems SA1': {
        'brand': 'Spendor Audio',
        'model': 'Systems SA1',
        'type': 'passive',
        'price': '',
        'shape': 'bookshelves',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
             },
        },
    },
    'SVS Ultra Bookshelf': {
        'brand': 'SVS',
        'model': 'Ultra Bookshelf',
        'type': 'passive',
        'price': '1000',
        'amount': 'pair',
        'shape': 'bookshelves',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/svs-ultra-bookshelf-speaker-review.15055/',
             },
        },
    },
    'Tannoy Definition DC6i': {
        'brand': 'Tannoy',
        'model': 'Definition DC6i',
        'type': 'passive',
        'price': '',
        'shape': 'floorstanders',
        'default_measurement': 'princeton',
        'measurements': {
            'princeton': {
                'origin': 'Princeton',
                'format': 'princeton',
             },
        },
    },
    'Tannoy Revolution XT6': {
        'brand': 'Tannoy',
        'model': 'Revolution XT6',
        'type': 'passive',
        'price': '1400',
        'shape': 'floorstanders',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/tannoy-revolution-xt-6-speaker-review.14662/',
             },
        },
    },
    'Tannoy System 600': {
        'brand': 'Tannoy',
        'model': 'System 600',
        'type': 'passive',
        'price': '',
        'shape': 'bookshelves',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/tannoy-system-600-speaker-review.11919/',
            },
        },
    },
    'Vanatoo Transparent Zero': {
        'brand': 'Vanatoo',
        'model': 'Transparent Zero',
        'type': 'passive',
        'price': '350',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/vanatoo-transparent-zero-speaker-review.13717/',
            },
        },
    },
    'Verdant Audio Bambusa AL 1': {
        'brand': 'Verdant Audio',
        'model': 'Bambusa AL 1',
        'type': 'passive',
        'price': '3500',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/verdant-audio-bambusa-al-1-review.12562/',
            },
        },
    },
    'Verdant Audio Bambusa MG 1': {
        'brand': 'Verdant Audio',
        'model': 'Bambusa MG 1',
        'type': 'passive',
        'price': '5000',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/verdant-audio-bambusa-mg-1-speaker-review.12385/',
            },
        },
    },
    'Wharfedale Diamond 220': {
        'brand': 'Wharfedale',
        'model': 'Diamond 220',
        'type': 'passive',
        'price': '200',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/wharfedale-diamond-220-budget-speaker-review.16752/',
            },
        },
    },
    'Yamaha HS5': {
        'brand': 'Yamaha',
        'model': 'HS5',
        'type': 'active',
        'price': '399',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/yamaha-hs5-powered-monitor-review.10967/',
            },
        },
    },
    'Yamaha NS-A638': {
        'brand': 'Yamaha',
        'model': 'NS-A638',
        'type': 'passive',
        'price': '',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'vendor',
        'measurements': {
            'vendor': {
                'origin': 'Vendors-Yamaha',
                'format': 'rewstextdump',
                'review': '',
            },
        },
    },
    'Yamaha NS-6490': {
        'brand': 'Yamaha',
        'model': 'NS-6490',
        'type': 'passive',
        'price': '130',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': 'https://www.audiosciencereview.com/forum/index.php?threads/yamaha-ns-6490-3-way-budget-speaker-review.17042/',
            },
        },
    },
    'Zaph Audio ZA5': {
        'brand': 'Zaph Audio',
        'model': 'ZA5',
        'type': 'passive',
        'price': '350',
        'shape': 'bookshelves',
        'amount': 'pair',
        'default_measurement': 'asr',
        'measurements': {
            'asr': {
                'origin': 'ASR',
                'format': 'klippel',
                'review': '',
            },
        },
    },
}

# add some information about precisions of graphs
origins_info = {
    # for example the Princeton 3d3a measurements are valid >500hz
    'ASR': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/asr.png',
        'logo-small': 'docs/metadata/asr-small.png',
        'url': 'http://www.audiosciencereview.com',
    },
    'Princeton': {
        'min hz': 500,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/3d3a.jpg',
        'logo-small': 'docs/metadata/3d3a.jpg',
        'url': 'https://www.princeton.edu/3D3A/Directivity.html',
    },
    'ErinsAudioCorner': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/eac.png',
        'logo-small': 'docs/metadata/eac.png',
        'url': 'https://www.erinsaudiocorner.com',
    },
    'Misc': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': '',
        'logo-small': '',
        'url': '',
    },
    'Vendors-Apple': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/apple.png',
        'logo-small': 'docs/metadata/apple.png',
        'url': 'https://www.apple.com',
    },
    'Vendors-BIC America': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/BIC America.jpg',
        'logo-small': 'docs/metadata/BIC America.jpg',
        'url': 'https://bicamerica.com/',
    },
    'Vendors-Buchardt Audio': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/buchardt-audio.png',
        'logo-small': 'docs/metadata/buchardt-audio-small.png',
        'url': 'https://www.buchardtaudio.com',
    },
    'Vendors-Bose': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/bose.png',
        'logo-small': 'docs/metadata/bose.png',
        'url': 'https://www.bose.com',
    },
    'Vendors-Bowers & Wilkins': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/bose.png',
        'logo-small': 'docs/metadata/bose.png',
        'url': 'https://www.bowerswilkins.com/',
    },
    'Vendors-Cambridge Soundworks': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/.png',
        'logo-small': 'docs/metadata/.png',
        'url': 'https://en.wikipedia.org/wiki/Cambridge_SoundWorks',
    },
    'Vendors-Infinity': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/infinity.png',
        'logo-small': 'docs/metadata/infinity-small.png',
        'url': 'https://www.infinityspeakers.com',
    },
    'Vendors-GGNTKT': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/ggntkt.png',
        'logo-small': 'docs/metadata/ggntkt-small.png',
        'url': 'https://www.ggntkt.de',
    },
    'Vendors-JBL': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/jbl.png',
        'logo-small': 'docs/metadata/jbl-small.png',
        'url': 'https://www.jbl.com',
    },
    'Vendors-JTR': {
        'min hz': 50,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/jtr.png',
        'logo-small': 'docs/metadata/jtr-small.png',
        'url': 'https://www.jtrspeakers.com',
    },
    'Vendors-KLH': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/klh.png',
        'logo-small': 'docs/metadata/klh-small.png',
        'url': 'https://www.klh.com',
    },
    'Vendors-KEF': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/kef.png',
        'logo-small': 'docs/metadata/kef.png',
        'url': 'https://www.kef.com',
    },
    'Vendors-Klipsch': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/klipsch.png',
        'logo-small': 'docs/metadata/klipsch.png',
        'url': 'https://www.klipsch.com',
    },
    'Vendors-Magico': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/magico.png',
        'logo-small': 'docs/metadata/magico.png',
        'url': 'https://www.magicoaudio.com',
    },
    'Vendors-Mesanovic': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/mesanovic.png',
        'logo-small': 'docs/metadata/mesanovic.png',
        'url': 'https://www.mesanovicmicrophones.com',
    },
    'Vendors-Pioneer': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/pioneer.png',
        'logo-small': 'docs/metadata/pioneer.png',
        'url': 'https://www.pioneer.com',
    },
    'Vendors-PMC': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/pmc.png',
        'logo-small': 'docs/metadata/pmc.png',
        'url': 'https://www.pmc-speakers.com/',
    },
    'Vendors-Polk Audio': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/polkaudio.png',
        'logo-small': 'docs/metadata/polkaudio.png',
        'url': 'https://www.polkaudio.com',
    },
    'Vendors-Revel': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/revel.png',
        'logo-small': 'docs/metadata/jbl-small.png',
        'url': 'http://www.revel.com',
    },
    'Vendors-Yamaha': {
        'min hz': 20,
        'max hz': 20000,
        'min dB': -40,
        'max dB': 10,
        'logo': 'docs/metadata/yamaha.png',
        'logo-small': 'docs/metadata/yamaha-small.png',
        'url': 'http://www.yamaha.com',
    },
}
