from . import SpeakerDatabase, gll_data_acquisition_std

speakers_info_o: SpeakerDatabase = {
    "Ocean Way HR5": {
        "brand": "Ocean Way",
        "model": "HR5",
        "type": "active",
        "price": "2800",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/ocean-way-hr5-studio-monitor-review.13925",
                "review_published": "20200608",
            },
        },
    },
    "Onesystems 108HTH": {
        "brand": "Onesystems",
        "model": "108HTH",
        "type": "passive",
        "price": "1200",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-105x60",
        "measurements": {
            "vendor-pattern-105x60": {
                "origin": "Vendors-Onesystems",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "low",
                "review_published": "20230327",
            },
        },
    },
    "Onesystems 208HTC": {
        "brand": "Onesystems",
        "model": "208HTC",
        "type": "passive",
        "price": "1400",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Onesystems",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "low",
                "review_published": "20230327",
            },
        },
    },
    "Onesystems 212HC": {
        "brand": "Onesystems",
        "model": "212HC",
        "type": "passive",
        "price": "2700",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Onesystems",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "low",
                "review_published": "20230327",
            },
        },
    },
    "Onesystems 312HC": {
        "brand": "Onesystems",
        "model": "312HC",
        "type": "passive",
        "price": "3900",
        "amount": "each",
        "shape": "liveportable",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Onesystems",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "low",
                "review_published": "20230327",
            },
        },
    },
    "Optimal Audio Cuboid 3": {
        "brand": "Optimal Audio",
        "model": "Cuboid 3",
        "type": "passive",
        "price": "85",
        "amount": "each",
        "shape": "bookshelves",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Optimal Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "low",
                "review_published": "20231020",
                "specifications": {
                    "dispersion": {
                        "horizontal": 130,
                        "vertical": 120,
                    },
                    "sensitivity": 84,
                    "impedance": 16,
                    "size": {
                        "height": 190,
                        "width": 120,
                        "depth": 118,
                    },
                    "weight": 1.26,
                },
            },
        },
    },
    "Optimal Audio Cuboid 5": {
        "brand": "Optimal Audio",
        "model": "Cuboid 5",
        "type": "passive",
        "price": "110",
        "amount": "each",
        "shape": "bookshelves",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Optimal Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "low",
                "review_published": "20231020",
                "specifications": {
                    "dispersion": {
                        "horizontal": 150,
                        "vertical": 100,
                    },
                    "sensitivity": 88,
                    "impedance": 8,
                    "size": {
                        "height": 255,
                        "width": 155,
                        "depth": 150,
                    },
                    "weight": 2.15,
                },
            },
        },
    },
    "Optimal Audio Cuboid 8": {
        "brand": "Optimal Audio",
        "model": "Cuboid 8",
        "type": "passive",
        "price": "490",
        "amount": "each",
        "shape": "bookshelves",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Optimal Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "low",
                "review_published": "20231020",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 50,
                    },
                    "sensitivity": 92,
                    "impedance": 8,
                    "size": {
                        "height": 422,
                        "width": 256,
                        "depth": 261,
                    },
                    "weight": 10.0,
                },
            },
        },
    },
    "Optimal Audio Cuboid 10": {
        "brand": "Optimal Audio",
        "model": "Cuboid 10",
        "type": "passive",
        "price": "660",
        "amount": "each",
        "shape": "bookshelves",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Optimal Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "low",
                "review_published": "20231020",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 50,
                    },
                    "SPL": {
                        "max": 120,
                        "peak": 126,
                    },
                    "sensitivity": 96,
                    "impedance": 8,
                    "size": {
                        "height": 524,
                        "width": 322,
                        "depth": 326,
                    },
                    "weight": 16.0,
                },
            },
        },
    },
    "Optimal Audio Cuboid 12": {
        "brand": "Optimal Audio",
        "model": "Cuboid 12",
        "type": "passive",
        "price": "760",
        "amount": "each",
        "shape": "bookshelves",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Optimal Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "low",
                "review_published": "20231020",
                "specifications": {
                    "dispersion": {
                        "horizontal": 80,
                        "vertical": 50,
                    },
                    "SPL": {
                        "max": 123,
                        "peak": 129,
                    },
                    "sensitivity": 98,
                    "impedance": 8,
                    "size": {
                        "height": 575,
                        "width": 360,
                        "depth": 392,
                    },
                    "weight": 20.0,
                },
            },
        },
    },
    "Optimal Audio Cuboid 15": {
        "brand": "Optimal Audio",
        "model": "Cuboid 15",
        "type": "passive",
        "price": "1035",
        "amount": "each",
        "shape": "bookshelves",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Optimal Audio",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "low",
                "review_published": "20231020",
                "specifications": {
                    "dispersion": {
                        "horizontal": 80,
                        "vertical": 50,
                    },
                    "SPL": {
                        "max": 126,
                        "peak": 132,
                    },
                    "sensitivity": 99,
                    "impedance": 8,
                    "size": {
                        "height": 691,
                        "width": 626,
                        "depth": 416,
                    },
                    "weight": 28.0,
                },
            },
        },
    },
    "OS Acoustics DBS8": {
        "brand": "OS Acoustics",
        "model": "DBS8",
        "type": "active",
        "price": "2800",
        "amount": "each",
        "shape": "bookshelves",
        "default_measurement": "misc-sr",
        "measurements": {
            "misc-sr": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "reviews": {
                    "sr": "https://www.soundandrecording.de/equipment/o-s-acoustics-dbs8-2-wege-monitor-im-test/",
                    "sos": "https://www.soundonsound.com/reviews/os-acoustics-dbs8",
                },
                "review_published": "20221228",
                "specifications": {
                    "dispersion": {
                        "horizontal": 90,
                        "vertical": 50,
                    },
                    "sensitivity": 92,
                    "impedance": 8,
                    "size": {
                        "height": 422,
                        "width": 256,
                        "depth": 261,
                    },
                    "weight": 10.0,
                },
            },
        },
    },
    "OSD Audio AP650": {
        "brand": "OSD Audio",
        "model": "AP650",
        "type": "passive",
        "price": "200",
        "shape": "outdoor",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/osd-ap650-review-outdoor-speaker.20229/",
                "review_published": "20210208",
            },
        },
    },
    "Outlaw Audio BLSv2": {
        "brand": "Outlaw Audio",
        "model": "BLSv2",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-audioholics",
        "measurements": {
            "misc-audioholics": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://www.audioholics.com/bookshelf-speaker-reviews/outlaw-blsv2/conclusion",
            },
        },
    },
    "Outlaw Audio LCRv2": {
        "brand": "Outlaw Audio",
        "model": "LCRv2",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-audioholics-vertical",
        "measurements": {
            "misc-audioholics-vertical": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://www.audioholics.com/bookshelf-speaker-reviews/outlaw-blsv2/conclusion",
            },
            "misc-audioholics-horizontal": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://www.audioholics.com/bookshelf-speaker-reviews/outlaw-blsv2/conclusion",
            },
        },
    },
}
