# extra speaker info
speakers_info = {
    'Adam S2V': {
        'brand': 'Adam',
        'model': 'S2V',
        'type': 'active',
        'price': '1750',
        'origin': 'https://www.audiosciencereview.com/',
        'format': 'klippel',
        },
    'Dayton Audio B652-AIR': {
        'brand': 'Dayton Audio',
        'model': 'B652-AIR',
        'type': 'passive',
        'price': '',
        'origin': 'https://www.audiosciencereview.com/',
        'format': 'klippel',
        },
    'JBL 104': {
        'brand': 'JBL',
        'model': '104',
        'type': 'passive',
        'price': '',
        'origin': 'https://www.audiosciencereview.com/',
        'format': 'klippel',
        },
    'Kali IN-8': {
        'brand': 'Kali',
        'model': 'IN-8',
        'type': 'active',
        'price': '',
        'origin': 'https://www.audiosciencereview.com/',
        'format': 'klippel',
        },
    'Pioneer SP-BS22-LR': {
        'brand': 'Pioneer',
        'model': 'SP-BS22-LR',
        'type': 'passive',
        'price': '',
        'origin': 'https://www.audiosciencereview.com/',
        'format': 'klippel',
        },
    'Revel C52': {
        'brand': 'Revel',
        'model': 'C52',
        'type': 'passive',
        'price': '',
        'origin': 'https://www.audiosciencereview.com/',
        'format': 'klippel',
        },
    'Elac Adante AS-61': {
        'brand': 'Elac',
        'model': 'Adante AS-61',
        'type': 'passive',
        'price': '',
        'origin': 'https://www.audiosciencereview.com/',
        'format': 'klippel',
        },
    'Emotiva Airmotive 6s': {
        'brand': 'Emotiva',
        'model': 'Airmotiv 6s',
        'type': 'passive',
        'price': '',
        'origin': 'https://www.audiosciencereview.com/',
        'format': 'klippel',
        },
    'JBL Control 1 Pro': {
        'brand': 'JBL',
        'model': 'Control 1 Pro',
        'type': 'active',
        'price': '',
        'origin': 'https://www.audiosciencereview.com/',
        'format': 'klippel',
        },
    'Micca RB42': {
        'brand': 'Micca',
        'model': 'RB42',
        'type': 'passive',
        'price': '',
        'origin': 'https://www.audiosciencereview.com/',
        'format': 'klippel',
        },
    'Selah Audio RC3R': {
        'brand': 'Selah Audio',
        'model': 'RC3R',
        'type': 'passive',
        'price': '',
        'origin': 'https://www.audiosciencereview.com/',
        'format': 'klippel',
        },
    'Harbeth Monitor': {
        'brand': 'Harbeth',
        'model': 'Monitor 30.0',
        'type': 'passive',
        'price': '',
        'origin': 'https://www.audiosciencereview.com/',
        'format': 'klippel',
        },
    'KEF LS50': {
        'brand': 'KEF',
        'model': 'LS50',
        'type': 'passive',
        'price': '',
        'origin': 'https://www.audiosciencereview.com/',
        'format': 'klippel',
        },
    'KEF Reference 5': {
        'brand': 'KEF',
        'model': 'Reference 5',
        'type': 'passive',
        'price': '',
        'origin': 'https://www.kef.com/',
        'format': 'webplotdigitizer',
        },
    'Neumann KH 80': {
        'brand': 'Neumann',
        'model': 'KH 80',
        'type': 'active',
        'price': '',
        'origin': 'https://www.audiosciencereview.com/',
        'format': 'klippel',
        },
    'Realistic MC-1000': {
        'brand': 'Realistic',
        'model': 'MC-1000',
        'type': 'passive',
        'price': '',
        'origin': 'https://www.audiosciencereview.com/',
        'format': 'klippel',
        },
    'Yamaha HS5': {
        'brand': 'Yamaha',
        'model': 'HS5',
        'type': 'active',
        'price': '',
        'origin': 'https://www.audiosciencereview.com/',
        'format': 'klippel',
        },
    'NHT Pro M-00': {
        'brand': 'NHT',
        'model': 'Pro M-00',
        'type': 'active',
        'price': '',
        'origin': 'https://www.audiosciencereview.com/',
        'format': 'klippel',
        },
}
