# -*- coding: utf-8 -*-
from . import SpeakerDatabase, gll_data_acquisition_std

speakers_info_p: SpeakerDatabase = {
    "Palmer Studimon 5": {
        "brand": "Palmer",
        "model": "Studimon 5",
        "type": "active",
        "price": "500",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-sr",
        "measurements": {
            "misc-sr": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://www.soundandrecording.de/equipment/palmer-studimon-5-preiswerter-2-wege-nahfeldmonitor-im-test/",
                "review_published": "20220710",
            },
        },
    },
    "Paradigm Cinema 100": {
        "brand": "Paradigm",
        "model": "Cinema 100",
        "type": "passive",
        "price": "100",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/paradigm-cinema-100-review-home-theater-speakers.22597/",
                "review_published": "20210418",
            },
        },
    },
    "Paradigm Founder 70LCR": {
        "brand": "Paradigm",
        "model": "Founder 70LCR",
        "type": "passive",
        "price": "1700",
        "shape": "bookshelves",
        "amount": "each",
        "default_measurement": "misc-audioholics",
        "measurements": {
            "misc-audioholics": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "reviews": {
                    "adh": "https://www.audioholics.com/tower-speaker-reviews/paradigm-founder-100f-70lcr/conclusion",
                    "paradigm": "https://www.paradigm.com/en/center/founder-70lcr",
                },
                "review_published": "20220109",
            },
        },
    },
    "Paradigm Monitor SE Atom": {
        "brand": "Paradigm",
        "model": "Monitor SE Atom",
        "type": "passive",
        "price": "239",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/paradigm-monitor-se-atom-speaker-review.17837/",
                "review_published": "20201124",
            },
        },
    },
    "Paradigm Millenia LP 2": {
        "brand": "Paradigm",
        "model": "Millenia LP 2",
        "type": "passive",
        "price": "550",
        "shape": "center",
        "amount": "each",
        "default_measurement": "misc-matthews",
        "measurements": {
            "misc-matthews": {
                "origin": "Misc",
                "format": "spl_hv_txt",
                "quality": "medium",
                "symmetry": "coaxial",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/paradigm-millenia-lp-2-review-measurements.47312/",
                "review_published": "20230823",
            },
        },
    },
    "Paradigm Persona 3F": {
        "brand": "Paradigm",
        "model": "Persona 3F",
        "type": "passive",
        "price": "6000",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "vendor",
        "measurements": {
            # TODO: data is truncated, should be artificially completed.
            "vendor": {
                "origin": "Vendors-Paradigm",
                "format": "webplotdigitizer",
            },
        },
    },
    "Paradigm Prestige 15B": {
        "brand": "Paradigm",
        "model": "Prestige 15B",
        "type": "passive",
        "price": "1600",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/paradigm-prestige-15b-review-bookshelf-speaker.19466/",
                "review_published": "20210117",
            },
        },
    },
    "Part Express DIY C-Note": {
        "brand": "Part Express",
        "model": "DIY C-Note",
        "type": "passive",
        "price": "100",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/parts-express-diy-c-note-speaker-review.12693/",
                "review_published": "20200419",
            },
        },
    },
    "Part Express DIY Copperhead": {
        "brand": "Part Express",
        "model": "DIY Copperhead",
        "type": "passive",
        "price": "100",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/parts_express_copperhead/",
                "review_published": "20220625",
            },
        },
    },
    "Part Express DIY Samba MT": {
        "brand": "Part Express",
        "model": "DIY Samba MT",
        "type": "passive",
        "price": "330",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/parts_express_samba_mt/",
                "review_published": "20220619",
            },
        },
    },
    "Part Express DIY Overnight Sensations MT": {
        "brand": "Part Express",
        "model": "DIY Overnight Sensations MT",
        "type": "passive",
        "price": "160",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/parts_express_overnight_sensation_mt/",
                "review_published": "20220621",
            },
        },
    },
    "Perlisten r4b": {
        "brand": "Perlisten",
        "model": "r4b",
        "type": "passive",
        "price": "2500",
        "shape": "bookshelves",
        "amount": "each",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Perlisten",
                "format": "webplotdigitizer",
                "reviews": {
                    "vendor": "https://www.perlistenaudio.com/downloads/",
                },
                "notes": "Warning: measurements provided by vendor (Perlisten) are smoothed",
                "review_published": "20220208",
                "quality": "low",
            },
        },
    },
    "Perlisten r4s": {
        "brand": "Perlisten",
        "model": "r4s",
        "type": "passive",
        "price": "2000",
        "shape": "bookshelves",
        "amount": "each",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Perlisten",
                "format": "webplotdigitizer",
                "reviews": {
                    "vendor": "https://www.perlistenaudio.com/downloads/",
                },
                "notes": "Warning: measurements provided by vendor (Perlisten) are smoothed",
                "review_published": "20231022",
                "quality": "medium",
                "specifications": {
                    "sensitivity": 86.5,
                    "impedance": 4,
                    "SPL": {
                        "max": 109,
                    },
                    "size": {
                        "height": 378,
                        "width": 230,
                        "depth": 173,
                    },
                    "weight": 9.5,
                },
            },
        },
    },
    "Perlisten r5t": {
        "brand": "Perlisten",
        "model": "r5t",
        "type": "passive",
        "price": "7000",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Perlisten",
                "format": "webplotdigitizer",
                "reviews": {
                    "vendor": "https://www.perlistenaudio.com/downloads/",
                },
                "notes": "Warning: measurements provided by vendor (Perlisten) are smoothed",
                "review_published": "20220208",
                "quality": "low",
            },
        },
    },
    "Perlisten r5c": {
        "brand": "Perlisten",
        "model": "r5c",
        "type": "passive",
        "price": "3000",
        "shape": "center",
        "amount": "each",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Perlisten",
                "format": "webplotdigitizer",
                "reviews": {
                    "vendor": "https://www.perlistenaudio.com/downloads/",
                },
                "notes": "Warning: measurements provided by vendor (Perlisten) are smoothed",
                "review_published": "20231025",
                "quality": "medium",
                "specifications": {
                    "sensitivity": 88.6,
                    "impedance": 4,
                    "SPL": {
                        "max": 109,
                    },
                    "size": {
                        "height": 240,
                        "width": 550,
                        "depth": 270,
                    },
                    "weight": 15.0,
                },
            },
        },
    },
    "Perlisten r5m": {
        "brand": "Perlisten",
        "model": "r5m",
        "type": "passive",
        "price": "3000",
        "shape": "bookshelves",
        "amount": "each",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Perlisten",
                "format": "webplotdigitizer",
                "reviews": {
                    "vendor": "https://www.perlistenaudio.com/downloads/",
                },
                "notes": "Warning: measurements provided by vendor (Perlisten) are smoothed",
                "review_published": "20231025",
                "quality": "medium",
                "specifications": {
                    "sensitivity": 89.2,
                    "impedance": 4,
                    "SPL": {
                        "max": 113,
                    },
                    "size": {
                        "height": 546,
                        "width": 230,
                        "depth": 336,
                    },
                    "weight": 17.5,
                },
            },
        },
    },
    "Perlisten r7t": {
        "brand": "Perlisten",
        "model": "r7t",
        "type": "passive",
        "price": "5000",
        "shape": "floorstanders",
        "amount": "each",
        "default_measurement": "vendor-vented",
        "measurements": {
            "vendor-vented": {
                "origin": "Vendors-Perlisten",
                "format": "webplotdigitizer",
                "reviews": {
                    "vendor": "https://www.perlistenaudio.com/downloads/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/perlisten-speakers.19745/",
                },
                "review_published": "20220208",
                "notes": "Vented measurements provided by Perlisten, note that smoothing is heavy and score will be overestimated",
                "quality": "low",
            },
            "vendor-sealed": {
                "origin": "Vendors-Perlisten",
                "format": "webplotdigitizer",
                "reviews": {
                    "vendor": "https://www.perlistenaudio.com/downloads/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/perlisten-speakers.19745/",
                },
                "notes": "Sealed measurements provided by Perlisten, note that smoothing is heavy and score will be overestimated",
                "review_published": "20220208",
                "quality": "low",
            },
        },
    },
    "Perlisten s4b": {
        "brand": "Perlisten",
        "model": "s4b",
        "type": "passive",
        "price": "8000",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/perlisten_s4b/",
                    "yt": "https://www.youtube.com/watch?v=53qOAQrwOz8",
                },
                "review_published": "20211024",
            },
            "vendor": {
                "origin": "Vendors-Perlisten",
                "format": "webplotdigitizer",
                "reviews": {
                    "vendor": "https://www.perlistenaudio.com/downloads/",
                },
                "notes": "Warning: measurements provided by vendor (Perlisten) are smoothed and diverge significantly from Erin's measurements",
                "review_published": "20220208",
                "quality": "low",
            },
        },
    },
    "Perlisten s4s": {
        "brand": "Perlisten",
        "model": "s4s",
        "type": "passive",
        "price": "7600",
        "shape": "surround",
        "amount": "pair",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Perlisten",
                "format": "webplotdigitizer",
                "reviews": {
                    "vendor": "https://www.perlistenaudio.com/downloads/",
                },
                "notes": "Warning: measurements provided by vendor (Perlisten) are smoothed",
                "review_published": "20220208",
                "quality": "low",
            },
        },
    },
    "Perlisten s5m": {
        "brand": "Perlisten",
        "model": "s5m",
        "type": "passive",
        "price": "14000",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "vendor-vented",
        "measurements": {
            "vendor-vented": {
                "origin": "Vendors-Perlisten",
                "format": "webplotdigitizer",
                "reviews": {
                    "vendor": "https://www.perlistenaudio.com/downloads/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/perlisten-speakers.19745/",
                },
                "review_published": "20220208",
                "notes": "Vented measurements provided by Perlisten, note that smoothing is heavy and score will be overestimated",
                "quality": "low",
            },
            "vendor-sealed": {
                "origin": "Vendors-Perlisten",
                "format": "webplotdigitizer",
                "reviews": {
                    "vendor": "https://www.perlistenaudio.com/downloads/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/perlisten-speakers.19745/",
                },
                "notes": "Sealed measurements provided by Perlisten, note that smoothing is heavy and score will be overestimated",
                "review_published": "20220208",
                "quality": "low",
            },
        },
    },
    "Perlisten s7c": {
        "brand": "Perlisten",
        "model": "s7c",
        "type": "passive",
        "price": "7500",
        "shape": "center",
        "amount": "each",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Perlisten",
                "format": "webplotdigitizer",
                "reviews": {
                    "vendor": "https://www.perlistenaudio.com/downloads/",
                },
                "notes": "Warning: measurements provided by vendor (Perlisten) are smoothed",
                "review_published": "20220208",
                "quality": "low",
            },
        },
    },
    "Perlisten s7t": {
        "brand": "Perlisten",
        "model": "s7t",
        "type": "passive",
        "price": "16000",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Perlisten",
                "format": "webplotdigitizer",
                "reviews": {
                    "vendor": "https://www.perlistenaudio.com/downloads/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/perlisten-speakers.19745/",
                },
                "review_published": "20220208",
                "quality": "low",
            },
            "misc-audioholics": {
                "origin": "Misc",
                "format": "rew_text_dump",
                "quality": "low",
                "reviews": {
                    "adh": "https://www.audioholics.com/tower-speaker-reviews/perlisten-s7t/conclusion",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/perlisten-speakers.19745/",
                },
            },
        },
    },
    "Pioneer DJ VM-50": {
        "brand": "Pioneer",
        "model": "DJ VM-50",
        "type": "active",
        "price": "340",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/pioneer_djvm50/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/pioneer%E2%80%99s-new-dj-vm-50-powered-monitors-review.24216/",
                },
                "review_published": "20210614",
            },
        },
    },
    "Pioneer S-DF3-K": {
        "brand": "Pioneer",
        "model": "S-DF3-K",
        "type": "passive",
        "price": "",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Pioneer",
                "format": "rew_text_dump",
                "review": "",
            },
        },
    },
    "Pioneer SP-C22": {
        "brand": "Pioneer",
        "model": "SP-C22",
        "type": "passive",
        "price": "75",
        "shape": "center",
        "amount": "each",
        "default_measurement": "asr-vertical",
        "measurements": {
            "asr-vertical": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/pioneer-sp-c22-review-center-speaker.33717/",
                "review_published": "20220505",
            },
            "asr-horizontal": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/pioneer-sp-c22-review-center-speaker.33717/",
                "review_published": "20220505",
            },
        },
    },
    "Pioneer SP-BS22-LR": {
        "brand": "Pioneer",
        "model": "SP-BS22-LR",
        "type": "passive",
        "price": "160",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/pioneer-sp-bs22-lr-bookshelf-speaker-review.11303/",
                "review_published": "20200207",
            },
        },
    },
    "Pioneer SP-EBS73-LR": {
        "brand": "Pioneer",
        "model": "SP-EBS73-LR",
        "type": "passive",
        "price": "750",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/pioneer-elite-sp-ebs73-lr-atmos-speaker-review.12163/",
                "review_published": "20200321",
            },
        },
    },
    "Pioneer SP-EC73": {
        "brand": "Pioneer",
        "model": "SP-EC73",
        "type": "passive",
        "price": "400",
        "shape": "center",
        "amount": "each",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/pioneer-elite-sp-ec73-center-speaker-review.12197/",
                "review_published": "20200323",
            },
        },
    },
    "PMC Twenty 21": {
        "brand": "PMC",
        "model": "Twenty 21",
        "type": "passive",
        "price": "2000",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/pmc-twenty-21-bookshelf-speaker-review.14442/",
                "review_published": "20200630",
            },
        },
    },
    "Polk Audio Atrium 4": {
        "brand": "Polk Audio",
        "model": "Atrium 4",
        "type": "passive",
        "price": "117",
        "shape": "outdoor",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/polk-atrium-4-review-outdoor-speaker.21056/",
                "review_published": "20210306",
            },
        },
    },
    "Polk Audio Legend L200": {
        "brand": "Polk Audio",
        "model": "Legend L200",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-napilopez",
        "measurements": {
            "misc-napilopez": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "reviews": {
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/polk-l200-low-spinorama-and-measurements.13191/",
                },
            },
            "misc-audioholics": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://www.audioholics.com/bookshelf-speaker-reviews/polk-l200-l400/conclusion",
            },
        },
    },
    "Polk Audio Legend L800": {
        "brand": "Polk Audio",
        "model": "Legend L800",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "cinema",
        "default_measurement": "misc-audioholics",
        "measurements": {
            "misc-audioholics": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://www.audioholics.com/tower-speaker-reviews/polk-legend-l800/conclusion",
            },
        },
    },
    "Polk Audio Monitor 40 Series II": {
        "brand": "Polk Audio",
        "model": "Monitor 40 Series II",
        "type": "passive",
        "price": "200",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/polk-monitor-40-series-ii-review-speaker.24146/",
                "review_published": "20210612",
            },
        },
    },
    "Polk Audio Reserve R100": {
        "brand": "Polk Audio",
        "model": "Reserve R100",
        "type": "passive",
        "price": "650",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "review": "https://www.erinsaudiocorner.com/loudspeakers/polk_r100/",
                "review_published": "20211209",
            },
        },
    },
    "Polk Audio Reserve R200": {
        "brand": "Polk Audio",
        "model": "Reserve R200",
        "type": "passive",
        "price": "700",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/polk_r200/",
                    "yt": "https://youtu.be/BzDClEAQsBU",
                },
                "review_published": "20230618",
            },
            "misc-napilopez": {
                "origin": "Misc",
                "format": "rew_text_dump",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/polk-reserve-r200-spinorama-and-measurements-a-really-nice-surprise.23502/#post-785637",
                "quality": "low",
                "review_published": "20210517",
            },
        },
    },
    "Polk Audio Reserve R350": {
        "brand": "Polk Audio",
        "model": "Reserve R350",
        "type": "passive",
        "price": "600",
        "shape": "center",
        "amount": "each",
        "default_measurement": "asr-vertical",
        "measurements": {
            "asr-vertical": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/polk-reserve-r350-review-center-speaker.27535/",
                "review_published": "20211024",
            },
            "asr-horizontal": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/polk-reserve-r350-review-center-speaker.27535/",
                "review_published": "20211024",
            },
        },
    },
    "Polk Audio Reserve R500": {
        "brand": "Polk Audio",
        "model": "Reserve R500",
        "type": "passive",
        "price": "650",
        "amount": "each",
        "shape": "floorstanders",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/polk_r500/",
                    "yt": "https://www.youtube.com/watch?v=yYewhU3ydwE",
                },
                "review_published": "20240312",
                "specifications": {
                    "sensitivity": 87,
                    "impedance": 4,
                    "size": {
                        "height": 1044,
                        "width": 255,
                        "depth": 349,
                    },
                    "weight": 17.7,
                },
            },
        },
    },
    "Polk Audio Reserve R700": {
        "brand": "Polk Audio",
        "model": "Reserve R700",
        "type": "passive",
        "price": "1100",
        "amount": "each",
        "shape": "floorstanders",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/polk_r700/",
                    "yt": "https://www.youtube.com/watch?v=E6APuGxTtJw",
                },
                "review_published": "20240727",
                "specifications": {
                    "sensitivity": 88,
                    "impedance": 4,
                    "size": {
                        "height": 1144,
                        "width": 320,
                        "depth": 428,
                    },
                    "weight": 35.9,
                },
            },
        },
    },
    "Polk Audio RT15i": {
        "brand": "Polk Audio",
        "model": "RT15i",
        "type": "passive",
        "price": "",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "vendor",
        "measurements": {
            "vendor": {
                "origin": "Vendors-Polk Audio",
                "format": "rew_text_dump",
                "review": "",
            },
        },
    },
    "Polk Audio Rti 10": {
        "brand": "Polk Audio",
        "model": "Rti 10",
        "type": "passive",
        "price": "",
        "amount": "pair",
        "shape": "floorstanders",
        "default_measurement": "misc-speakerdata2034",
        "measurements": {
            "misc-speakerdata2034": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://speakerdata2034.blogspot.com/2020/04/various-brands-spinorama-data-from.html",
            },
        },
    },
    "Polk Audio 5JR": {
        "brand": "Polk Audio",
        "model": "5JR",
        "type": "passive",
        "price": "",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "princeton",
        "measurements": {
            "princeton": {
                "origin": "Princeton",
                "format": "princeton",
                "review": "https://www.princeton.edu/3D3A/Directivity.html",
                "review_published": "20151001",
            },
        },
    },
    "Polk Audio Signature Elite ES20": {
        "brand": "Polk Audio",
        "model": "Signature Elite ES20",
        "type": "passive",
        "price": "349",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/polk-signature-elite-es20-review-bookshelf-speaker.33834/",
                "review_published": "20220510",
            },
        },
    },
    "Polk Audio Signature Elite ES60": {
        "brand": "Polk Audio",
        "model": "Signature Elite ES60",
        "type": "passive",
        "price": "540",
        "shape": "floorstanders",
        "amount": "each",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/polk-es60-tower-speaker-review.52064/",
                "review_published": "20240208",
                "specifications": {
                    "sensitivity": 90,
                    "size": {
                        "height": 1130,
                        "width": 216,
                        "depth": 399,
                    },
                    "weight": 23.6,
                },
            },
        },
    },
    "Polk Audio Signature S15": {
        "brand": "Polk Audio",
        "model": "Signature S15",
        "type": "passive",
        "price": "230",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/polk-audio-signature-s15-speaker-review.15437/",
                "review_published": "20200819",
            },
        },
    },
    "Polk Audio Signature S30": {
        "brand": "Polk Audio",
        "model": "Signature S30",
        "type": "passive",
        "price": "229",
        "shape": "center",
        "amount": "each",
        "default_measurement": "asr-vertical",
        "measurements": {
            "asr-vertical": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/polk-s30-center-speaker-review.24728/",
                "review_published": "20210704",
            },
            "asr-horizontal": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/polk-s30-center-speaker-review.24728/",
                "review_published": "20210704",
            },
        },
    },
    "Polk Audio T15": {
        "brand": "Polk Audio",
        "model": "T15",
        "type": "passive",
        "price": "100",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/polk-t15-bookshelf-speaker-review.11720/",
                "review_published": "20200226",
            },
        },
    },
    "Polk Audio T50": {
        "brand": "Polk Audio",
        "model": "T50",
        "type": "passive",
        "price": "300",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/polk-t50-review-floor-standing-speaker.24890/",
                "review_published": "20210712",
            },
        },
    },
    "Polk Audio XT15": {
        "brand": "Polk Audio",
        "model": "XT15",
        "type": "passive",
        "price": "200",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/polk_xt15/",
                },
                "review_published": "20220108",
            },
        },
    },
    "Polk Audio XT20": {
        "brand": "Polk Audio",
        "model": "XT20",
        "type": "passive",
        "price": "300",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/polk_xt20/",
                },
                "review_published": "20220108",
            },
        },
    },
    "Polk Audio XT30": {
        "brand": "Polk Audio",
        "model": "XT30",
        "type": "passive",
        "price": "200",
        "shape": "center",
        "amount": "each",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/polk_xt30/",
                },
                "review_published": "20220108",
            },
        },
    },
    "Polk Audio XT35": {
        "brand": "Polk Audio",
        "model": "XT35",
        "type": "passive",
        "price": "300",
        "shape": "center",
        "amount": "each",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/polk_xt35/",
                },
                "review_published": "20220108",
            },
        },
    },
    "Polk Audio XT60": {
        "brand": "Polk Audio",
        "model": "XT60",
        "type": "passive",
        "price": "500",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/polk_xt60/",
                },
                "review_published": "20220108",
            },
        },
    },
    "Polk Audio XT70": {
        "brand": "Polk Audio",
        "model": "XT70",
        "type": "passive",
        "price": "700",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/polk_xt70/",
                },
                "review_published": "20220108",
            },
        },
    },
    "Power Sound Audio MT-110-M": {
        "brand": "Power Sound Audio",
        "model": "MT-110-M",
        "type": "passive",
        "price": "1350",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/powersoundaudiomt110m/",
                },
                "review_published": "20231106",
                "specifications": {
                    "sensitivity": 95,
                    "impedance": 8,
                    "size": {
                        "height": 444,
                        "width": 279,
                        "depth": 356,
                    },
                    "weight": 13.6,
                },
            },
        },
    },
    "Presonus CDL12": {
        "brand": "Presonus",
        "model": "CDL12",
        "type": "active",
        "price": "1000",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-v1x",
        "measurements": {
            "vendor-v1x": {
                "origin": "Vendors-Presonus",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221125",
                "parameters": {
                    "mean_min": 50,
                    "mean_max": 500,
                },
            },
            "vendor-v2x": {
                "origin": "Vendors-Presonus",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221125",
                "parameters": {
                    "mean_min": 50,
                    "mean_max": 500,
                },
            },
            "vendor-v3x": {
                "origin": "Vendors-Presonus",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221125",
                "parameters": {
                    "mean_min": 50,
                    "mean_max": 500,
                },
            },
            "vendor-v4x": {
                "origin": "Vendors-Presonus",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221125",
                "parameters": {
                    "mean_min": 50,
                    "mean_max": 500,
                },
            },
            "vendor-v5x": {
                "origin": "Vendors-Presonus",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221125",
                "parameters": {
                    "mean_min": 50,
                    "mean_max": 500,
                },
            },
            "vendor-v6x": {
                "origin": "Vendors-Presonus",
                "data_acquisition": gll_data_acquisition_std,
                "format": "gll_hv_txt",
                "quality": "medium",
                "review_published": "20221125",
                "parameters": {
                    "mean_min": 30,
                    "mean_max": 100,
                },
            },
        },
    },
    "Presonus Eris E3.5": {
        "brand": "Presonus",
        "model": "Eris E3.5",
        "type": "active",
        "price": "110",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/presonus_eris_e3_5/",
                    "asr": "https://www.audiosciencereview.com/forum/index.php?threads/presonus-eris-e3-5-powered-monitor-review-100-pair.23388/",
                },
                "review_published": "20210514",
            },
        },
    },
    "Presonus Eris E3.5 2nd edition": {
        "brand": "Presonus",
        "model": "Eris E3.5 2nd edition",
        "type": "active",
        "price": "100",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/presonus_eris3.5_mk2/",
                },
                "review_published": "20231009",
            },
        },
    },
    "Presonus Eris E5 XT": {
        "brand": "Presonus",
        "model": "Eris E5 XT",
        "type": "active",
        "price": "260",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/presonus-e5-xt-active-speaker-review.13436/",
                "review_published": "20200516",
            },
        },
    },
    "Presonus ULT10": {
        "brand": "Presonus",
        "model": "ULT10",
        "type": "active",
        "price": "830",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-110x50",
        "measurements": {
            "vendor-pattern-110x50": {
                "origin": "Vendors-Presonus",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221125",
            },
        },
    },
    "Presonus ULT12": {
        "brand": "Presonus",
        "model": "ULT12",
        "type": "active",
        "price": "1000",
        "amount": "pair",
        "shape": "liveportable",
        "default_measurement": "vendor-pattern-110x50",
        "measurements": {
            "vendor-pattern-110x50": {
                "origin": "Vendors-Presonus",
                "format": "gll_hv_txt",
                "data_acquisition": gll_data_acquisition_std,
                "quality": "medium",
                "review_published": "20221125",
            },
        },
    },
    "Presonus Eris E8 XT": {
        "brand": "Presonus",
        "model": "Eris E8 XT",
        "type": "active",
        "price": "420",
        "amount": "pair",
        "shape": "bookshelves",
        "default_measurement": "misc-audioholics",
        "measurements": {
            "misc-audioholics": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://www.audioholics.com/bookshelf-speaker-reviews/presonus-eris-e8-xt/conclusion",
            },
        },
    },
    "PSB Alpha P3": {
        "brand": "PSB",
        "model": "Alpha P3",
        "type": "passive",
        "price": "249",
        "shape": "bookshelves",
        "amount": "each",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/psb-alpha-p3-review-bookshelf-speaker.27498/",
                "review_published": "20211022",
            },
        },
    },
    "PSB Alpha P5": {
        "brand": "PSB",
        "model": "Alpha P5",
        "type": "passive",
        "price": "349",
        "shape": "bookshelves",
        "amount": "each",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/psb-alpha-p5-speaker-review.15161/",
                "review_published": "20200806",
            },
        },
    },
    "PSAudio aspen FR10": {
        "brand": "PSAudio",
        "model": "aspen FR10",
        "type": "passive",
        "price": "10000",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/ps_audio_aspen_fr10/",
                    "yt": "https://youtu.be/BGmIT3jWfFg",
                },
                "review_published": "20240320",
                "specifications": {
                    "sensitivity": 86.5,
                    "impedance": 3.3,
                    "size": {
                        "height": 1054.1,
                        "width": 298.5,
                        "depth": 412.8,
                    },
                    "weight": 34.1,
                },
            },
        },
    },
    "PSB Alpha P3": {
        "brand": "PSB",
        "model": "Alpha P3",
        "type": "passive",
        "price": "249",
        "shape": "bookshelves",
        "amount": "each",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/psb-alpha-p3-review-bookshelf-speaker.27498/",
                "review_published": "20211022",
            },
        },
    },
    "PSB Alpha P5": {
        "brand": "PSB",
        "model": "Alpha P5",
        "type": "passive",
        "price": "349",
        "shape": "bookshelves",
        "amount": "each",
        "default_measurement": "asr",
        "measurements": {
            "asr": {
                "origin": "ASR",
                "format": "klippel",
                "review": "https://www.audiosciencereview.com/forum/index.php?threads/psb-alpha-p5-speaker-review.15161/",
                "review_published": "20200806",
            },
        },
    },
    "PSB Imagine B50": {
        "brand": "PSB",
        "model": "Imagine B50",
        "type": "passive",
        "price": "700",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/psb_b50/",
                    "yt": "",
                },
                "review_published": "20240330",
                "specifications": {
                    "sensitivity": 87,
                    "impedance": 4,
                    "size": {
                        "height": 300,
                        "width": 171,
                        "depth": 251,
                    },
                    "weight": 5.13,
                },
            },
        },
    },
    "PSB Imagine T65": {
        "brand": "PSB",
        "model": "Imagine T65",
        "type": "passive",
        "price": "2180",
        "shape": "floorstanders",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/psb_t65/",
                    "yt": "https://youtu.be/HXuFjZ5Q3vg",
                },
                "review_published": "20240312",
                "specifications": {
                    "sensitivity": 88,
                    "impedance": 4,
                    "size": {
                        "height": 986,
                        "width": 343,
                        "depth": 213,
                    },
                    "weight": 20.0,
                },
            },
        },
    },
    "PSI Audio A21-M": {
        "brand": "PSI Audio",
        "model": "A21-M",
        "type": "active",
        "price": "3100",
        "amount": "each",
        "shape": "bookshelves",
        "default_measurement": "misc-sr",
        "measurements": {
            "misc-sr": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://www.soundandrecording.de/equipment/psi-a21-m-grosser-nahfeldmonitor-im-test/",
                "review_published": "20221228",
                "specifications": {
                    "dispersion": {
                        "horizontal": 80,
                        "vertical": 30,
                    },
                    "SPL": {
                        "max": 106,
                        "peak": 121,
                    },
                    "size": {
                        "height": 400,
                        "width": 250,
                        "depth": 300,
                    },
                    "weight": 12.8,
                },
            },
        },
    },
    "Philharmonic BMR": {
        "brand": "Philharmonic",
        "model": "BMR",
        "type": "passive",
        "price": "2400",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac-v2-20220518",
        "measurements": {
            "eac-v2-20220518": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/philharmonic_bmr_v2/",
                },
                "review_published": "20220518",
            },
            "eac-v1-20211121": {
                "origin": "ErinsAudioCorner",
                "format": "spl_hv_txt",
                "quality": "medium",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/philharmonic_bmr/",
                    "asr": " https://www.audiosciencereview.com/forum/index.php?threads/philharmonic-bmr-speaker-review.14781/",
                },
                "review_published": "20211121",
            },
            "misc-audioholics": {
                "origin": "Misc",
                "format": "webplotdigitizer",
                "quality": "low",
                "review": "https://www.audioholics.com/bookshelf-speaker-reviews/bmr-philharmonitor-1/conclusion",
                "review_published": "20211121",
            },
        },
    },
    "Philharmonic Ceramic Mini": {
        "brand": "Philharmonic",
        "model": "Ceramic Mini",
        "type": "passive",
        "price": "850",
        "shape": "bookshelves",
        "amount": "pair",
        "default_measurement": "eac",
        "measurements": {
            "eac": {
                "origin": "ErinsAudioCorner",
                "format": "klippel",
                "reviews": {
                    "eac": "https://www.erinsaudiocorner.com/loudspeakers/philharmonic_ceramic_mini/",
                    "yt": "https://youtu.be/313qwtkdMxo",
                },
                "review_published": "20231124",
            },
        },
    },
}
