name: Spinorama Python

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: self-hosted # ubuntu-22.04.4

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.3"
    - run: which python
    - run: pwd
    - run: ls -la
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        sudo apt-get install -y build-essential selenium
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude .venv
    - name: Test metadata file
      run: |
        PYTHONPATH=.:./src:./src/spinorama:./src/website ./scripts/check_meta.py
    - name: Compilation of cython files
      run: |
        PYTHONPATH=.:./src cd src/spinorama && python setup.py build_ext --inplace && ln -s c_compute_scores.cpython-*.so c_compute_scores.so
    - name: Test with pytest
      run: |
        PYTHONPATH=.:./src:./src/spinorama:./src/website pytest tests
